---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Verifique se as LIFs de dados nas do node2 no node1 foram relocadas de node1 para node2 ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Migre agregados que não sejam raiz e LIFs de dados nas de volta para node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Após verificar a configuração de rede no nó 2, você precisa realocar as LIFs de dados NAS pertencentes ao nó 2 do nó 1 para o nó 2 e confirmar se as LIFs SAN existem no nó 2.

.Sobre esta tarefa
As LIFs remotas gerenciam o tráfego para as LUNs SAN durante o procedimento de atualização. A movimentação de LIFs SAN não é necessária para a integridade do cluster ou do serviço durante a atualização. As interfaces LIF da SAN não são movidas a menos que precisem ser mapeadas para novas portas.

Você verifica se as LIFs estão íntegras e localizadas nas portas corretas depois de colocar o nó 2 online.

.Passos
. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema executa as seguintes tarefas:

+
--
** Verificação do quorum do cluster
** Verificação da ID do sistema
** Verificação da versão da imagem
** Verificação da plataforma alvo
** Verificação de acessibilidade da rede


--
+
O sistema pausa a operação nesta etapa da verificação de acessibilidade da rede.

. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações:

+
--
** Verificação de integridade do cluster
** Verificação do status de LIF do cluster


--
+
Depois de executar essas verificações, o sistema relocaliza os agregados não-raiz e LIFs de dados nas de volta para node2, que agora está sendo executado na controladora de substituição.

+
A operação de substituição do controlador é interrompida após a conclusão da realocação de recursos.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
[source, cli]
----
system controller replace show-details
----
+
Se o procedimento de substituição do controlador estiver em pausa, verifique e corrija o erro, se houver, e então o problema `resume` para continuar a operação.

. Caso necessário, restaure e reverta as LIFs deslocadas ou migre e modifique manualmente as LIFs do nó 2 que não foram realocadas automaticamente para o nó 2.
+
[role="tabbed-block"]
====
.Restaurar e reverter LIFs deslocados
--
.. Liste quaisquer LIFs deslocados:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Se algum LIFs for deslocado, restaure o nó inicial de volta para node2:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrar e modificar LIFs manualmente
--
.. Migre os LIFs que não foram realocados automaticamente para o nó 2:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. Modifique o nó inicial e a porta inicial para as LIFs migradas:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. Retome a operação para solicitar ao sistema que execute as verificações posteriores necessárias:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações posteriores:

+
** Verificação do quorum do cluster
** Verificação de integridade do cluster
** Verificação de reconstrução de agregados
** Verificação do status do agregado
** Verificação do estado do disco
** Verificação do status de LIF do cluster
** Verificação do volume



