---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Verifique se as LIFs de dados nas do node2 no node1 foram relocadas de node1 para node2 ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Migre agregados que não sejam raiz e LIFs de dados nas de volta para node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depois de verificar a configuração de rede no node2 e antes de realocar agregados de node1 para node2, você verifica se os LIFs de dados nas pertencentes ao node2 que estão atualmente no node1 são relocados de node1 para node2. Você também deve verificar se as SAN LIFs existem no node2.

.Sobre esta tarefa
Os LIFs remotos manipulam o tráfego para LUNs SAN durante o procedimento de atualização. A movimentação de SAN LIFs não é necessária para o cluster ou a integridade do serviço durante a atualização. Os LIFs DE SAN não são movidos a menos que precisem ser mapeados para novas portas. Depois de colocar o node2 on-line, você deve verificar se os LIFs estão saudáveis e localizados nas portas apropriadas.

.Passos
. Retomar a operação de realocação:
+
`system controller replace resume`

+
O sistema executa as seguintes tarefas:

+
--
** Verificação do quorum do cluster
** Verificação da ID do sistema
** Verificação da versão da imagem
** Verificação da plataforma alvo
** Verificação de acessibilidade da rede


--
+
A operação é interrompida nesta fase na verificação de acessibilidade da rede.

. Retomar a operação de realocação:
+
`system controller replace resume`

+
O sistema efetua as seguintes verificações:

+
--
** Verificação de integridade do cluster
** Verificação do status de LIF do cluster


--
+
Depois de executar essas verificações, o sistema relocaliza os agregados não-raiz e LIFs de dados nas de volta para node2, que agora está sendo executado na controladora de substituição.

+
A operação de substituição do controlador é interrompida após a conclusão da realocação de recursos.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
`system controller replace show-details`

+
Se o procedimento de substituição do controlador estiver em pausa, verifique e corrija o erro, se houver, e então o problema `resume` para continuar a operação.

. Se necessário, restaure e reverta quaisquer LIFs deslocados. Liste quaisquer LIFs deslocados:
+
`cluster controller-replacement network displaced-interface show`

+
Se algum LIFs for deslocado, restaure o nó inicial de volta para node2:

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Retome a operação para solicitar ao sistema que execute as verificações posteriores necessárias:
+
`system controller replace resume`

+
O sistema efetua as seguintes verificações posteriores:

+
** Verificação do quorum do cluster
** Verificação de integridade do cluster
** Verificação de reconstrução de agregados
** Verificação do status do agregado
** Verificação do estado do disco
** Verificação do status de LIF do cluster
** Verificação do volume



