---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-nas-lifs-node1-from-node2-to-upgraded-node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Verifique se as LIFs de dados nas node1 no node2 foram relocadas de node2 para node1 ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Migre node1 agregados não-raiz e LIFs de dados nas de node2 para o node1 atualizado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Após verificar a configuração de rede no nó 1, você precisa realocar as LIFs de dados NAS pertencentes ao nó 1 do nó 2 para o nó 1 e confirmar se as LIFs SAN existem no nó 1.

.Sobre esta tarefa
As LIFs remotas gerenciam o tráfego para as LUNs SAN durante o procedimento de atualização. A movimentação de LIFs SAN não é necessária para a integridade do cluster ou do serviço durante a atualização. As interfaces LIF da SAN não são movidas a menos que precisem ser mapeadas para novas portas.

Você verifica se as LIFs estão íntegras e localizadas nas portas corretas depois de colocar o nó 1 online.

.Passos
. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema executa as seguintes tarefas:

+
--
** Verificação do quorum do cluster
** Verificação da ID do sistema
** Verificação da versão da imagem
** Verificação da plataforma alvo
** Verificação de acessibilidade da rede


--
+
O sistema pausa a operação nesta etapa da verificação de acessibilidade da rede.

. Execute uma verificação de acessibilidade da rede:
+
[source, cli]
----
network port reachability show -node node1
----
+
Confirme se todas as portas conetadas, incluindo o grupo de interfaces e as portas VLAN, mostram seu status como `OK`.

. Para as atualizações a seguir, você deve reatribuir os LIFs SAN FCP.
+
[cols="35,65"]
|===
| Sistema existente | Sistema de substituição 


| AFF A250 | AFF A30, AFF A50 


| AFF C250 | AFF C30, AFF C60 


| AFF A800 | AFF A70, AFF A90 


| AFF C800 | AFF C80 
|===
+
Para todas as outras atualizações do sistema, avance para <<resume_relocation_step4,Passo 4>>.

+
.. Reatribua os LIFs de SAN FCP usados para o acesso a dados FCP ou FC-NVMe às portas iniciais corretas:
+
[source, cli]
----
network interface show -vserver <vserver_hosting_fcp_lifs>
----
.. Para LIFs com o nó atual como o node1 atualizado e a porta atual relata "status oper" como "-" (porque a porta existia no nó AFF A800 mas não existe no nó AFF A90), modifique a porta atual antes que ela possa ser colocada on-line.
+
Verifique se a conectividade física está estabelecida com a porta de destino FC onde o FC LIF precisa ser movido:

+
--
... Defina o estado de LIF para "baixo":
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down
----
... Modifique a porta inicial do LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>
----
... Defina o estado de LIF para "up" (para cima):
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up
----


--
+
Repita as subetapas a e b para cada FC SAN LIF que está em casa no node1.



. [[resume_relocation_step4]]Retomar a operação de relocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações:

+
--
** Verificação de integridade do cluster
** Verificação do status de LIF do cluster


--
+
Depois de executar essas verificações, o sistema relocaliza os agregados não-raiz e LIFs de dados nas de propriedade do node1 para o novo node1.

+
A operação de substituição do controlador é interrompida após a conclusão da realocação de recursos.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
[source, cli]
----
system controller replace show-details
----
+
Se o procedimento de substituição do controlador estiver em pausa, verifique e corrija o erro, se houver, e então o problema `resume` para continuar a operação.

. Caso necessário, restaure e reverta as LIFs deslocadas ou migre e modifique manualmente as LIFs do nó 1 que não foram realocadas automaticamente para o nó 1.
+
[role="tabbed-block"]
====
.Restaurar e reverter LIFs deslocados
--
.. Liste quaisquer LIFs deslocados:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Se algum LIFs for deslocado, restaure o nó inicial de volta para node1:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node1_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrar e modificar LIFs manualmente
--
.. Migre os LIFs que não foram realocados automaticamente para o nó 1:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node1_nodename> -destination-port <port_on_node1>
----
.. Modifique o nó inicial e a porta inicial para as LIFs migradas:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node1_nodename> -home-port <home_port>
----


--
====
. Retome a operação para solicitar ao sistema que execute as verificações posteriores necessárias:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações posteriores:

+
** Verificação do quorum do cluster
** Verificação de integridade do cluster
** Verificação de reconstrução de agregados
** Verificação do status do agregado
** Verificação do estado do disco
** Verificação do status de LIF do cluster
** Verificação do volume



