---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/retire-node1.html 
keywords: retiring, node1, node, retire 
summary: Desative o par de HA com node2 e desligue o node1 ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Aposentar-se node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para desativar o node1, você retoma a operação automatizada para desativar o par de HA com o node2 e encerrar o node1 corretamente.

.Passos
. Retomar a operação:
+
`system controller replace resume`

. Verifique se o node1 foi interrompido:
+
`system controller replace show-details`

+
Depois de o node1 ter sido completamente interrompido, o node1 deve estar no prompt Loader>. Para ver o prompt Loader>, conete-se ao console serial do node1.



.O que se segue?
Após desativar o node1, escolha um dos seguintes procedimentos de substituição do controlador com base na sua configuração de upgrade:

* link:replace-node1-affa250-affc250.html["Substitua o módulo do controlador node1 AFF A250 ou AFF C250"]
* link:replace-node1-affa800.html["Substitua o módulo do controlador node1 AFF A800 ou AFF C800"]
* link:replace-node1-affa220-affa200-affc190-fas2620-fas2720.html["Substitua o módulo controlador node1 AFF A220, AFF A200, AFF C190, FAS2620 ou FAS2720"]
* link:replace-node1-aff700-fas900.html["Substitua o controlador node1 AFF A700 ou FAS9000 e os módulos NVRAM"]

