---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/verify-rcf-configuration.html 
keywords: aggregate, relocation, cluster, switch, rcf, shared 
summary: Verifique se o RCF do switch de cluster oferece suporte às portas de cluster/HA compartilhadas para os novos controladores para atualizações de clusters conectados ao switch. 
---
= Verifique a configuração RCF nos switches do cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nesta fase do procedimento de atualização, todos os agregados de dados devem estar no nó 1.  Se estiver atualizando uma configuração com clusters conectados ao switch, você precisará validar se o arquivo de configuração de referência do switch do cluster (RCF) oferece suporte às portas de cluster/HA compartilhadas para os novos controladores.

Se você estiver atualizando para uma configuração de cluster sem switch de dois nós, pode pular esta seção e ir paralink:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Migre agregados que não sejam raiz e LIFs de dados nas de volta para node2"] .

.Passos
. Mudar para o modo de privilégio avançado:
+
`set advanced`

. Verifique o status do "IC RDMA":
+
`ha interconnect status show`

+
Na saída, a "Conexão IC RDMA" deve ter o status `Up` .

+
[cols="50,50"]
|===
| Se o status "Conexão IC RDMA" for ... | Então... 


| `Up` | Vá paralink:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Migre agregados que não sejam raiz e LIFs de dados nas de volta para node2"] . 


| `Down` | Vá para<<verify-rcf-step3,Passo 3>> . 
|===
. [[verify-rcf-step3]]Verifique as portas do cluster e o RCF do switch.
+
Para obter mais informações, link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Conete-se a um cluster conetado a switch"]consulte .

. Verifique se o status "Conexão IC RDMA" mudou para `Up` :
+
`ha interconnect status show`



.O que vem a seguir
link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Migre agregados que não sejam raiz e LIFs de dados nas de volta para node2"]
