---
permalink: upgrade/convert-node2-to-drive-shelf.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Converta o node2 em um shelf de discos e conecte ao node4 antes de reatribuir os discos do node2 para o node4. 
---
= Converter node2 em um compartimento de unidades e conectá-lo ao node4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Converta o node2 do AFF A150, AFF A220 ou FAS2820 em um shelf de discos e conecte-o ao node4 antes de reatribuir os discos do node2 para o node4. Node1 e node2 são os controladores dentro do shelf de discos.

.Passos
. Desligue todos os cabos de rede do node2.
. Remova o node2 do chassi AFF A150, AFF A220 ou FAS2820.
. Insira o módulo IOM12 ou IOM12B no compartimento do nó2.
. Conecte a porta SCSI serial anexada (SAS) do node4 a uma porta disponível no módulo IOM12 ou IOM12B.  Veja olink:https://hwu.netapp.com["Hardware Universe"^] para verificar as portas SAS do seu sistema.
. Crie conexões de cluster temporárias conectando as portas e0a e e0b do node1 a quaisquer duas portas de 25GbE no node4.
+

NOTE: Se o node4 suportar apenas conexões de cluster de 10 GbE, você deverá ter cabeamento de 10 GbE para criar conexões de cluster temporárias.



.O que se segue?
link:reassign-node2-drives.html["Reatribuir unidades de node2 a node4"]
