---
permalink: upgrade/migrate-fas2820-node4-lIfs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: 'Para concluir a atualização, conecte o FAS2820node3 ao node4 e então migre as interfaces lógicas de dados (LIFs) e os agregados de dados do node4 para o node3.' 
---
= Migrar LIFs e agregados de dados do nó FAS2820 node4 para node3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para concluir a atualização, conecte o FAS2820 node3 ao node4 e então migre as interfaces lógicas de dados (LIFs) e os agregados de dados do node4 para o node3.

.Sobre esta tarefa
Execute as seguintes etapas no nó3.

.Passos
. No prompt DO Loader para node3, inicialize o nó no menu de inicialização:
+
[source, cli]
----
boot_ontap menu
----
. Selecione a opção `6 Update flash from backup config` para restaurar o sistema de ficheiros /var para node3.
+
Isso substitui todas as configurações baseadas em flash pelo último backup nos discos.

. Entre `y` para continuar.
. Permita que o nó inicialize normalmente.
+
[NOTE]
====
O nó reinicia automaticamente para carregar a nova cópia do sistema de ficheiros /var.

O nó informa um aviso de que existe uma incompatibilidade de ID do sistema. Introduza `y` para substituir a ID do sistema.

====
. Verifique se as portas do cluster e do HA estão conectadas entre o nó 3 e o nó 4.
. Exibir as portas do cluster e do HA no nó 3 e no nó 4:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
. Modifique o domínio de broadcast do cluster para incluir as portas de cluster desejadas:
+
[source, cli]
----
network port broadcast-domain remove-ports -broadcast-domain <broadcast_domain_name> -ports <port_names>
----
+
[source, cli]
----
network port broadcast-domain add-ports -broadcast-domain Cluster -ports <port_names>
----
+

NOTE: A partir do ONTAP 9.8, novos IPspaces e um ou mais domínios de broadcast podem ser designados para portas físicas existentes destinadas à conetividade de cluster.

. Modifique o IPspace do cluster para incluir as portas do cluster desejadas e defina a unidade máxima de transmissão para 9000 se ainda não estiver definida:
+
[source, cli]
----
network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster
----
. Apresentar todas as LIFs de rede do cluster:
+
[source, cli]
----
network interface show -role cluster
----
. Migre todos os LIFs de rede do cluster em ambos os nós para suas portas iniciais planejadas:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node_name> -destination-port <port_name>
----
. Apresentar todas as LIFs de rede do cluster:
+
[source, cli]
----
network interface show -role cluster
----
. Configure as portas iniciais para os LIFs da rede do cluster:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <port_name>
----
. Migrar todos os LIFs de dados destinados ao node3 de volta para o node3:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node3> -destination-port <port_name>
----
. Apresentar todas as LIFs da rede de dados:
+
[source, cli]
----
network interface show -role data
----
. Configure o nó inicial e a porta inicial para todos os LIFs de dados.  Se algum LIF estiver inativo, defina seu status administrativo como `up` inserindo o seguinte comando uma vez para cada LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -status-admin up
----
. Migração do LIF de gerenciamento de cluster:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node3> -destination-port <port_name>
----
. Exibir o status do LIF de gerenciamento de cluster:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Exibir o status de todos os agregados de dados no cluster:
+
[source, cli]
----
storage aggregate show
----
. Habilite a alta disponibilidade do cluster no cluster de dois nós:
+
[source, cli]
----
cluster ha modify -configured true
----
. Habilitar e verificar failover de armazenamento para node3 e node4:
+
[source, cli]
----
storage failover modify -node <node3> -enabled true
----
+
[source, cli]
----
storage failover modify -node <node4> -enabled true
----
+
[source, cli]
----
storage failover show
----
. Migrar agregados de dados de propriedade do node4 que deveriam ser de propriedade do node3:
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node4> -destination <node3>
----
. Exibir o status de todos os agregados de dados no cluster:
+
[source, cli]
----
storage aggregate show
----
. Ative a reversão automática das LIFs de rede nos nós:
+
[source, cli]
----
network interface modify -lif * -auto-revert true
----
. Habilite a giveback automático de failover de storage:
+
[source, cli]
----
storage failover modify -node * -auto-giveback true
----
. Apresentar o estado do grupo de instrumentos:
+
[source, cli]
----
cluster show
----
. Elegibilidade para failover de exibição:
+
[source, cli]
----
storage failover show
----
+

NOTE: Na saída do relatório do cluster, um nó pode possuir incorretamente agregados que pertencem a outro nó.  Se isso ocorrer, realize uma aquisição e devolução de ambos os lados do cluster.

. Exibir o status de todos os agregados de dados no cluster:
+
[source, cli]
----
storage aggregate show
----

