---
permalink: upgrade/migrate-fas2820-aggregates-epsilon-lifs.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: 'Migre os agregados de dados, epsilon e interfaces lógicas (LIFs) do nó 1 para o nó 4.' 
---
= Migrar agregados de dados, epsilon e LIFs no nó FAS2820 node1 para node4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Migre os agregados de dados, epsilon e interfaces lógicas (LIFs) no nó FAS2820 node1 para node4.

.Sobre esta tarefa
Execute as seguintes etapas no nó4.

.Passos
. No prompt do LOADER para o node4, defina o ID do sistema parceiro:
+
[source, cli]
----
setenv partner-sysid <system_ID_of_node1>
----
. Verifique o ID do sistema do parceiro:
+
[source, cli]
----
printenv partner-sysid
----
. Salve as alterações:
+
[source, cli]
----
saveenv
----
. Inicialize o nó no menu de inicialização:
+
[source, cli]
----
boot_ontap menu
----
. No menu de inicialização, selecione a opção `6 Update flash from backup config` para restaurar o sistema de arquivos /var para node4.
+
Isso substitui todas as configurações baseadas em flash pelo último backup nos discos.

. Entre `y` para continuar.
+
[NOTE]
====
O nó reinicia automaticamente para carregar a nova cópia do sistema de ficheiros /var.

O nó relata um aviso de incompatibilidade de ID do sistema. Introduza `y` para substituir a ID do sistema.

====
. Migrar as LIFs de cluster:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
+
[NOTE]
====
Se as portas do cluster do sistema não forem semelhantes ao atualizar um FAS2820 para um controlador de substituição, talvez seja necessário alterar temporariamente as interfaces no node4 para portas do cluster:

[source, cli]
----
network port modify -node <node4> -port <port_name> -mtu 9000 -ipspace Cluster
----
====
+
[source, cli]
----
network interface migrate -vserver Cluster -lif <cluster_LIF>  -destination-node <node4> -destination-port <port_name>
----
. Aguarde até que o cluster atinja o quorum e verifique se os nós do cluster estão íntegros:
+
[source, cli]
----
– cluster show
----
+

NOTE: O par de HA e o failover de storage permanecem desativados no estado atual.

. Mova os LIFs de cluster para as portas de cluster 25G temporárias no node4:
+
[source, cli]
----
network interface modify -vserver Cluster -lif <cluster_LIF> -home-node <node4> -home-port <port_name>
----
. Conclua esta etapa somente se grupos de interface e VLANs de dados forem usados ​​no cluster FAS2820 que você está atualizando. Caso contrário, vá para<<migrate_node1_nod4,Passo 11>> .
+
Os nomes das portas de rede física no controlador de substituição são diferentes daqueles no FAS2820.  Isso pode levar a VLANs deslocadas e grupos de interface configurados incorretamente no nó 4.

+
.. Mostrar as VLANs deslocadas:
+
[source, cli]
----
cluster controller-replacement network displaced-vlans show
----
.. Restaure as VLANs deslocadas:
+
[source, cli]
----
cluster controller-replacement network displaced-vlans restore
----
.. Corrija os grupos de interface configurados incorretamente.  Os nomes das portas entre o FAS2820 e os controladores que você está atualizando podem ser diferentes.  Atualize os grupos de interface com as portas de membro corretas:
+
[source, cli]
----
ifgrp remove-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----
+
[source, cli]
----
ifgrp add-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----




[[migrate_node1_nod4]]
. Migre os agregados de dados em node1 para node4:
+
[source, cli]
----
storage aggregate relocation start -aggregate-list <aggregate_list_name> -node <node1> -destination <node4> -ndo-controller-upgrade true -override-destination-checks true
----
. Mostrar status de agregação de dados:
+
[source, cli]
----
storage aggregate show
----
. Migre o epsilon removendo-o do nó 1 e movendo-o para o nó 4.
+
.. Remova o epsilon do node1:
+
[source, cli]
----
cluster modify -epsilon false -node <node1>
----
.. Mova o epsilon para node4:
+
[source, cli]
----
cluster modify -epsilon true -node <node4>
----


. Mostrar status do cluster para verificar a alteração do epsilon:
+
[source, cli]
----
cluster show
----
. Apresentar todas as LIFs da rede de dados:
+
[source, cli]
----
network interface show -role data
----
. Migrar todas as LIFs de dados para o node4:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node4> -destination-port <port_name>
----
. Apresentar o estado de todas as LIFs de dados no cluster:
+
[source, cli]
----
network interface show -role data
----
. Se algum LIF estiver inativo, defina seu status administrativo como `up` inserindo o seguinte comando uma vez para cada LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. Migração do LIF de gerenciamento de cluster:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node4> -destination-port <port_name>
----
. Exibir o status do LIF de gerenciamento de cluster:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Paragem node1:
+
[source, cli]
----
halt -node <node1> -inhibit-takeover true -ignore-quorum-warnings true
----


.O que se segue?
link:convert-fas2820-node1-drive-shelf.html["Converter node1 em um compartimento de unidades e conectá-lo ao node3"]
