---
permalink: upgrade/upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html 
sidebar: sidebar 
keywords: complete, procedure, upgrading, upgrade, moving, move, storage, delete, port, lif, re-enable, service, processor, sp, license, autosupport, fc, cna, por, perform final upgrade steps in ontap 9.7 or earlier 
summary: 'Para concluir o procedimento de atualização movendo o storage, você precisa excluir quaisquer portas e LIFs não utilizados dos novos nós, reativar o failover de storage ou alta disponibilidade, configurar o processador de serviço (SP), instalar novas licenças e configurar o AutoSupport. Também pode ser necessário configurar a criptografia de armazenamento ou volume e configurar as portas FC ou CNA.' 
---
= Execute as etapas finais de atualização no ONTAP 9.7 ou anterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para concluir o procedimento de atualização movendo o storage, você deve excluir quaisquer portas e LIFs não utilizados dos novos nós, reativar o failover de storage ou alta disponibilidade, configurar o processador de serviço (SP), instalar novas licenças e configurar o AutoSupport. Também pode ser necessário configurar a criptografia de armazenamento ou volume e configurar as portas FC ou CNA.

.Antes de começar
Estas etapas se aplicam a sistemas que executam o ONTAP 9.7 ou anterior. Se você estiver executando o ONTAP 9.8 ou posterior, use o procedimento em link:upgrade-final-upgrade-steps-in-ontap-9-8.html["Execute as etapas finais de atualização no ONTAP 9.8 ou posterior"].

.Passos
. Se o seu sistema estiver executando o ONTAP 9.8 ou posterior, *STOP*. Tem de utilizar o procedimento em link:upgrade-final-upgrade-steps-in-ontap-9-8.html["Execute as etapas finais de atualização no ONTAP 9.8 ou posterior"].
. No prompt do sistema de armazenamento, exiba informações sobre LIFs:
+
`network interface show`

. Exclua quaisquer portas não utilizadas dos novos nós (nível de privilégio avançado):
+
`network port delete`

. Se você estiver em um ambiente SAN, exclua LIFs não usadas do conjunto de portas para removê-las:
+
.. Apresentar a lista de conjuntos de portas:
+
`lun portset show`

.. Remova quaisquer LIFs não utilizados do conjunto de portas:
+
`lun portset remove`



. Remova cada LIF não utilizado dos novos nós:
+
`network interface delete`

. Reative o failover de storage ou a alta disponibilidade no novo par de nós, conforme necessário:
+
[cols="1,2"]
|===
| Se você tem um... | Então... 


| Cluster de dois nós | Reative a alta disponibilidade:
`cluster ha modify -configured true` 


| Um cluster com mais de dois nós | Reative o failover de armazenamento:
`storage failover modify -node node_name -enabled true` 
|===
. Configure o SP nos novos nós conforme necessário:
+
`system service-processor network modify`

. Instale novas licenças nos novos nós conforme necessário:
+
`system license add`

. Configure o AutoSupport nos novos nós:
+
`system node autosupport modify`

. A partir de cada novo nó, envie uma mensagem de AutoSupport pós-atualização para o suporte técnico:
+
`system node autosupport invoke -node node_name -type all -message "MAINT=END node_name successfully upgraded from platform_old to platform_new"`

. Restaure a funcionalidade de armazenamento ou encriptação de volume utilizando o procedimento adequado no https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Gerencie a criptografia com a CLI"^]conteúdo.
+
Use um dos procedimentos a seguir, dependendo se você estiver usando o gerenciamento de chaves externas ou integradas:

+
** "'restaurar chaves de criptografia integradas de gerenciamento de chaves'"
** "Restaurar chaves de criptografia de gerenciamento de chaves externas"


. Se os novos nós tiverem portas FC (integradas ou em adaptadores FC), portas CNA integradas ou uma placa CNA, configure as portas FC ou CNA inserindo o seguinte comando no prompt do sistema de storage:
+
`system node hardware unified-connect modify -node node-name -adapter adapter-name -mode {fc|cna} -type {target|initiator}`

+
link:https://docs.netapp.com/us-en/ontap/san-admin/index.html["GERENCIAMENTO DE SAN com a CLI"^]

+
Você pode modificar a configuração CNA somente quando os adaptadores CNA estiverem offline.

. Configure um cluster sem switch nos novos nós, se necessário.
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140536["Migração para um cluster comutado de dois nós com switches de cluster Cisco"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140535["Migração para um cluster comutado de dois nós com switches de cluster NetApp CN1610"^]

. Conforme necessário, desative os sistemas originais por meio do site de suporte da NetApp para informar à NetApp que os sistemas não estão mais em operação e podem ser removidos de bancos de dados de suporte:
+
.. Faça login no https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^] site.
.. Clique no link *Meus sistemas instalados*.
.. Na página sistemas instalados, digite o número de série do sistema antigo no formulário e clique em *Go!*
.. Na página do formulário Decommission, preencha o formulário e clique em *Enviar*.




.Depois de terminar
Concluiu o procedimento de atualização.
