---
permalink: upgrade/upgrade-map-network-ports-ontap-9-7-or-earlier.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, configure, setting, intend, data, map, map network ports using ontap 9.7 or earlier 
summary: Para permitir que o node3 e o node4 se comuniquem entre si no cluster e com a rede após a atualização, você deve confirmar se as portas físicas estão corretamente configuradas com as configurações para o uso pretendido, como cluster, dados, etc. 
---
= Mapeie portas de rede usando o ONTAP 9.7 ou anterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para permitir que o node3 e o node4 se comuniquem entre si no cluster e com a rede após a atualização, você deve confirmar se as portas físicas estão corretamente configuradas com as configurações para o uso pretendido, como cluster, dados, etc.

.Antes de começar
Estas etapas se aplicam a sistemas que executam o ONTAP 9.7 ou anterior. Se você estiver executando o ONTAP 9.8 ou posterior, use o procedimento em link:upgrade-map-network-ports-ontap-9-8.html["Mapeie as portas de rede usando o ONTAP 9.8 ou posterior"].

.Sobre esta tarefa
Você deve executar estas etapas em node3 e node4.


NOTE: Os seguintes exemplos de comandos referem-se a "node1" porque, nesta fase do procedimento, os nós de substituição "node3" e "node4" são na realidade denominados "node1" e "node2".

.Passos
. Se o seu sistema estiver executando o ONTAP 9.8 ou posterior, *STOP*. Tem de utilizar o procedimento em link:upgrade-map-network-ports-ontap-9-8.html["Mapeie as portas de rede usando o ONTAP 9.8 ou posterior"].
. Localize as informações de configuração de porta e LIF para node1 e node2 registradas em _prepare for upgrade ao mover o armazenamento_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["Passo 3"].
. Localize as informações de portas, domínios de broadcast e IPspaces que você gravou em _prepare for upgrade ao mover o armazenamento_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["Passo 3"].
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

. Faça as seguintes alterações:
+
.. Inicialize node3 e node4 no prompt do cluster se você ainda não o fez.
.. Adicione as portas corretas ao `Cluster` domínio de broadcast:
+
`network port modify -node _node_name_ -port _port_name_ -mtu 9000 -ipspace Cluster`

+
Este exemplo adiciona `Cluster` a porta e1b em "'node1"":

+
`network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000`

.. Migre os LIFs para as novas portas uma vez para cada LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -source-node node1 -destination-node node1 -destination-port _port_name_`

+
Os LIFs de dados SAN só podem ser migrados quando estiverem offline.

.. Modifique a porta inicial dos LIFs de cluster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Remova as portas antigas do domínio de broadcast de cluster:
+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports _node1:port_`

.. Apresentar o estado de funcionamento de node3 e node4:
+
`cluster show -node _node1_ -fields health`

.. Cada LIF de cluster deve estar escutando na porta 7700. Verifique se as LIFs do cluster estão escutando na porta 7700:
+
`::> network connections listening show -vserver Cluster`

+
A escuta da porta 7700 nas portas do cluster é o resultado esperado, como mostrado no exemplo a seguir para um cluster de dois nós:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. Para cada LIF de cluster que não está escutando na porta 7700, defina o status administrativo do LIF para `down` e depois `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Repita a subetapa (g) para verificar se o LIF do cluster está escutando na porta 7700.



. Modifique a VLAN e `ifgrp config` para corresponder ao novo layout da porta física do controlador.
. Exclua as portas node1 e node2 que não existem mais no node3 e node4 (nível de privilégio avançado):
+
`network port delete -node _node1_ -port _port_name_`

. [[map_97_7]] Ajuste o domínio de broadcast de gerenciamento de nó e migre as LIFs de gerenciamento de nó e gerenciamento de cluster, se necessário:
+
.. Apresentar a porta inicial de um LIF:
+
`network interface show -fields home-node,home-port`

.. Exiba o domínio de broadcast que contém a porta:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Adicione ou remova portas de domínios de broadcast conforme necessário:
+
`network port broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. Modifique a porta inicial de um LIF, se necessário:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ –home-port _port_name_`



. Ajuste os domínios de broadcast entre clusters e migre os LIFs entre clusters, se necessário, usando os comandos no <<map_97_7,Passo 7>>.
. Ajuste quaisquer outros domínios de broadcast e migre os LIFs de dados, se necessário, usando os comandos no <<map_97_7,Passo 7>>.
. Ajuste todos os grupos de failover de LIF:
+
`network interface modify -failover-group _failover_group_ -failover-policy _failover_policy_`

+
O comando a seguir define a política de failover para broadcast-domain-wide e usa as portas no grupo de failover "FG1" como destinos de failover para LIF "data1" em "node1":

+
`network interface modify -vserver node1 -lif data1 -failover-policy broadcast-domain-wide -failover-group fg1`

. Exibir os atributos da porta de rede do node3 e do node4:
+
`network port show -node node1`



.Depois de terminar
Concluiu o mapeamento das portas físicas. Para concluir a atualização, vá para link:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html["Execute as etapas finais de atualização no ONTAP 9.7 ou anterior"].
