---
permalink: upgrade/upgrade_move_delete_recreate_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lif, re-create, move san lifs, create 
summary: Dependendo do conteúdo do cluster e do ambiente de cluster, você precisa mover, excluir ou criar SAN LIFs ou recriar SAN LIFs excluídos. 
---
= Mover, excluir ou criar SAN LIFs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dependendo do conteúdo do cluster e do ambiente de cluster, você deve mover, excluir ou criar SAN LIFs ou recriar SAN LIFs excluídos.



== Considerações para mover SAN LIFs

Você só precisa mover os LIFs SAN se estiver alterando o conteúdo do cluster, por exemplo, adicionando nós ao cluster ou excluindo nós do cluster. Ao mover um LIF, não é necessário recalibrar sua malha FC nem criar novas sessões iSCSI entre os hosts conetados do cluster e a nova interface de destino.

Você pode mover um SAN LIF usando o `network interface modify` comando. Para mover um SAN LIF, você deve colocar o LIF off-line, mover o LIF para um nó ou porta inicial diferente e, em seguida, colocá-lo de volta on-line em seu novo local. O Acesso lógico-Unidade assimétrica (ALUA) fornece caminhos redundantes e seleção automática de caminhos como parte de qualquer solução de SAN ONTAP. Portanto, quando o LIF é colocado off-line para o movimento, não há interrupção de e/S. O host simplesmente tenta novamente e depois move I/o para outro LIF.

Durante os movimentos de LIF, você pode executar as seguintes tarefas sem interrupções:

* Substitua um par de HA de um cluster por um par de HA atualizado de uma forma transparente para os hosts que acessam dados LUN
* Atualize uma placa de interface de destino
* Migre os recursos de uma máquina virtual de storage (SVM) de um conjunto de nós em um cluster para outro conjunto de nós no mesmo cluster
* Quando o servidor host está on-line, é possível mover um LUN SAN para um novo par de HA sem interromper o acesso do servidor host aos dados LUN


Para obter mais informações, consulte o https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["Movimento de SAN LIF"^] procedimento na documentação _SAN storage Management_.



== Excluir SAN LIFs não é mais necessário

Se o cluster estiver em um ambiente SAN, você deverá excluir quaisquer LIFs SAN que você não precisar mais dos nós originais antes de poder desassociar os nós originais do cluster.

.Passos
. Se tiver iniciadores iSCSI, execute as seguintes etapas:
+
.. Exibir uma lista de iniciadores ativos atualmente conetados a um SVM nos nós originais, uma vez para cada um dos LIFs antigos
`iscsi connection show -vserver _Vserver_name_ -lif _old_lif_`
+
O exemplo a seguir mostra a saída do comando com um iniciador ativo conetado ao SVM VS1:

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. Se algum iniciador ainda estiver conetado a um nó original, faça logout das sessões do computador host.


. Exiba a lista de conjuntos de portas para determinar se quaisquer LIFs iSCSI ou FC nos nós originais pertencem a um conjunto de portas:
+
`lun portset show`

+
O exemplo a seguir mostra a saída `lun portset show` do comando:

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. Se algum iSCSIs ou FC LIFs em um nó original forem membros de um conjunto de portas, remova-os do conjunto de portas:
+
`lun portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _lif_name_`

. Exclua os LIFs nos nós originais:
+
`network interface delete -vserver _vserver_name_ -lif _lif_name_`





== Crie novos LIFs SAN ou crie novamente LIFs SAN excluídos

Dependendo dos requisitos do ambiente do cluster, você pode decidir criar novas LIFs SAN ou recriar LIFs SAN que você excluiu anteriormente neste procedimento. Você pode criar ou recriar LIFs de SAN usando o procedimento na documentação _Gerenciamento de cluster usando o https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_network_interfaces.html["criação de interfaces de rede"^] Gerenciador de sistema do OnCommand_.
