---
permalink: upgrade/upgrade-remove-disk-ownership-new-nodes.html 
sidebar: sidebar 
keywords: node, internal, disk, add-on, shelves, attach, system, interfere, controller, upgrade, remove, ownership, node3, node4, node, remove ownership of disks attached to the new nodes 
summary: Se os novos nós tiverem discos internos ou gavetas complementares conectados ao sistema, isso poderá interferir na atualização da controladora. Siga as etapas a seguir para remover a propriedade de quaisquer novos discos fornecidos com o node3/node4. 
---
= Remova a propriedade dos discos conectados aos novos nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se os novos nós tiverem discos internos ou gavetas complementares conectados ao sistema, isso poderá interferir na atualização da controladora. Siga as etapas a seguir para remover a propriedade de quaisquer novos discos fornecidos com o node3/node4.

.Sobre esta tarefa
Estas etapas são executadas em node3 e node4 uma após a outra. A sequência do nó não importa.

[NOTE]
====
* As prateleiras de node1 e node2 não estão fisicamente conetadas a node3 e node4 nesta fase.
* Você só precisa remover a propriedade de disco para discos e gavetas que acompanham novas controladoras.
* Não é necessário remover a propriedade dos discos se você estiver atualizando o hardware trocando um controlador antigo por um novo controlador em uma plataforma de unidade interna, mantendo o chassi e os discos da controladora antiga.
+
Por exemplo, se você estiver atualizando seu sistema de um AFF A200 para um AFF A220 trocando apenas o antigo módulo de controlador AFF A200 pelo novo módulo de controlador AFF A220 enquanto mantém o chassi e os discos do AFF A200 antigo no lugar, você não removeria a propriedade dos discos para o novo módulo de controladora AFF A220, conforme descrito nesta seção _Remoção de propriedade dos discos anexados aos novos nós_.

+
Entre em Contato com o suporte técnico da NetApp se tiver dúvidas sobre como remover a propriedade do disco durante uma atualização da controladora.

+
Veja a seguir uma lista de sistemas que têm storage interno: FAS2620, FAS2650, FAS2720, FAS2750, AFF A200, AFF A220, AFF A700s, AFF A800, AFF A250.

+
Se o seu sistema não estiver listado acima, consulte https://hwu.netapp.com["NetApp Hardware Universe"^] para verificar se tem unidades internas.



====
.Passos
. No prompt Loader do nó, digite o comando:
+
`boot_ontap menu`

. No prompt do menu de inicialização, digite `9a` e pressione Enter.
+
A tela a seguir mostra o prompt do menu de inicialização.

+
[listing]
----
Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  9a
----
. Remova a propriedade do disco inserindo `y` quando você vir um prompt semelhante ao seguinte:
+
[listing]
----

########## WARNING ##########

This is a disruptive operation and will result in the
    loss of all filesystem data. Before proceeding further,
    make sure that:
    1) This option (9a) has been executed or will be executed
    on the HA partner node, prior to reinitializing either
    system in the HA-pair.
    2) The HA partner node is currently in a halted state or
    at the LOADER prompt.


    Do you still want to continue (yes/no)? yes
----
+
O sistema remove a propriedade do disco e retorna ao menu de inicialização.

. No menu de inicialização, entre `5` para ir para o modo de manutenção.
. No modo de manutenção, execute o `disk show` comando.
+
Nenhum disco deve ser listado.

. Execute o comando: "
+
`disk show -a`

+
Todos os discos listados devem ser não atribuídos.

. Sair do modo de manutenção:
+
`halt`


