---
permalink: upgrade/upgrade-optional-move-internal-storage.html 
sidebar: sidebar 
keywords: node, support, model, internal, sata, drive, ssd, moving, move, upgrading, upgrade, convert, move internal storage or convert the system to a drive shelf 
summary: Se o nó original for um dos modelos suportados, você terá a opção de mover suas unidades SATA internas, SSDs ou unidades SAS para um compartimento de unidades anexado aos novos nós durante o processo de atualização movendo o armazenamento. Você também pode converter o sistema em um compartimento de unidades e anexá-lo aos novos nós. 
---
= Visão geral
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o nó original for um dos modelos suportados, você terá a opção de mover suas unidades SATA internas, SSDs ou unidades SAS para um compartimento de unidades anexado aos novos nós durante o processo de atualização movendo o armazenamento. Você também pode converter o sistema em um compartimento de unidades e anexá-lo aos novos nós.

.Sobre esta tarefa
Você pode mover unidades ou compartimentos de unidades apenas no mesmo cluster.

.Opções
* link:upgrade-move-internal-drives.html["Mova unidades internas de um nó original"]
+
Se o nó original for um dos modelos suportados, durante o processo de atualização movendo o armazenamento, você poderá mover as unidades SATA internas, SSDs ou unidades SAS do nó para um compartimento de unidades anexado ao novo nó no mesmo cluster.

* link:upgrade-convert-node-to-shelf.html["Converta um nó original em um compartimento de unidades"]
+
Se o nó original for um dos modelos com suporte, durante o processo de atualização movendo o storage, você poderá converter o nó em um compartimento de unidades e anexá-lo aos novos nós no mesmo cluster.


