---
permalink: upgrade/upgrade-remove-original-nodes.html 
sidebar: sidebar 
keywords: volume, move, node, remove, original, cluster, configuration, disk, initialize, remove the original nodes from the cluster 
summary: Após os volumes serem movidos para os novos nós, você remove os nós originais do cluster. Ao remover um nó, a configuração desse nó é apagada e todos os discos são inicializados. 
---
= Remova os nós originais do cluster.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após mover os volumes dos nós originais para os novos nós e mover ou excluir as LIFs de dados, você remove os nós originais do cluster. Ao remover um nó, a configuração desse nó é apagada e todos os discos são inicializados.

.Passos
. [[disable-ha]]Desativar a configuração de alta disponibilidade (HA) nos nós originais:
+
[source, cli]
----
storage failover modify -node <original_node_name> -enabled false
----


. Altere o nível de privilégio para avançado:
+
[source, cli]
----
set -privilege advanced
----
. Identifique o nó no cluster que possui epsilon:
+
[source, cli]
----
cluster show
----
+
No exemplo a seguir, "node0" atualmente contém epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Se o nó que você está removendo contém epsilon:
+
.. Mova o epsilon do nó que você está removendo:
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. Mova epsilon para um nó que você não está removendo:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Identifique o nó mestre atual:
+
[source, cli]
----
cluster ring show
----
+
O nó mestre é o nó que hospeda processos como... `mgmt`, `vldb`, `vifmgr`, `bcomd`, e `crs`.

. Se o nó que você está removendo for o nó mestre atual, habilite outro nó no cluster para ser eleito como o nó mestre:
+
.. Torne o nó mestre atual inelegível para participar do cluster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
O nó é marcado como não íntegro até que a elegibilidade seja restaurada. Quando o nó mestre se torna inelegível, um dos nós restantes é eleito pelo quórum do cluster como o novo mestre.

+
[NOTE]
====
Se você estiver executando esta etapa no primeiro nó de um par de HA, você deve marcar apenas esse nó como inelegível. Não modifique o status do parceiro de HA.

Se o nó parceiro for selecionado como o novo mestre, você precisa verificar se ele detém epsilon antes de torná-lo inelegível. Se o nó parceiro detiver epsilon, você precisa mover epsilon para outro nó que permaneça no cluster antes de torná-lo inelegível. Você faz isso ao repetir estas etapas para remover o nó parceiro.

====
.. Torne o nó mestre anterior elegível para participar do cluster novamente:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Faça login na LIF de gerenciamento de nó remoto ou na LIF de gerenciamento de cluster em um nó que você não está removendo do cluster.
. Remova os nós do cluster:
+
|===
| Para esta versão do ONTAP... | Use este comando... 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9.4 e versões posteriores
 a| 
Com o nome do nó:

[source, cli]
----
cluster remove-node -node <node_name>
----
Com o endereço IP do nó:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Se você tiver um cluster com versões mistas e estiver removendo o último nó com versão inferior, use o `-skip-last-low-version-node-check` parâmetro com esses comandos.

+
O sistema informa o seguinte:

+
** Você também deve remover o parceiro de failover do nó do cluster.
** Após o nó ser removido e antes que ele possa se juntar novamente a um cluster, você deve usar a opção de menu de inicialização *(4) Limpar configuração e inicializar todos os discos* ou a opção *(9) Configurar particionamento avançado de unidade* para apagar a configuração do nó e inicializar todos os discos.
+
Uma mensagem de falha é gerada se houver condições que você precise resolver antes de remover o nó. Por exemplo, a mensagem pode indicar que o nó possui recursos compartilhados que você deve remover ou que o nó está em uma configuração de alta disponibilidade (HA) de cluster ou em uma configuração de failover de armazenamento que você deve desativar.

+
Se o nó for o mestre de quorum, o cluster perderá brevemente o quorum e depois o restabelecerá. Essa perda de quorum é temporária e não afeta nenhuma operação de dados.



. Se uma mensagem de falha indicar condições de erro, corrija essas condições e execute o programa novamente. `cluster remove-node` ou `cluster unjoin` comando.
+
O nó reinicia automaticamente após ser removido com sucesso do cluster.

. Se você estiver reutilizando o nó, apague a configuração do nó e inicialize todos os discos:
+
.. Durante o processo de inicialização, pressione Ctrl+C para exibir o menu de inicialização quando solicitado.
.. Selecione a opção do menu de inicialização *(4) Limpar configuração e inicializar todos os discos*.


. [[return-admin]]Retornar ao nível de privilégio de admin:
+
[source, cli]
----
set -privilege admin
----


. Repita os passos <<disable-ha,1>> para <<return-admin,10>> Para remover o parceiro de failover do cluster.
. Se o cluster tiver apenas dois nós restantes, configure a alta disponibilidade para o cluster de dois nós:
+
[source, cli]
----
cluster ha modify -configured true
----


.O que se segue?
link:upgrade-complete-move-volumes.html["Concluir a atualização dos volumes de movimentação"]
