---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: Você deve reatribuir os discos que pertenciam a node1 e node2 a node3 e node4, respetivamente. 
---
= Conecte as gavetas de storage e reatribua a propriedade do disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve reatribuir os discos que pertenciam a node1 e node2 a node3 e node4, respetivamente.

.Sobre esta tarefa
Você executa as etapas desta seção no node3 e no node4. Conclua cada etapa no node3 e depois no node4 antes de passar para a próxima etapa.

[[reassign-spare-disks-step1]]
.Passos
. Conecte os cabos das prateleiras de armazenamento que estavam previamente conectadas:
+
** Conecte os cabos do nó 1 ao nó 3
** Conecte os cabos do nó 2 ao nó 4.
+

CAUTION: Não conecte novas shelves ao node3 ou node4 durante este procedimento de atualização. Você pode conectar novas shelves ao sistema sem interrupções após concluir a atualização do controlador.



. Verifique a fonte de alimentação e a conectividade física das gavetas.
. A partir do prompt do node3 Loader, inicialize para o modo de manutenção:
+
`boot_ontap maint`

. Apresentar a ID do sistema de node3:
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
Anote o ID do sistema do node3 para uso em <<reassign-disks-and-aggregates,Passo 5>>.



[[reassign-disks-and-aggregates]]
. Reatribua os discos e os agregados de dados:
+
[role="tabbed-block"]
====
.Reatribuir ao node3
--
Reatribua os discos sobressalentes do node1, os discos pertencentes ao agregado de raiz e quaisquer agregados de dados ao node3:

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** O parâmetro  `node1_sysid` é o valor que você registrou em _Desligando os nós originais_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Passo 5"].
** Especifique o parâmetro  `-p <node2_sysid>` somente quando houver discos compartilhados.


--
.Reatribuir ao node4
--
Reatribua os discos sobressalentes do node2, os discos pertencentes ao agregado de raiz e quaisquer agregados de dados ao node4:

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** O parâmetro  `node2_sysid` é o valor que você registrou em _Desligando os nós originais_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Passo 5"].
** Especifique o parâmetro  `-p <node3_sysid>` somente quando houver discos compartilhados.


--
====
+
O sistema exibe uma mensagem semelhante à seguinte:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Entre `y` para continuar.
+
O sistema exibe uma mensagem semelhante à seguinte:

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. Entre `y` para continuar.
. Confirme se o agregado raiz do node1 está definido como `root` no campo de opções e se outros agregados estão online:
+
`aggr status`

+
Você deve ver saída semelhante ao seguinte:

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]Saia do modo de manutenção:
+
`halt`

. Repita <<reassign-spare-disks-step1,Passo 1>> para <<reassign-spare-disks-step9,Passo 9>> no nó 4.


.O que se segue?
Após conectar as gavetas de armazenamento e reatribuir a propriedade dos discos, link:upgrade-restore-root-volume-config.html["restaurar a configuração do volume raiz"].
