---
permalink: upgrade/upgrade-complete-move-volumes.html 
sidebar: sidebar 
keywords: complete, procedure, upgrading, upgrade, move, moving, volume, configure, service, processor, sp, license, autosupport, storage, encryption, fc, nca, port, complete the upgrade 
summary: 'Para concluir o procedimento de atualização movendo volumes, você precisa configurar o processador de serviço (SP), instalar novas licenças e configurar o AutoSupport. Também pode ser necessário configurar a criptografia de armazenamento ou volume e configurar as portas FC ou NCA.' 
---
= Concluir a atualização dos volumes de movimentação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para concluir o procedimento de atualização movendo volumes, você deve configurar o processador de serviço (SP), instalar novas licenças e configurar o AutoSupport. Também pode ser necessário configurar a criptografia de armazenamento ou volume e configurar as portas FC ou NCA.

. Configure o SP nos novos nós conforme necessário:
+
`system service-processor network modify`

. Instale novas licenças nos novos nós conforme necessário:
+
`system license add`

. Configure o AutoSupport nos novos nós:
+
`system node autosupport modify`

. A partir de cada novo nó, envie uma mensagem de AutoSupport pós-atualização para o suporte técnico:
+
`system node autosupport invoke -node node_name -type all -message "node_name successfully upgraded from platform_old to platform_new"`

. Restaure a funcionalidade de armazenamento ou criptografia de volume usando um dos procedimentos a seguir, dependendo se você estiver usando o gerenciamento de chaves interno ou externo:
+
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaurar chaves de criptografia integradas de gerenciamento de chaves"^]
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaurar chaves de criptografia de gerenciamento de chaves externas"^]


. Se os novos nós tiverem portas FC (integradas ou em adaptadores FC), portas CNA integradas ou uma placa CNA, configure as portas FC ou CNA inserindo o seguinte comando no prompt do sistema de armazenamento:
+
`system node hardware unified-connect modify -node node-name -adapter adapter-name -mode {fc|cna} -type {target|initiator}`

+
link:https://docs.netapp.com/us-en/ontap/san-admin/index.html["GERENCIAMENTO DE SAN com a CLI"^]

+
Você pode modificar a configuração CNA somente quando os adaptadores CNA estiverem offline.

. Configure um cluster sem switch nos novos nós, se necessário.
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140536["Migração para um cluster comutado de dois nós com switches de cluster Cisco"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140535["Migração para um cluster comutado de dois nós com switches de cluster NetApp CN1610"^]

. Conforme necessário, desative os sistemas originais por meio do site de suporte da NetApp para informar à NetApp que os sistemas não estão mais em operação e podem ser removidos de bancos de dados de suporte:
+
.. Faça login no https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^] site.
.. Clique no link *Meus sistemas instalados*.
.. Na página *Installed Systems*, insira o número de série do sistema antigo no formulário e clique em *Go!*
.. Na página do formulário Decommission, preencha o formulário e clique em *Enviar*.



