---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configure e gerencie a criptografia de armazenamento, gerencie chaves de autenticação e silencie as relações SnapMirror ao atualizar controladores executando o ONTAP 9.15,1 ou posterior usando `system controller replace` o comando.' 
---
= Conclua a preparação para a atualização
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre licenciamento ONTAP e gerenciamento de criptografia de armazenamento usando o Onboard Key Manager (OKM). Opcionalmente, suspenda os relacionamentos SnapMirror.



== Saiba mais sobre o licenciamento ONTAP

Para obter informações detalhadas sobre o licenciamento do ONTAP, https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gerenciamento de licenças"^] consulte .


NOTE: O uso de recursos não licenciados no controlador pode colocá-lo fora de conformidade com seu contrato de licença.



== Gerencie a criptografia de armazenamento usando o Gerenciador de chaves integrado

Utilize o Gerenciador de Chaves Integrado (OKM) para gerenciar as chaves de criptografia. Se o OKM estiver configurado, você deve anotar a senha e o material de backup antes de iniciar a atualização.

.Passos
. Grave a frase-passe de todo o cluster.
+
Esta é a senha que foi inserida quando o OKM foi configurado ou atualizado usando a CLI ou API REST.

. Verifique a senha e a operação do key-manager:
+
`security key-manager onboard sync`

+
Quando solicitado, insira a senha OKM de todo o cluster que você registrou na etapa anterior.

. Verifique se cc-mode está ativado consultando a saída do seguinte comando:
+
`security key-manager config show`

. Faça backup das informações do key-manager:
+
`security key-manager onboard show-backup`





== Opcionalmente, suspenda os SnapMirror relacionamentos

Antes de continuar com o procedimento, você deve confirmar que todas as relações do SnapMirror são silenciadas. Quando um relacionamento do SnapMirror é interrompido, ele permanece quieto em reinicializações e failovers.

.Passos
. Verifique o status da relação do SnapMirror no cluster de destino:
+
`snapmirror show`

+
[NOTE]
====
Se o status for "transferência", você deve cancelar essas transferências:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
A interrupção falha se a relação SnapMirror não estiver no estado "transferindo".

. Quiesce todas as relações entre o cluster:
+
`snapmirror quiesce -destination-vserver *`



.O que se segue?
Após a preparação para a atualização, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Realocar agregados não raiz e LIFs de dados NAS pertencentes ao node1 para o node2"].
