---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Entenda se você pode atualizar controladores executando o ONTAP 9.15,1 ou posterior usando `system controller replace` comandos.' 
---
= Diretrizes para atualização de controladores com ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para entender se você pode usar o ARL para atualizar um par de controladores executando o ONTAP 9.15,1 ou posterior depende da plataforma e da configuração dos controladores original e de substituição.



== Atualizações suportadas para ARL

Antes de atualizar um par de nós usando este procedimento ARL, revise os seguintes requisitos para garantir que sua configuração seja compatível:

* Verifique se o ARL pode ser executado nos controladores originais e de substituição.
* Verifique o tamanho de todos os agregados definidos e o número de discos suportados pelo sistema original. Em seguida, você compara os tamanhos de agregados e o número de discos suportados com o tamanho de agregado e o número de discos suportados pelo novo sistema. Consulte a link:other_references.html["Referências"]ligação para o _Hardware Universe_ onde esta informação está disponível. O tamanho agregado e o número de discos suportados pelo novo sistema devem ser iguais ou superiores ao tamanho agregado e ao número de discos suportados pelo sistema original.
* Valide nas regras de mistura de cluster se novos nós podem se tornar parte do cluster com os nós existentes quando o controlador original for substituído. Para obter mais informações sobre as regras de mistura de cluster, consulte o link:other_references.html["Referências"]link para o _Hardware Universe_.
* Migre e reorganize as LIFs de cluster para duas portas de cluster por nó se você tiver um sistema, como um AFF 700, com a seguinte configuração:
* Mais de duas portas de cluster por nó
* Uma placa de interconexão de cluster em SLOT4 no modo de breakout para criar as portas e4a, e4b, e4c e e4d e as portas e4e, e4f, e4g e e4h
+

NOTE: Executar uma atualização de controladora com mais de duas portas de cluster por nó pode resultar em LIFs de cluster ausentes na nova controladora após a atualização.

+
Para obter mais informações, consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["Como eliminar LIFs de cluster indesejadas ou desnecessárias"^].



A atualização do controlador usando ARL é suportada em sistemas configurados com volumes SnapLock Enterprise e SnapLock Compliance.



== Clusters sem switch de dois nós

Se você estiver atualizando nós em um cluster sem switch de dois nós, poderá deixar os nós no cluster sem switch durante a atualização. Você não precisa convertê-los em um cluster comutado.



== Atualizações não suportadas para ARL

Não é possível atualizar os controladores de substituição que não sejam compatíveis com as gavetas de disco conectadas às controladoras originais.

link:other_references.html["Referências"]Consulte o link para o _Hardware Universe_ para obter informações de suporte a disco.

Se você quiser atualizar controladores de nível de entrada com unidades internas, link:other_references.html["Referências"]consulte o link para _Atualizar movendo volumes ou armazenamento_ e vá para o procedimento _Atualizar um par de nós executando Data ONTAP em cluster movendo volumes_.



== Solucionar problemas

Se ocorrerem problemas durante a atualização dos controladores, consulte link:troubleshoot_index.html["Solucionar problemas"] para obter mais informações e possíveis soluções.

Se você não encontrar uma solução para o problema que encontrou, entre em Contato com o suporte técnico.
