---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 'Você pode atualizar o hardware da controladora executando o ONTAP 9.15,1 ou posterior usando `system controller replace` comandos, relocando a propriedade de agregados que não sejam raiz.' 
---
= Saiba mais sobre este procedimento de atualização do ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existem vários métodos de realocação agregada (ARL) para atualizar o hardware do controlador. Este procedimento de ARL descreve como atualizar um par de controladores HA em sistemas de armazenamento AFF e FAS introduzidos no ONTAP 9.15.1 ou posterior com novos controladores, mantendo os dados e discos existentes.


NOTE: Não é possível usar este procedimento para atualizar uma configuração MetroCluster FC ou IP. Para atualizar uma configuração do MetroCluster, link:other_references.html["Referências"] consulte para vincular à documentação de atualização e expansão _MetroCluster_.

Durante o procedimento, você atualiza o hardware da controladora original com o hardware da controladora de substituição, relocando a propriedade de agregados que não sejam raiz. Migre agregados várias vezes de nó para nó para confirmar se pelo menos um nó está fornecendo dados dos agregados durante o procedimento de atualização. Você também migra interfaces lógicas de dados (LIFs) e atribui as portas de rede do novo controlador aos grupos de interface à medida que avança.

.Terminologia utilizada nesta informação
Nesta informação, os nós originais são chamados "node1" e "node2", e os novos nós são chamados "node3" e "node4". Durante o procedimento descrito, o node1 é substituído pelo node3 e o node2 é substituído pelo node4.

Os termos "node1", "node2", "node3" e "node4" são usados apenas para distinguir entre os nós originais e novos. Ao seguir o procedimento, você deve substituir os nomes reais de seus nós originais e novos. No entanto, na realidade, os nomes dos nós não mudam: node3 tem o nome node1 e node4 tem o nome node2 após o hardware do controlador ser atualizado.

.Informações importantes:
* Este procedimento é complexo e assume que você tem habilidades avançadas de administração do ONTAP. Você também deve ler e compreender o link:guidelines_for_upgrading_controllers_with_arl.html["diretrizes para atualização de controladores com ARL"] e o link:overview_of_the_arl_upgrade.html["Sequência de atualização do ARL"] antes de iniciar a atualização.
* Este procedimento pressupõe que o hardware do controlador de substituição é novo e não foi utilizado. Os passos necessários para preparar controladores usados com o `wipeconfig` comando não estão incluídos neste procedimento. Você deve entrar em Contato com o suporte técnico se o hardware do controlador de substituição tiver sido usado anteriormente.
* Use este procedimento para atualizar o hardware da controladora em clusters com mais de dois nós. No entanto, é necessário executar o procedimento separadamente para cada par de alta disponibilidade (HA) no cluster.
* Ao atualizar para um sistema introduzido no ONTAP 9.15.1 ou posterior, o ONTAP converte a eficiência de storage de volumes existentes e aplica os novos recursos de eficiência de storage que utilizam a funcionalidade de descarga de hardware. Este é um processo de fundo automático, sem impactos visível no desempenho do sistema.
+
** Para os sistemas AFF A20, AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60 e AFF C80, o ONTAP converte a eficiência de storage de todos os volumes thin Provisioning existentes, incluindo aqueles que não usam a eficiência de storage.
** Para um sistema FAS70 e FAS90, o ONTAP converte apenas a eficiência de storage de volumes thin Provisioning existentes que tinham a eficiência de storage habilitada antes da atualização.


+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Saiba mais sobre a eficiência de storage"^].

* Os sistemas AFF A20, AFF A50, AFF A70, AFF A90, AFF A1K, FAS70 e FAS90 compartilham 100GbE portas de rede para conexões de cluster e HA. Esses sistemas podem oferecer suporte a conexões de cluster 10GbE ou 25GbE a switches de cluster legados. No entanto, a NetApp recomenda a atualização para velocidades de cluster 100GbE quando os switches 10GbE e 25GbE não forem mais necessários. Para obter mais informações, consulte os seguintes artigos da base de dados de Conhecimento:
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Como configurar portas de cluster 10G ou 25G em uma nova configuração de cluster"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Como converter portas de cluster 10G ou 25G existentes para portas de cluster 40G ou 100g"^]


--
+
O sistema AFF A20 compartilha portas de rede 10GbE e 25GbE para conexões de cluster e HA. Estas são as únicas conexões de cluster de portas de rede suportadas por um sistema AFF A20.

+
Se não for possível vincular portas de cluster e0a ou e0b no nó existente às portas de cluster no novo nó, link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bugs Online ID de erro CONTAP-166978"^]consulte .


