---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'Verifique se LIFs de dados nas do node2 que estão no node3 são relocados de node3 para node4 ao atualizar controladores executando o ONTAP 9.15,1 ou posterior usando `system controller replace` comandos.' 
---
= Migre agregados que não sejam raiz e LIFs de dados nas pertencentes ao node2 de node3 para node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depois de verificar a configuração de rede no node4 e antes de realocar agregados de node3 para node4, você deve verificar se os LIFs de dados nas pertencentes ao node2 que estão atualmente no node3 são relocados de node3 para node4. Você também deve verificar se as SAN LIFs existem no node4.

.Sobre esta tarefa
Os LIFs remotos manipulam o tráfego para LUNs SAN durante o procedimento de atualização. A movimentação de SAN LIFs não é necessária para o cluster ou a integridade do serviço durante a atualização. Os LIFs DE SAN não são movidos a menos que precisem ser mapeados para novas portas. Você irá verificar se os LIFs estão saudáveis e localizados em portas apropriadas depois de colocar o node4 on-line.

.Passos
. Os iSCSI LIFs encontram automaticamente as portas iniciais corretas usando a digitalização de acessibilidade. Os LIFs FC e NVMe/FC SAN não são movidos automaticamente. Eles continuam a mostrar a porta de casa em que estavam antes de atualizar.
+
Verifique os LIFs SAN em node4:

+
.. Modifique quaisquer LIFs SAN iSCSI que relatem um status de operação "inativo" para as novas portas de dados:
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif> admin down
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif> port <new_port> node <node>
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif>
----
.. Modifique quaisquer LIFs FC e NVMe/FC SAN que estejam em casa da nova controladora e relatando um status operacional "inativo" para as portas FCP na nova controladora:
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif> admin down
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif> port <new_port> node <node>
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif>
----


. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema executa as seguintes tarefas:

+
** Verificação do quorum do cluster
** Verificação da ID do sistema
** Verificação da versão da imagem
** Verificação da plataforma alvo
** Verificação de acessibilidade da rede


+
A operação é interrompida nesta fase na verificação de acessibilidade da rede.

. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações:

+
** Verificação de integridade do cluster
** Verificação do status de LIF do cluster


+
Depois de executar essas verificações, o sistema relocaliza os agregados não-raiz e LIFs de dados nas de propriedade do node2 para a nova controladora, node4. A operação de substituição do controlador é interrompida após a conclusão da realocação de recursos.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
[source, cli]
----
system controller replace show-details
----
+
Se o procedimento de substituição do controlador estiver em pausa, verifique e corrija o erro, se houver, e então o problema `resume` para continuar a operação.

. Caso necessário, restaure e reverta as LIFs deslocadas ou migre e modifique manualmente as LIFs do nó 2 que não foram realocadas automaticamente para o nó 4.
+
[role="tabbed-block"]
====
.Restaurar e reverter LIFs deslocados
--
.. Liste quaisquer LIFs deslocados:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Se algum LIFs for deslocado, restaure o nó inicial de volta para node4:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrar e modificar LIFs manualmente
--
.. Migre os LIFs que não foram realocados automaticamente para o nó 4:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. Modifique o nó inicial e a porta inicial para as LIFs migradas:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. Retome a operação para solicitar ao sistema que execute as verificações posteriores necessárias:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações posteriores:

+
** Verificação do quorum do cluster
** Verificação de integridade do cluster
** Verificação de reconstrução de agregados
** Verificação do status do agregado
** Verificação do estado do disco
** Verificação do status de LIF do cluster
** Verificação do volume



