---
sidebar: sidebar 
permalink: upgrade-arl-auto/check_metrocluster_config_errors.html 
keywords: Config Advisor, configuration, errors, validation, health, Active IQ 
summary: 'Use a ferramenta Config Advisor para verificar se há erros de configuração comuns ao atualizar controladores executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Verifique se há erros de configuração do MetroCluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar a ferramenta Active IQ Config Advisor disponível no site de suporte da NetApp para verificar se há erros de configuração comuns.

Se não tiver uma configuração do MetroCluster, pode ignorar esta secção.

.Sobre esta tarefa
O Active IQ Config Advisor é uma ferramenta de validação de configuração e verificação de integridade. Você pode implantá-lo em sites seguros e sites não seguros para coleta de dados e análise do sistema.


NOTE: O suporte para Config Advisor é limitado e está disponível apenas online.

. Faça o download link:https://mysupport.netapp.com/site/tools["Active IQ Config Advisor"]da ferramenta.
. Execute o Active IQ Config Advisor, revisando a saída e seguindo suas recomendações para resolver quaisquer problemas.

