---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: 'Decida se deseja usar o ARL para atualizar controladores executando o ONTAP 9.5 a 9,7 usando `system controller replace` comandos.' 
---
= Decida se deve usar este procedimento de realocação agregada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existem vários métodos de realocação agregada (ARL) para atualizar o hardware do controlador. Este procedimento descreve como atualizar o hardware do controlador usando ARL com "comandos de substituição do controlador do sistema" em sistemas que executam o ONTAP 9.7, 9.6 ou 9.5. Você só deve usar este procedimento complexo se for um administrador ONTAP experiente.

Para ajudar você a decidir se este procedimento ARL é adequado para a atualização de hardware do seu controlador, você deve revisar todas as seguintes circunstâncias para atualizações suportadas:

* Você está atualizando os controladores NetApp que executam o ONTAP 9.5, 9,6 ou 9,7. Este documento não se aplica a atualizações para o ONTAP 9.8.
* Você não quer adicionar os novos controladores como um novo par de HA ao cluster e migrar os dados usando as movimentações de volume.
* Tem experiência na administração de ONTAP e está confortável com os riscos de trabalhar no modo de privilégio de diagnóstico.
* Sua combinação de atualização de hardware está listada em <<sys_commands_95_97_supported_systems,matriz de modelo suportada>> .
* Se você estiver atualizando uma configuração do MetroCluster, ela será uma configuração de FC de 4 nós ou superior e todos os nós executarão o ONTAP 9.6 ou 9,7.


[NOTE]
====
* Se você estiver atualizando um sistema trocando módulos de controlador no mesmo chassi, como AFF A800 ou AFF C800, a NetApp recomenda fortemente usar o procedimento de atualização quelink:../upgrade-arl-auto-in-chassis/index.html["atualiza modelos de controlador usando ARL, mantendo o chassi e os discos do sistema existentes"] .  Este procedimento ARL inclui as etapas que garantem que os discos internos permaneçam seguros no chassi quando você remove e instala os controladores durante o procedimento de atualização.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Aprenda sobre as combinações de atualização de sistema suportadas usando ARL, mantendo o chassi e os discos do sistema existentes"].

* Você pode usar criptografia de storage NetApp (NSE), criptografia de volume NetApp (NVE) e criptografia de agregado NetApp (NAE) com este procedimento.


====


== Combinações de atualização de sistema suportadas

As tabelas a seguir mostram a matriz de modelos suportada para a atualização do controlador usando este procedimento ARL.

[cols="50,50"]
|===
| Controlador antigo | Controlador de substituição 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700 1, AFF A800 2 


| FAS8200 | FAS8700,FAS9000,FAS8300 4,5 


| AFF A300 | AFF A700, AFF A800, AFF A400 4, 2, 3, 1, 5, 
|===

NOTE: Se a combinação do modelo de atualização da controladora não estiver na tabela acima, entre em Contato com o suporte técnico.

1 a atualização automática ARL para o sistema AFF A700 é suportada a partir do ONTAP 9.7P2.

^2^Se você estiver atualizando para um AFF A800 ou um sistema que suporte discos internos e externos, você deve seguir as instruções específicas para o agregado raiz em discos NVMe internos.  Consultelink:reassign-node1-disks-to-node3.html#auto_check3_step9["Reatribuir discos node1 a node3, passo 9"] elink:reassign-node2-disks-to-node4.html#auto_check_4_step9["Reatribuir discos node2 a node4, passo 9"] .

3 a atualização automática ARL de um sistema AFF A300 para um sistema AFF A800 é suportada a partir do ONTAP 9.7P5.

4 a atualização automática ARL de um AFF A300 para um AFF A400 e um FAS8200 para um sistema FAS8300 é suportada a partir do ONTAP 9.7P8.

5 se você estiver atualizando de um AFF A300 para um AFF A400 ou um FAS8200 para um sistema FAS8300 em uma configuração de cluster sem switch de dois nós, você deve escolher portas de cluster temporárias para a atualização do controlador. Os sistemas AFF A400 e FAS8300 vêm em duas configurações, como um pacote Ethernet onde as portas da placa mezzanine são do tipo Ethernet e como um pacote FC onde as portas mezzanine são do tipo FC.

* Para um AFF A400 ou um FAS8300 com uma configuração de tipo Ethernet, você pode usar qualquer uma das duas portas mezzanine como portas de cluster temporárias.
* Para um AFF A400 ou um FAS8300 com uma configuração de tipo FC, você deve adicionar uma placa de interface de rede 10GbE de quatro portas (código de peça X1147A) para fornecer portas de cluster temporárias.
* Após concluir a atualização da controladora usando portas de cluster temporárias, é possível migrar LIFs de cluster para portas E3A e e3b, 100GbE em um sistema AFF A400 e portas e0c e e0d, 100GbE em um sistema FAS8300 sem interrupções.




== Escolha um procedimento de atualização de hardware diferente

* link:../upgrade-arl/index.html["Revise os métodos ARL alternativos disponíveis para atualizar o hardware do controlador"].
* Se você preferir um método diferente de atualizar o hardware do controlador e estiver disposto a fazer movimentos de volume, consulte link:other_references.html["Referências"]o link para _Upgrade movendo volumes ou armazenamento_.


.Informações relacionadas
Consulte link:other_references.html["Referências"] para acessar a _Documentação do ONTAP 9_.
