---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: 'Entenda se você pode atualizar controladores executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Diretrizes para atualização de controladores com ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para entender se você pode usar o ARL (Aggregate Relocation) para atualizar um par de controladores que executam o ONTAP 9.5 para o ONTAP 9.7 depende da plataforma e da configuração das controladoras originais e de substituição.



[[supported-upgrades-for-arl]]
== Atualizações suportadas para ARL

Quando você atualiza um par de nós usando este procedimento ARL para o ONTAP 9.5 para o ONTAP 9.7, você deve verificar se o ARL pode ser executado nos controladores original e de substituição.

Você deve verificar o tamanho de todos os agregados definidos e o número de discos suportados pelo sistema original. Em seguida, você deve comparar os tamanhos de agregados e o número de discos suportados com o tamanho de agregado e o número de discos suportados pelo novo sistema. Consulte link:other-references.html["Referências"] para acessar o _Hardware Universe_, onde essas informações estão disponíveis. O tamanho de agregado e o número de discos suportados pelo novo sistema devem ser iguais ou maiores que o tamanho de agregado e o número de discos suportados pelo sistema original.

Você deve validar nas regras de mistura de clusters se novos nós podem se integrar ao cluster com os nós existentes quando o controlador original for substituído. Para mais informações sobre regras de mistura de clusters, consulte link:other-references.html["Referências"] para acessar o _Hardware Universe_.


NOTE: Antes de executar uma atualização do sistema AFF, você deve atualizar o ONTAP para lançar as versões 9.5P1 ou posterior. Esses níveis de versão são necessários para uma atualização bem-sucedida.


NOTE: Se você estiver atualizando um sistema que suporta unidades internas (por exemplo, um FAS2700 ou AFF A250), mas NÃO possui unidades internas, consulte link:other-references.html["Referências"] e utilize o procedimento no conteúdo _Relocação de Agregados para Atualização Manual do Hardware do Controlador_ que seja adequado para a sua versão do ONTAP.

Se você estiver usando o ONTAP 9.6P11, 9.7P8 ou versões posteriores, é recomendável ativar o controle de conetividade, vivacidade e disponibilidade do monitor (CLAM) para retornar o cluster ao quorum quando certas falhas de nó ocorrerem. O `kernel-service` comando requer acesso avançado ao nível de privilégio. Para obter mais informações, consulte: https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["Artigo SU436 da NetApp KB: Configuração padrão de aquisição do CLAM alterada"^].

A atualização da controladora usando ARL é compatível com sistemas configurados com volumes de conformidade SnapLock Enterprise e SnapLock.



[[two-node-switchless-clusters]]
== Clusters sem switch de dois nós

Se você estiver atualizando nós em um cluster sem switch de dois nós, poderá deixar os nós no cluster sem switch durante a atualização. Você não precisa convertê-los em um cluster comutado.



[[upgrades-not-supported-for-arl]]
== Atualizações não suportadas para ARL

Você não pode executar as seguintes atualizações:

* Para substituir as controladoras que não são compatíveis com as gavetas de disco conectadas às controladoras originais
+
Consulte link:other-references.html["Referências"] para acessar o _Hardware Universe_ e obter informações sobre suporte a discos.

* Para controladores de nível básico com acionamentos internos, por exemplo: um FAS2750.
+
Se você deseja atualizar controladores de nível básico com unidades internas, consulte link:other-references.html["Referências"] para acessar _Atualizar movendo volumes ou armazenamento_ e vá para o procedimento _Atualizando um par de nós executando Clustered Data ONTAP movendo volumes_.





[[metrocluster-fc-configuration]]
== Configuração FC do MetroCluster

Em uma configuração MetroCluster FC, você precisa substituir os nós do local de failover/recuperação de desastre o mais rápido possível. A incompatibilidade entre modelos de controladores em uma configuração do MetroCluster não é suportada porque a incompatibilidade entre modelos de controladores pode fazer com que o espelhamento de recuperação de desastres fique offline. Use o  `-skip-metrocluster-check true` comando para ignorar as verificações do MetroCluster quando você estiver substituindo nós no segundo site.



[[troubleshoot]]
== Solucionar problemas

Você pode encontrar uma falha ao atualizar o par de nós. O nó pode falhar, os agregados podem não ser relocados ou LIFs podem não migrar. A causa da falha e sua solução dependem de quando a falha ocorreu durante o procedimento de atualização.

Consulte a tabela que descreve as diferentes fases do procedimento na seção Visão geral da atualização do ARL. As informações sobre as falhas que podem ocorrer são listadas pela fase do procedimento.

Se ocorrerem problemas durante a atualização dos controladores, consulte olink:aggregate_relocation_failures.html["Solucionar problemas"] seção.  As informações sobre as falhas que podem ocorrer são listadas por fase do procedimento nolink:overview_of_the_arl_upgrade.html["Sequência de atualização do ARL"] .

Se você não encontrar uma solução para o problema que encontrou, entre em Contato com o suporte técnico.
