---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: 'Entenda se você pode atualizar controladores executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Diretrizes para atualização de controladores com ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para entender se você pode usar o ARL (Aggregate Relocation) para atualizar um par de controladores que executam o ONTAP 9.5 para o ONTAP 9.7 depende da plataforma e da configuração das controladoras originais e de substituição.



== Atualizações suportadas para ARL

Quando você atualiza um par de nós usando este procedimento ARL para o ONTAP 9.5 para o ONTAP 9.7, você deve verificar se o ARL pode ser executado nos controladores original e de substituição.

Você deve verificar o tamanho de todos os agregados definidos e o número de discos suportados pelo sistema original. Em seguida, você deve comparar os tamanhos de agregados e o número de discos suportados com o tamanho de agregado e o número de discos suportados pelo novo sistema. Consulte a link:other_references.html["Referências"]ligação para o _Hardware Universe_ onde esta informação está disponível. O tamanho agregado e o número de discos suportados pelo novo sistema devem ser iguais ou superiores ao tamanho agregado e ao número de discos suportados pelo sistema original.

Você deve validar nas regras de mistura de cluster se novos nós podem se tornar parte do cluster com os nós existentes, quando o controlador original for substituído. Para obter mais informações sobre as regras de mistura de cluster, consulte o link:other_references.html["Referências"]link para o _Hardware Universe_.


NOTE: Antes de executar uma atualização do sistema AFF, você deve atualizar o ONTAP para lançar as versões 9.5P1 ou posterior. Esses níveis de versão são necessários para uma atualização bem-sucedida.


NOTE: Se você estiver atualizando um sistema que suporte unidades internas (por exemplo, um FAS2700 ou AFF A250), mas NÃO tiver unidades internas, consulte link:other_references.html["Referências"]e use o procedimento no _realocação agregada para atualizar manualmente o hardware do controlador_ conteúdo correto para sua versão do ONTAP.

Se você estiver usando o ONTAP 9.6P11, 9.7P8 ou versões posteriores, é recomendável ativar o controle de conetividade, vivacidade e disponibilidade do monitor (CLAM) para retornar o cluster ao quorum quando certas falhas de nó ocorrerem. O `kernel-service` comando requer acesso avançado ao nível de privilégio. Para obter mais informações, consulte: https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["Artigo SU436 da NetApp KB: Configuração padrão de aquisição do CLAM alterada"^].

A atualização da controladora usando ARL é compatível com sistemas configurados com volumes de conformidade SnapLock Enterprise e SnapLock.



== Clusters sem switch de dois nós

Se você estiver atualizando nós em um cluster sem switch de dois nós, poderá deixar os nós no cluster sem switch durante a atualização. Você não precisa convertê-los em um cluster comutado.



== Atualizações não suportadas para ARL

Você não pode executar as seguintes atualizações:

* Para substituir as controladoras que não são compatíveis com as gavetas de disco conectadas às controladoras originais
+
link:other_references.html["Referências"]Consulte o link para o _Hardware Universe_ para obter informações de suporte a disco.

* Para controladores de nível de entrada com unidades internas, por exemplo: Um FAS 2500.
+
Se você quiser atualizar controladores de nível de entrada com unidades internas, link:other_references.html["Referências"]consulte o link para _Atualizar movendo volumes ou armazenamento_ e vá para o procedimento _Atualizar um par de nós executando Data ONTAP em cluster movendo volumes_.





== Solução de problemas

Se ocorrerem problemas durante a atualização dos controladores, consulte link:troubleshoot_index.html["Solucionar problemas"]a secção no final do procedimento para obter mais informações e possíveis soluções.

Se você não encontrar uma solução para o problema que encontrou, entre em Contato com o suporte técnico.
