---
sidebar: sidebar 
permalink: upgrade-arl-auto/move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html 
keywords: aggregate relocation, lifs, node3, node1, node2, NAS 
summary: 'Mova as LIFs de dados do nas node1 no node2 de node2 para node3 ao atualizar controladoras executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Migre agregados que não sejam raiz e LIFs de dados nas pertencentes ao node1 de node2 para node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depois de verificar a instalação do node3 e antes de realocar agregados de node2 para node3, você deve mover os LIFs de dados do nas pertencentes ao node1 que estão atualmente no node2 de node2 para node3. Você também deve verificar se as SAN LIFs existem no node3.

.Sobre esta tarefa
Os LIFs remotos manipulam o tráfego para LUNs SAN durante o procedimento de atualização. A movimentação de SAN LIFs não é necessária para o cluster ou a integridade do serviço durante a atualização. Os LIFs DE SAN não são movidos a menos que precisem ser mapeados para novas portas. Você irá verificar se os LIFs estão saudáveis e localizados em portas apropriadas depois de colocar o node3 on-line.

.Passos
. Retomar a operação de realocação:
+
`system controller replace resume`

+
O sistema executa as seguintes tarefas:

+
** Verificação do quorum do cluster
** Verificação da ID do sistema
** Verificação da versão da imagem
** Verificação da plataforma alvo
** Verificação de acessibilidade da rede


+
A operação é interrompida nesta fase na verificação de acessibilidade da rede.

. Verifique manualmente se a rede e todas as VLANs, grupos de interface e domínios de broadcast foram configurados corretamente.
. Retomar a operação de realocação:
+
`system controller replace resume`

+
[listing]
----
To complete the "Network Reachability" phase, ONTAP network configuration must
be manually adjusted to match the new physical network configuration of the
hardware. This includes assigning network ports to the correct broadcast
domains, creating any required ifgrps and VLANs, and modifying the home-port
parameter of network interfaces to the appropriate ports. Refer to the "Using
aggregate relocation to upgrade controller hardware on a pair of nodes running
ONTAP 9.x" documentation, Stages 3 and 5. Have all of these steps been manually
completed? [y/n]
----
. Entre `y` para continuar.
. O sistema efetua as seguintes verificações:
+
** Verificação de integridade do cluster
** Verificação do status de LIF do cluster


+
Depois de executar essas verificações, o sistema relocaliza os agregados não-raiz e LIFs de dados nas de propriedade do node1 para a nova controladora, node3. O sistema pára quando a realocação de recursos estiver concluída.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
`system controller replace show-details`

. Verifique se os agregados não-raiz e LIFs de dados nas foram relocados com sucesso para node3.
+
Se algum agregado não conseguir realocar ou estiver vetado, você deve realocar manualmente os agregados ou substituir os vetos ou as verificações de destino, se necessário. Consulte link:relocate_failed_or_vetoed_aggr.html["Realocar agregados com falha ou vetado"] para obter mais informações.

. Verifique se as SAN LIFs estão nas portas corretas no node3, executando as seguintes subetapas:
+
.. Digite o seguinte comando e examine sua saída:
+
`network interface show -data-protocol _iscsi|fcp_ -home-node _node3_`

+
O sistema retorna uma saída semelhante ao seguinte exemplo:

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3

        Logical   Status     Network           Current  Current Is
Vserver Interface Admin/Oper Address/Mask      Node     Port    Home
------- --------- ---------- ----------------- -------- ------- ----
vs0
        a0a       up/down     10.63.0.53/24     node3   a0a     true
        data1     up/up       10.63.0.50/18     node3   e0c     true
        rads1     up/up       10.63.0.51/18     node3   e1a     true
        rads2     up/down     10.63.0.52/24     node3   e1b     true
vs1
        lif1      up/up       172.17.176.120/24 node3   e0c     true
        lif2      up/up       172.17.176.121/24 node3   e1a     true
----
.. Se o node3 tiver quaisquer LIFs SAN ou grupos de LIFs SAN que estejam em uma porta que não exista no node1 ou que precisem ser mapeados para uma porta diferente, mova-os para uma porta apropriada no node3 executando as seguintes subetapas:
+
... Defina o status de LIF para baixo:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -status-admin down`

... Remova o LIF do conjunto de portas:
+
`portset remove -vserver _Vserver_name_ -portset _portset_name_ -port-name _port_name_`

... Introduza um dos seguintes comandos:
+
**** Mover um único LIF:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-port _new_home_port_`

**** Mova todos os LIFs em uma única porta inexistente ou incorreta para uma nova porta:
+
`network interface modify {-home-port _port_on_node1_ -home-node _node1_ -role data} -home-port _new_home_port_on_node3_`

**** Adicione os LIFs de volta ao conjunto de portas:
+
`portset add -vserver _Vserver_name_ -portset _portset_name_ -port-name _port_name_`

+

NOTE: Você deve confirmar que você moveu SAN LIFs para uma porta que tenha a mesma velocidade de link que a porta original.





.. Modifique o status de todos os LIFs para "up" para que os LIFs possam aceitar e enviar tráfego no nó:
+
`network interface modify -home-port _port_name_ -home-node _node3_ -lif data -status admin up`

.. Digite o seguinte comando em qualquer nó e examine sua saída para verificar se LIFs foram movidos para as portas corretas e se os LIFs têm o status de `up`:
+
`network interface show -home-node _node3_ -role data`

.. Se algum LIFs estiver inativo, defina o status administrativo dos LIFs para `up` digitando o seguinte comando, uma vez para cada LIF:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin up`



. Retome a operação para solicitar ao sistema que execute as verificações posteriores necessárias:
+
`system controller replace resume`

+
O sistema efetua as seguintes verificações posteriores:

+
** Verificação do quorum do cluster
** Verificação de integridade do cluster
** Verificação de reconstrução de agregados
** Verificação do status do agregado
** Verificação do estado do disco
** Verificação do status de LIF do cluster



