---
sidebar: sidebar 
permalink: upgrade-arl-auto/overview_of_the_arl_upgrade.html 
keywords: aggregate relocation, upgrade, process, overview, stages 
summary: 'Entenda como funciona o procedimento para atualizar controladores executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Visão geral da atualização ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de atualizar os nós usando ARL, você deve entender como o procedimento funciona. Neste conteúdo, o procedimento é dividido em várias etapas.



== Atualize o par de nós

Para atualizar o par de nós, você precisa preparar os nós originais e, em seguida, executar uma série de etapas nos nós original e novo. Em seguida, você pode desativar os nós originais.



== Visão geral da sequência de atualização ARL

Durante o procedimento, você atualiza o hardware da controladora original com o hardware da controladora de substituição, uma controladora de cada vez, aproveitando a configuração do par de HA para realocar a propriedade de agregados que não sejam raiz. Todos os agregados não-raiz devem passar por duas relocalizações para alcançar seu destino final, que é o nó atualizado correto.

Cada agregado tem um proprietário de casa e proprietário atual. O proprietário da casa é o proprietário real do agregado, e o proprietário atual é o proprietário temporário.

A tabela a seguir descreve as tarefas de alto nível executadas durante cada etapa e o estado de propriedade agregada no final da etapa. Etapas detalhadas são fornecidas posteriormente no procedimento:

[cols="25,75"]
|===
| Fase | Passos 


| link:stage_1_index.html["Fase 1. Prepare-se para a atualização"]  a| 
Durante a fase 1, você executa pré-verificações e, se necessário, corrige a propriedade agregada. Você deve Registrar certas informações se estiver gerenciando a criptografia de armazenamento usando o Gerenciador de chaves integrado e você pode optar por silenciar as relações do SnapMirror.

Propriedade agregada no final da fase 1:

* node1 é o proprietário da casa e atual proprietário dos agregados node1.
* Node2 é o proprietário da casa e atual proprietário dos agregados node2.




| link:stage_2_index.html["Fase 2. Transferir e retirar node1"]  a| 
Durante a fase 2, você realocar node1 agregados não-raiz e LIFs de dados nas para node2. Esse processo é amplamente automatizado; a operação é interrompida para permitir que você verifique seu status. Tem de retomar manualmente a operação. Se necessário, você realocar agregados com falha ou vetado. Tem de registar as informações node1 necessárias para utilização posterior no procedimento e, em seguida, desativar node1. Você também pode se preparar para netboot node3 e node4 posteriormente no procedimento.

Propriedade agregada no final da fase 2:

* Node2 é o atual proprietário de node1 agregados.
* Node2 é o proprietário da casa e atual proprietário de node2 agregados.




| link:stage_3_index.html["Fase 3. Instale e inicialize node3"]  a| 
Durante a fase 3, você instala e inicia o node3, mapeia as portas de gerenciamento de clusters e nós de node1 a node3, reatribui os discos node1 a node3 e verifica a instalação do node3. Se necessário, você define a configuração FC ou UTA/UTA2 em node3 e confirma que o node3 aderiu ao quórum. Você também realocar os LIFs de dados nas node1 e agregados não-raiz de node2 para node3 e verificar se os LIFs SAN existem no node3.

Propriedade agregada no final da fase 3:

* Node3 é o proprietário da casa e atual proprietário de node1 agregados.
* Node2 é o proprietário da casa e atual proprietário de node2 agregados.




| link:stage_4_index.html["Fase 4. Transferir e retirar node2"]  a| 
Durante a fase 4, você realocará node2 agregados não-raiz e LIFs de dados não-SAN para node3. Você também Registra as informações node2 necessárias e, em seguida, aposenta node2.

Propriedade agregada no final da fase 4:

* Node3 é o proprietário da casa e atual proprietário de agregados que originalmente pertenciam a node1.
* Node2 é o proprietário da casa de node2 agregados.
* Node3 é o atual proprietário de node2 agregados.




| link:stage_5_index.html["Fase 5. Instale e inicialize node4"]  a| 
Durante a fase 5, você instala e inicia o node4, mapeia as portas de gerenciamento de clusters e nós de node2 a node4, reatribui os discos node2 a node4 e verifica a instalação do node4. Se necessário, você define a configuração FC ou UTA/UTA2 em node4 e confirma que o node4 aderiu ao quórum. Você também relocaliza node2 LIFs de dados nas e agregados não-raiz de node3 para node4 e verifica se os LIFs SAN existem no node4.

Propriedade agregada no final da fase 5:

* Node3 é o proprietário da casa e atual proprietário dos agregados que originalmente pertenciam a node1.
* Node4 é o proprietário da casa e atual proprietário de agregados que originalmente pertenciam a node2.




| link:stage_6_index.html["Fase 6. Conclua a atualização"]  a| 
Durante a fase 6, você confirma que os novos nós estão configurados corretamente e, se os novos nós estiverem habilitados para criptografia, você configura e configura a criptografia de armazenamento ou a criptografia de volume do NetApp. Você também deve desativar os nós antigos e retomar as operações do SnapMirror.

|===