---
sidebar: sidebar 
permalink: upgrade-arl-auto/reassign-node1-disks-to-node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports, FlexArray Virtualization 
summary: 'Configure node3 portas FC integradas, portas UTA/UTA2 ou a placa UTA/UTA2 ao atualizar as controladoras executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Reatribuir discos node1 a node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você precisa reatribuir os discos que pertenciam ao node1 ao node3 antes de verificar a instalação do node3.

.Sobre esta tarefa
Execute as etapas nesta seção em node3.

.Passos
. [[reassign-node1-node3-step1]]vá para o menu de inicialização e usando 22/7 e selecione a opção oculta `boot_after_controller_replacement` . No prompt, digite node1 para reatribuir os discos de node1 a node3, conforme o exemplo a seguir.
+
.Expanda o exemplo de saída do console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement)   Boot after controller upgrade
(9a)                                  Unpartition all disks and remove their ownership information.
(9b)                                  Clean configuration and initialize node with partitioned disks.
(9c)                                  Clean configuration and initialize node with whole disks.
(9d)                                  Reboot the node.
(9e)                                  Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to
disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
.
.
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login:
...
----
====
. Se o sistema entrar em um loop de reinicialização com a mensagem `no disks found`, isso ocorre porque ele redefiniu as portas de volta para o modo de destino e, portanto, não consegue ver nenhum disco. Continue com <<auto_check3_step3,Passo 3>> para <<auto_check3_step8,Passo 8>>resolver este problema.
. [[auto_check3_step3]]pressione Ctrl-C durante o AUTOBOOT para parar o nó no prompt Loader>.
. [[step18]]no prompt DO Loader, entre no modo de manutenção:
+
`boot_ontap maint`

. [[step19]]no modo de manutenção, exiba todas as portas do iniciador definidas anteriormente que estão agora no modo de destino:
+
`ucadmin show`

+
Altere as portas novamente para o modo iniciador:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[step20]]Verifique se as portas foram alteradas para o modo iniciador:
+
`ucadmin show`

. [[step21]]Sair do modo de manutenção:
+
`halt`

+
[NOTE]
====
Se você estiver atualizando de um sistema que suporte discos externos para um sistema que também suporte discos externos, vá para <<auto_check3_step8,Passo 8>>.

Se você estiver atualizando de um sistema que suporte discos externos para um sistema que suporte discos internos e externos, por exemplo, um sistema AFF A800, vá para <<auto_check3_step9,Passo 9>>.

====
. [[auto_check3_step8]]no prompt DO Loader, inicialize:
+
`boot_ontap menu`

+
Agora, na inicialização, o nó pode detetar todos os discos que foram atribuídos anteriormente a ele e pode inicializar como esperado.

+
Quando os nós de cluster que você está substituindo usam criptografia de volume raiz, o ONTAP não consegue ler as informações de volume dos discos. Restaure as chaves para o volume raiz:

+
.. Voltar ao menu de arranque especial:
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Selecione *(10) Definir segredos de recuperação do Onboard Key Manager*
.. Digite `y` no seguinte prompt:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. No prompt, insira a senha do gerenciador de chaves.
.. Insira os dados de backup quando solicitado.
+

NOTE: Tem de ter obtido a frase-passe e os dados de cópia de segurança na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]secção deste procedimento.

.. Depois de o sistema reiniciar para o menu de inicialização especial, execute a opção *(1) normal Boot*
+

NOTE: Você pode encontrar um erro nesta fase. Se ocorrer um erro, repita as subetapas em <<auto_check3_step8,Passo 8>> até que o sistema inicialize normalmente.



. [[auto_check3_step9]]se você estiver atualizando de um sistema com discos externos para um sistema que suporta discos internos e externos (sistemas AFF A800, por exemplo), defina o agregado node1 como o agregado raiz para confirmar que o node3 inicializa a partir do agregado raiz de node1. Para definir o agregado raiz, vá para o menu de inicialização e selecione a opção `5` para entrar no modo de manutenção.
+

CAUTION: *Você deve executar as seguintes subetapas na ordem exata mostrada; a falha em fazê-lo pode causar uma interrupção ou até mesmo perda de dados.*

+
O procedimento a seguir define node3 para inicializar a partir do agregado raiz de node1:

+
.. Entre no modo de manutenção:
+
`boot_ontap maint`

.. Verifique as informações de RAID, Plex e checksum para o agregado node1:
+
`aggr status -r`

.. Verifique o status do agregado node1:
+
`aggr status`

.. Se necessário, coloque o agregado node1 online:
+
`aggr_online root_aggr_from___node1__`

.. Evite que o node3 inicialize a partir do seu agregado raiz original:
+
`aggr offline _root_aggr_on_node3_`

.. Defina o agregado de raiz node1 como o novo agregado de raiz para node3:
+
`aggr options aggr_from___node1__ root`

.. Verifique se o agregado raiz do node3 está offline e o agregado raiz dos discos trazidos do node1 está online e definido como root:
+
`aggr status`

+

NOTE: A falha na execução da subetapa anterior pode fazer com que o node3 seja inicializado a partir do agregado raiz interno, ou pode fazer com que o sistema assuma que existe uma nova configuração de cluster ou peça para que você identifique uma.

+
O seguinte mostra um exemplo da saída do comando:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



