---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'Configure node4 portas FC integradas, portas UTA/UTA2 ou a placa UTA/UTA2 ao atualizar as controladoras executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Defina a configuração FC ou UTA/UTA2 em node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o node4 tiver portas FC integradas, portas de adaptador unificado de destino integrado (UTA/UTA2) ou uma placa UTA/UTA2, você deverá configurar as configurações antes de concluir o restante do procedimento.

.Sobre esta tarefa
Talvez seja necessário concluir a <<Configurar portas FC no node4>> seção ou<<Verifique e configure as portas UTA/UTA2 no node4>>, ou ambas as seções.


NOTE: Se o node4 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2 e estiver atualizando um sistema com discos de storage, você poderá pular para a link:map_ports_node2_node4.html["Portas de mapa de node2 a node4"] seção. No entanto, se você tiver um sistema da série V ou tiver um software de virtualização FlexArray e estiver conetado a storages de armazenamento, e o node4 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deverá retornar à seção _Instalar e inicializar node4_ e continuar em link:install_boot_node4.html#step22["Passo 22"]. Certifique-se de que o node4 tem espaço suficiente no rack. Se o node4 estiver em um chassi separado do node2, você pode colocar o node4 no mesmo local que o node3. Se o node2 e o node4 estiverem no mesmo chassi, o node4 já estará no local apropriado do rack.

.Opções
* <<Configurar portas FC no node4>>
* <<Verifique e configure as portas UTA/UTA2 no node4>>




== Configurar portas FC no node4

Se o node4 tiver portas FC, integradas ou em um adaptador FC, você precisará definir configurações de porta no nó antes de colocá-lo em serviço, pois as portas não estão pré-configuradas. Se as portas não estiverem configuradas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node2 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou um adaptador UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node4>>.


IMPORTANT: Se o sistema tiver discos de armazenamento, você deverá inserir os comandos nesta seção no prompt do cluster. Se tiver um sistema da série V ou um sistema com software de virtualização FlexArray ligado a matrizes de armazenamento, introduza os comandos nesta secção no modo de manutenção.

.Passos
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento | `system node hardware unified-connect show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
O sistema exibe informações sobre todos os adaptadores de rede FC e convergentes no sistema.

. Compare as configurações FC em node4 com as configurações que você capturou anteriormente de node1.
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
Modifique as portas FC no node4 conforme necessário:

** Para programar portas de destino:
+
`ucadmin modify -m fc -t target _adapter_`

** Para programar portas do iniciador:
+
`ucadmin modify -m fc -t initiator _adapter_`



`-t` É o tipo FC4: Alvo ou iniciador.



| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
Modifique as portas FC no node4 conforme necessário:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` É o tipo FC4, alvo ou iniciador.


NOTE: As portas FC devem ser programadas como iniciadores.

|===
. Sair do modo de manutenção:
+
`halt`

. Inicie o sistema a partir do prompt Loader:
+
`boot_ontap menu`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Selecione a opção `5` no menu de arranque para o modo de manutenção.


. [[step8]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
** Ignore esta seção e vá para link:map_ports_node2_node4.html["Portas de mapa de node2 a node4"] se o node4 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2.




| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
** Vá para link:set_fc_or_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["Verifique e configure as portas UTA/UTA2 no node4"] se o node4 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2.
** Ignore a seção _verificar e configurar portas UTA/UTA2 no node4_ se o node4 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, retorne à seção _Instalar e inicializar node4_ e continue em link:install_boot_node4.html#auto_install4_step23["Passo 23"].


|===




== Verifique e configure as portas UTA/UTA2 no node4

Se o node4 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2A, você deve verificar a configuração das portas e configurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2A. O modo FC suporta o iniciador FC e o destino FC; o modo UTA/UTA2 permite que o tráfego de NIC e FCoE simultâneos compartilhem a mesma interface SFP 10GbE e suporte ao destino FC.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

As PORTAS UTA/UTA2 podem estar em um adaptador ou no controlador com as seguintes configurações:

* Os cartões UTA/UTA2 encomendados ao mesmo tempo que o controlador são configurados antes do envio para ter a personalidade que você solicitou.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novas controladoras são configuradas (antes do envio) para ter a personalidade que você solicitou.


No entanto, você deve verificar a configuração das portas UTA/UTA2 no node4 e alterá-la, se necessário.


WARNING: *Atenção*: Se o seu sistema tiver discos de armazenamento, você insere os comandos nesta seção no prompt do cluster, a menos que seja direcionado para entrar no modo de manutenção. Se você tiver um sistema MetroCluster FC, um sistema V-Series ou um sistema com software de virtualização FlexArray conetado a matrizes de armazenamento, você deve estar no modo de manutenção para configurar portas UTA/UTA2.

.Passos
. Verifique como as portas estão atualmente configuradas usando um dos seguintes comandos no node4:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `system node hardware unified-connect show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. Examine a saída do `ucadmin show` comando e determine se as portas UTA/UTA2 têm a personalidade desejada.
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas CNA... | Então... 


| Não tenha a personalidade que você quer | Vá para <<auto_check_4_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a Etapa 5 até a Etapa 12 e vá para <<auto_check_4_step13,Passo 13>>. 
|===
. [[auto_check_4_step5]]execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para <<auto_check_4_step7,Passo 7>> 


| Portas UTA/UTA2 integradas | Pule a Etapa 7 e vá para <<auto_check_4_step8,Passo 8>>. 
|===
. Se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver online, coloque a porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check_4_step7]]se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` É o modo personalidade, FC ou 10GbE UTA.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita, sistemas de virtualização FlexArray e configurações MetroCluster. Você deve usar o destino FC para clientes SAN.



. [[auto_check_4_step8]]Verifique as configurações usando o seguinte comando e examinando sua saída:
+
`ucadmin show`

. Verifique as configurações:
+
[cols="40,60"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `ucadmin show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Coloque todas as portas de destino on-line inserindo um dos seguintes comandos, uma vez para cada porta:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `fcp config _adapter_name_ up` 
|===
. Faça o cabo da porta.


. [[step12]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Vá para a secção link:map_ports_node2_node4.html["Portas de mapa de node2 a node4"]. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Retorne à seção _Instalar e inicializar node4_ e continue em link:install_boot_node4.html#auto_install4_step23["Passo 23"]. 
|===
. [[auto_check_4_step13]]Sair do modo de manutenção:
+
`halt`

. [[step14]]nó de inicialização no menu de inicialização:
+
`boot_ontap menu`

+
Se você estiver atualizando para um A800, vá para <<auto_check_4_step23,Passo 23>>.

. [[auto_check_4_step15]]no node4, vá para o menu de inicialização e, usando 22/7, selecione a opção oculta `boot_after_controller_replacement` . No prompt, digite node2 para reatribuir os discos de node2 a node4, conforme o exemplo a seguir.
+
.Expanda o exemplo de saída do console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu ...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement) Boot after controller upgrade
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
.
.
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login: ...
----
====
. Se o sistema entrar em um loop de reinicialização com a mensagem `no disks found`, isso ocorre porque ele redefiniu as portas de volta para o modo de destino e, portanto, não consegue ver nenhum disco. Continue com <<auto_check_4_step17,Passo 17>> até <<auto_check_4_step22,Passo 22>> para resolver isso.
. [[auto_check_4_step17]]pressione Ctrl-C durante o AUTOBOOT para parar o nó no prompt Loader>.
. No prompt Loader, entre no modo de manutenção:
+
`boot_ontap maint`

. No modo de manutenção, exiba todas as portas do iniciador definidas anteriormente que estão agora no modo de destino:
+
`ucadmin show`

+
Altere as portas novamente para o modo iniciador:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. Verifique se as portas foram alteradas para o modo iniciador:
+
`ucadmin show`

. Sair do modo de manutenção:
+
`halt`

+
[NOTE]
====
Se você estiver atualizando de um sistema que suporte discos externos para um sistema que também suporte discos externos, vá para <<auto_check_4_step22,Passo 22>>.

Se você estiver atualizando de um sistema que usa discos externos para um sistema que suporta discos internos e externos, por exemplo, um sistema AFF A800, vá para <<auto_check_4_step23,Passo 23>>.

====
. [[auto_check_4_step22]]no prompt DO Loader, inicialize:
+
`boot_ontap menu`

+
Agora, na inicialização, o nó pode detetar todos os discos que foram atribuídos anteriormente a ele e pode inicializar como esperado.

+
Quando os nós de cluster que você está substituindo usam criptografia de volume raiz, o ONTAP não consegue ler as informações de volume dos discos. Restaure as chaves para o volume raiz:

+
.. Voltar ao menu de arranque especial:
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Selecione *(10) Definir segredos de recuperação do Onboard Key Manager*
.. Digite `y` no seguinte prompt:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. No prompt, insira a senha do gerenciador de chaves.
.. Insira os dados de backup quando solicitado.
+

NOTE: Tem de ter obtido a frase-passe e os dados de cópia de segurança na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]secção deste procedimento.

.. Depois de o sistema reiniciar para o menu de inicialização especial, execute a opção *(1) normal Boot*
+

NOTE: Você pode encontrar um erro nesta fase. Se ocorrer um erro, repita as subetapas em <<auto_check_4_step22,Passo 22>> até que o sistema inicialize normalmente.



. [[auto_check_4_step23]]se você estiver atualizando de um sistema com discos externos para um sistema que suporte discos internos e externos (sistemas AFF A800, por exemplo), defina o agregado node2 como o agregado raiz para confirmar que o node4 inicializa a partir do agregado raiz de node2. Para definir o agregado raiz, vá para o menu de inicialização e selecione a opção `5` para entrar no modo de manutenção.
+

WARNING: *Você deve executar as seguintes subetapas na ordem exata mostrada; a falha em fazê-lo pode causar uma interrupção ou até mesmo perda de dados.*

+
O procedimento a seguir define node4 para inicializar a partir do agregado raiz de node2:

+
.. Entre no modo de manutenção:
+
`boot_ontap maint`

.. Verifique as informações de RAID, Plex e checksum para o agregado node2:
+
`aggr status -r`

.. Verifique o status do agregado node2:
+
`aggr status`

.. Se necessário, coloque o agregado node2 online:
+
`aggr_online root_aggr_from___node2__`

.. Evite que o node4 inicialize a partir do seu agregado raiz original:
+
`aggr offline _root_aggr_on_node4_`

.. Defina o agregado de raiz node2 como o novo agregado de raiz para node4:
+
`aggr options aggr_from___node2__ root`




