---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports 
summary: 'Configure node3 portas FC integradas, portas UTA/UTA2 ou a placa UTA/UTA2 ao atualizar as controladoras executando o ONTAP 9.5 para 9,7 usando `system controller replace` comandos.' 
---
= Defina a configuração FC ou UTA/UTA2 em node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o node3 tiver portas FC integradas, portas de adaptador unificado de destino integrado (UTA/UTA2) ou uma placa UTA/UTA2, você deverá configurar as configurações antes de concluir o restante do procedimento.

.Sobre esta tarefa
Talvez seja necessário preencher a <<Configurar portas FC no node3>>seção , a <<Verifique e configure as portas UTA/UTA2 no node3>>seção ou ambas as seções.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas de adaptador de rede convergente (CNA). No entanto, a CLI usa o termo CNA.

Se o node3 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2 e você estiver atualizando um sistema com discos de storage, poderá pular para link:reassign-node1-disks-to-node3.html["Reatribuir discos node1 a node3"]o .



== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC adicional, você deverá definir as configurações de porta no nó antes de colocá-lo em serviço, porque as portas não são pré-configuradas quando os sistemas são enviados.  Se você não configurar as portas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Insira os comandos desta seção no prompt do shell do modo de manutenção.

.Passos
. Compare as configurações de FC no nó 3 com as configurações que você capturou anteriormente do nó 1.
. Execute uma das seguintes ações para modificar as portas FC no node3, conforme necessário:
+
No modo de manutenção (opção 5 no menu de inicialização):

+
** Para programar como portas de destino:
+
`ucadmin modify -m fc -t target <adapter>`

+
Por exemplo: `ucadmin modify -m fc -t target 2a`

** Para programar portas do iniciador:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Por exemplo: `ucadmin modify -m fc -t initator 2b`



. Verifique as novas configurações usando o seguinte comando e examinando a saída:
+
`ucadmin show`

. Parar o nó:
+
`halt`

. Inicie o sistema a partir do prompt Loader:
+
`boot_ontap menu`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Selecione a opção `5` no menu de arranque para o modo de manutenção.


. Execute uma das seguintes ações:
+
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, pule <<Verifique e configure as portas UTA/UTA2 no node3>> e vá para link:reassign-node1-disks-to-node3.html["Reatribuir discos node1 a node3"].






== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para visualizar ou verificar a configuração atual da porta, conforme mostrado no exemplo de saída a seguir:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

Você pode encontrar portas UTA/UTA2 em um adaptador adicional ou na placa-mãe do controlador, com as seguintes configurações, mas deve verificar a configuração das portas UTA/UTA2 no Node 3 e alterá-la, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

WARNING: Você deve estar no modo de manutenção para configurar portas UTA/UTA2.  Insira os comandos desta seção no prompt do shell do modo de manutenção.



.Passos
. Se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. Verifique as configurações da porta UTA/UTA2:
+
`ucadmin show`

+
Examine a saída e determine se as portas UTA/UTA2 têm a personalidade desejada.

+
A saída no exemplo a seguir mostra que o tipo de adaptador "1b" está mudando para iniciador e que o modo dos adaptadores "2a" e "2b" está mudando para "cna".  O modo CNA permite que você use o cartão como um adaptador de rede.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para<<auto_check3_step4,Passo 4>> . 


| Tenha a personalidade que você quer | Pule a Etapa 4 até a Etapa 8 e vá para<<auto_check3_step9,Passo 9>> . 
|===
. [[auto_check3_step4]]Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para<<auto_check3_step5,Passo 5>> 


| Portas UTA/UTA2 integradas | Pule a etapa 5 e vá para<<auto_check3_step6,Passo 6>> . 
|===
. [[auto_check3_step5]]Se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver on-line, coloque a porta UTA/UTA2 off-line:
+
`storage disable adapter <adapter_name>`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check3_step6]]Se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita e configurações do MetroCluster .  Você deve usar o destino FC para clientes SAN.



. Coloque todas as portas de destino on-line digitando o seguinte comando uma vez para cada porta:
+
`storage enable adapter <adapter_name>`

. Faça o cabo da porta.


[[auto_check3_step9]]
. Sair do modo de manutenção:
+
`halt`

. Inicialize o nó no menu de inicialização executando `boot_ontap menu` .


.O que se segue?
* Se você estiver atualizando para um sistema AFF A800 , vá paralink:reassign-node1-disks-to-node3.html#auto_check3_step9["Reatribuir discos node1 a node3, passo 9"] .
* Para todas as outras atualizações do sistema, vá paralink:reassign-node1-disks-to-node3.html["Reatribuir discos node1 a node3, passo 1"] .

