---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_3_index.html 
keywords: stage 3, install node3, non-SAN data LIFs, non-root aggregates 
summary: 'Sequência de processo do estágio 3 para uma atualização do ARL usando `system controller replace` comandos em controladores que executam o ONTAP 9.5 a 9,7.' 
---
= Visão geral da fase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante a fase 3, você instala e inicia o node3, mapeia as portas de gerenciamento de clusters e nós de node1 a node3 e verifica a instalação do node3. Se necessário, você define a configuração FC ou UTA/UTA2 em node3 e confirma que o node3 aderiu ao quórum. Você também realocar os LIFs de dados nas node1 e agregados não-raiz de node2 para node3 e verificar se os LIFs SAN existem no node3.

.Passos
. link:install_boot_node3.html["Instale e inicialize node3"]
. link:set_fc_or_uta_uta2_config_on_node3.html["Defina a configuração FC ou UTA/UTA2 em node3"]
. link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"]
. link:join_quorum_node_has_different_ports_stage3.html["Juntando-se ao quórum quando um nó tem um conjunto diferente de portas de rede"]
. link:verify_node3_installation.html["Verifique a instalação do node3"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html["Migre agregados que não sejam raiz e LIFs de dados nas pertencentes ao node1 de node2 para node3"]

