---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, MetroCluster, stage 6 
summary: 'Sequência de processo do estágio 6 para uma atualização do ARL usando `system controller replace` comandos em controladores que executam o ONTAP 9.5 a 9,7.' 
---
= Visão geral da fase 6
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante a fase 6, você confirma que os novos nós estão configurados corretamente e, se os novos nós estiverem habilitados para criptografia, você configura e configura a criptografia de armazenamento ou a criptografia de volume do NetApp. Você também deve desativar os nós antigos e retomar as operações do SnapMirror.

.Passos
. link:manage-authentication-using-kmip-servers.html["Gerenciar a autenticação usando servidores KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Confirme se os novos controladores estão configurados corretamente"]
. link:set_up_storage_encryption_new_module.html["Configure a criptografia de armazenamento no novo módulo do controlador"]
. link:set_up_netapp_volume_encryption_new_module.html["Configure o volume NetApp ou a encriptação agregada no novo módulo do controlador"]
. link:decommission_old_system.html["Desativar o sistema antigo"]
. link:resume_snapmirror_operations.html["Retomar as operações do SnapMirror"]


.Configuração FC do MetroCluster
Em uma configuração MetroCluster FC, você precisa substituir os nós do local de failover/recuperação de desastre o mais rápido possível. A incompatibilidade nos modelos de controladora em um MetroCluster não é suportada porque a incompatibilidade do modelo do controlador pode fazer com que o espelhamento de recuperação de desastres fique offline. Use o `-skip-metrocluster-check true` comando para ignorar as verificações do MetroCluster quando estiver substituindo nós no segundo local.
