= Configurar portas FC no node3
:allow-uri-read: 




== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC adicional, você deverá definir as configurações de porta no nó antes de colocá-lo em serviço, porque as portas não são pré-configuradas quando os sistemas são enviados.  Se você não configurar as portas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Insira os comandos desta seção no prompt do shell do modo de manutenção.

.Passos
. Compare as configurações de FC no nó 3 com as configurações que você capturou anteriormente do nó 1.
. Execute uma das seguintes ações para modificar as portas FC no node3, conforme necessário:
+
No modo de manutenção (opção 5 no menu de inicialização):

+
** Para programar como portas de destino:
+
`ucadmin modify -m fc -t target <adapter>`

+
Por exemplo: `ucadmin modify -m fc -t target 2a`

** Para programar portas do iniciador:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Por exemplo: `ucadmin modify -m fc -t initator 2b`



. Verifique as novas configurações usando o seguinte comando e examinando a saída:
+
`ucadmin show`

. Parar o nó:
+
`halt`

. Inicie o sistema a partir do prompt Loader:
+
`boot_ontap menu`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Selecione a opção `5` no menu de arranque para o modo de manutenção.

