= Verifique e configure as portas UTA/UTA2 no node3
:allow-uri-read: 




== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para visualizar ou verificar a configuração atual da porta, conforme mostrado no exemplo de saída a seguir:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

Você pode encontrar portas UTA/UTA2 em um adaptador adicional ou na placa-mãe do controlador, com as seguintes configurações, mas deve verificar a configuração das portas UTA/UTA2 no Node 3 e alterá-la, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

WARNING: Você deve estar no modo de manutenção para configurar portas UTA/UTA2.  Insira os comandos desta seção no prompt do shell do modo de manutenção.



.Passos
. Se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. Verifique as configurações da porta UTA/UTA2:
+
`ucadmin show`

+
Examine a saída e determine se as portas UTA/UTA2 têm a personalidade desejada.

+
A saída no exemplo a seguir mostra que o tipo de adaptador "1b" está mudando para iniciador e que o modo dos adaptadores "2a" e "2b" está mudando para "cna".  O modo CNA permite que você use o cartão como um adaptador de rede.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para<<auto_check3_step4,Passo 4>> . 


| Tenha a personalidade que você quer | Pule a Etapa 4 até a Etapa 8 e vá para<<auto_check3_step9,Passo 9>> . 
|===
. [[auto_check3_step4]]Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para<<auto_check3_step5,Passo 5>> 


| Portas UTA/UTA2 integradas | Pule a etapa 5 e vá para<<auto_check3_step6,Passo 6>> . 
|===
. [[auto_check3_step5]]Se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver on-line, coloque a porta UTA/UTA2 off-line:
+
`storage disable adapter <adapter_name>`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check3_step6]]Se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita e configurações do MetroCluster .  Você deve usar o destino FC para clientes SAN.



. Coloque todas as portas de destino on-line digitando o seguinte comando uma vez para cada porta:
+
`storage enable adapter <adapter_name>`

. Faça o cabo da porta.

