= Configurar portas FC no node4
:allow-uri-read: 




== Configurar portas FC no node4

Se o node4 tiver portas FC, integradas ou em um adaptador FC adicional, você deverá definir as configurações de porta no nó antes de colocá-lo em serviço, porque as portas não são pré-configuradas quando os sistemas são enviados.  Se você não configurar as portas conforme necessário, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node2 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou um adaptador UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node4>>.


IMPORTANT: Insira os comandos desta seção no prompt do shell do modo de manutenção.

.Passos
. Exibir informações sobre todos os adaptadores de rede FC e convergentes no sistema:
+
`system node hardware unified-connect show`

. Compare as configurações FC em node4 com as configurações que você capturou anteriormente de node1.
. Modifique as portas FC no node4 conforme necessário:
+
** Para programar como portas de destino:
+
`ucadmin modify -m fc -t target _adapter_`

+
Por exemplo: `ucadmin modify -m fc -t target 2a`

** Para programar portas do iniciador:
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` É o tipo FC4: Alvo ou iniciador.

+
Por exemplo: `ucadmin modify -m fc -t initator 2b`



. Parar o nó:
+
`halt`

. Inicie o sistema a partir do prompt Loader:
+
`boot_ontap menu`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Selecione a opção `5` no menu de arranque para o modo de manutenção.

