= Verifique e configure as portas UTA/UTA2 no node3
:allow-uri-read: 




== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para verificar a configuração atual da porta:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

As PORTAS UTA/UTA2 podem ser encontradas em um adaptador ou no controlador e têm as seguintes configurações, mas você deve verificar a configuração das portas UTA/UTA2 no node3 e alterá-lo, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

WARNING: *Atenção*: Se o seu sistema tiver discos de armazenamento, você insere os comandos nesta seção no prompt do cluster, a menos que seja direcionado para entrar no modo de manutenção. Se você tiver um sistema da série V ou tiver um software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, digite os comandos nesta seção no prompt do modo de manutenção. Você deve estar no modo Manutenção para configurar portas UTA/UTA2.



.Passos
. [[step1]]Verifique como as portas estão atualmente configuradas inserindo o seguinte comando em node3:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Nenhuma ação necessária. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2]]se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. [[step3]]examine a saída do `ucadmin show` comando e determine se as portas UTA/UTA2 têm a personalidade que você deseja.
. [[step4]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para <<auto_check3_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a Etapa 5 até a Etapa 12 e vá para <<auto_check3_step13,Passo 13>>. 
|===
. [[auto_check3_step5]]execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para <<auto_check3_step7,Passo 7>> 


| Portas UTA/UTA2 integradas | Pule a Etapa 7 e vá para <<auto_check3_step8,Passo 8>>. 
|===
. [[step6]]se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver online, coloque a porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check3_step7]]se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita, sistemas de virtualização FlexArray e configurações MetroCluster. Você deve usar o destino FC para clientes SAN.



. [[auto_check3_step8]]Verifique as definições:
+
`ucadmin show`

. [[step9]]Verifique as definições:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `ucadmin show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[step10]]coloque quaisquer portas de destino online inserindo um dos seguintes comandos, uma vez para cada porta:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `fcp config _adapter_name_ up` 
|===
. [[step11]]Ligue a porta.

