= Saiba mais sobre o licenciamento ONTAP
:allow-uri-read: 




[[learn-about-ontap-licensing]]
== Saiba mais sobre o licenciamento ONTAP

Alguns recursos exigem licenças, que são emitidas como _pacotes_ que incluem um ou mais recursos. Cada nó no cluster deve ter sua própria chave para cada recurso a ser usado no cluster.

Se você não tiver novas chaves de licença, os recursos atualmente licenciados no cluster estarão disponíveis para o novo controlador. No entanto, o uso de recursos não licenciados no controlador pode colocá-lo fora de conformidade com o contrato de licença, portanto, você deve instalar a nova chave de licença ou chaves para o novo controlador após a conclusão da atualização.

Consulte link:other-references.html["Referências"] para acessar o site de suporte da NetApp, onde você pode obter novas chaves de licença de 28 caracteres para ONTAP. As chaves estão disponíveis na seção "Meu Suporte", em "Licenças de Software". Se o site não tiver as chaves de licença de que você precisa, você pode entrar em contato com seu representante de vendas da NetApp.

Para obter informações detalhadas sobre o licenciamento do ONTAP, consulte link:other-references.html["Referências"] para acessar o _System Administration Reference_.
