= Verifique e configure as portas UTA/UTA2 no node4
:allow-uri-read: 




== Verifique e configure as portas UTA/UTA2 no node4

Se o node4 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2A, você deve verificar a configuração das portas e configurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2A. O modo FC suporta o iniciador FC e o destino FC; o modo UTA/UTA2 permite que o tráfego de NIC e FCoE simultâneos compartilhem a mesma interface SFP 10GbE e suporte ao destino FC.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

As PORTAS UTA/UTA2 podem estar em um adaptador ou no controlador com as seguintes configurações:

* Os cartões UTA/UTA2 encomendados ao mesmo tempo que o controlador são configurados antes do envio para ter a personalidade que você solicitou.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novas controladoras são configuradas (antes do envio) para ter a personalidade que você solicitou.


No entanto, você deve verificar a configuração das portas UTA/UTA2 no node4 e alterá-la, se necessário.


WARNING: Insira os comandos desta seção no prompt do shell do modo de manutenção.

.Passos
. Verifique como as portas estão configuradas atualmente no node4:
+
`system node hardware unified-connect show`

+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. Verifique as configurações:
+
`ucadmin show`

+
Examine a saída do `ucadmin show` comando e determine se as portas UTA/UTA2 têm a personalidade desejada.

+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas CNA... | Então... 


| Não tenha a personalidade que você quer | Vá para <<auto_check_4_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a etapa 5 até a etapa 9 e vá para<<auto_check_4_step10,Passo 10>> . 
|===
. [[auto_check_4_step5]]execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para<<auto_check_4_step6,Passo 6>> 


| Portas UTA/UTA2 integradas | Pule a etapa 6 e vá para<<auto_check_4_step7,Passo 7>> . 
|===
. [[auto_check_4_step6]]Se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver on-line, coloque a porta UTA/UTA2 off-line:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check_4_step7]]se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` É o modo personalidade, FC ou 10GbE UTA.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita e configurações do MetroCluster .  Você deve usar o destino FC para clientes SAN.



. Coloque todas as portas de destino on-line inserindo o seguinte comando, uma vez para cada porta:
+
`storage enable adapter <adapter_name>`

. Faça o cabo da porta.

