= 
:allow-uri-read: 



NOTE: O proprietário da casa para os agregados e LIFs não é modificado; apenas o proprietário atual é modificado.

.Passos
. Retomar as operações de transferência agregada e migração de LIF de dados nas:
+
`system controller replace resume`

+
Todos os agregados não-raiz e LIFs de dados nas são migrados de node1 para node2.

+
A operação é interrompida para permitir que você verifique se todos os node1 agregados não-raiz e LIFs de dados não-SAN foram migrados para o node2.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
`system controller replace show-details`

. Com a operação ainda em pausa, verifique se todos os agregados não-raiz estão online para o seu estado em node2:
+
`storage aggregate show -node <node2> -state online -root false`

+
O exemplo a seguir mostra que os agregados não-root no node2 estão online:

+
[listing]
----
cluster::> storage aggregate show -node node2 -state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Se os agregados ficaram offline ou se tornaram estrangeiros no node2, coloque-os online usando o seguinte comando no node2, uma vez para cada agregado:

+
`storage aggregate online -aggregate <aggregate_name>`

. Verifique se todos os volumes estão online no node2 usando o seguinte comando no node2 e examinando sua saída:
+
`volume show -node <node2> -state offline`

+
Se algum volume estiver offline no node2, coloque-o online usando o seguinte comando no node2, uma vez para cada volume:

+
`volume online -vserver <vserver_name> -volume <volume_name>`

+
O `vserver_name` a usar com este comando é encontrado na saída do comando anterior `volume show`.


