= 
:allow-uri-read: 


Este documento é escrito com as seguintes premissas:

* O hardware do controlador de substituição é novo e não foi utilizado.
+

WARNING: Os passos necessários para preparar controladores usados com o `wipeconfig` Os comandos não estão incluídos neste procedimento porque este pressupõe que o hardware do controlador de substituição seja novo e não tenha sido usado. Você deve entrar em contato com o suporte técnico se o hardware do controlador de substituição foi usado anteriormente, especialmente se os controladores estavam executando o Data ONTAP no Modo 7.

* Você lê e entende as diretrizes para atualizar o par de nós.
+

WARNING: Não tente limpar o conteúdo da NVRAM .  Se precisar limpar o conteúdo da NVRAM, entre em contato com o suporte técnico da NetApp .

* Você está executando o comando apropriado antes e depois dos `modify` comandos e comparando a saída de ambos os comandos `show` para verificar se o `modify` comando foi bem-sucedido.
* Se você tiver uma configuração de SAN, terá LIFs locais e parceiros para cada máquina virtual de storage (SVM) no par de HA. Se você não tiver LIFs locais e de parceiros para cada SVM, adicione o LIF de dados SAN nos nós local e remoto para esse SVM antes de iniciar a atualização.
* Se você tiver conjuntos de portas em uma configuração SAN, deverá ter verificado que cada conjunto de portas vinculadas contém pelo menos um LIF de cada nó no par de HA.


Este procedimento usa o termo _prompt do ambiente de inicialização_ para se referir ao prompt em um nó a partir do qual você pode executar certas tarefas, como reinicializar o nó e imprimir ou definir variáveis ambientais. O prompt às vezes é referido informalmente como o prompt _boot Loader_.

O prompt do ambiente de inicialização é mostrado no exemplo a seguir:

[listing]
----
LOADER>
----