= 
:allow-uri-read: 


Você deve instalar node4 no rack, transferir node2 conexões para node4 e inicializar node4. Você também precisa reatribuir quaisquer peças sobressalentes node2, todos os discos pertencentes à raiz e quaisquer agregados que não sejam raiz que não tenham sido relocados para o node3 anteriormente.

.Sobre esta tarefa
Você deve executar o comando netboot no nó 4 se a versão do ONTAP no nó 4 for diferente da versão do ONTAP no nó 2. Após instalar o node4, inicialize-o a partir da imagem do ONTAP 9 armazenada no servidor web. Em seguida, você poderá baixar os arquivos corretos para o dispositivo de inicialização para inicializações subsequentes do sistema, seguindo as instruções em link:prepare_for_netboot.html["Prepare-se para netboot"]

No entanto, não é necessário executar o netboot no nó 4 se a versão do ONTAP no nó 4 for igual ou posterior à versão do ONTAP no nó 2.

[IMPORTANT]
====
* Para uma atualização do controlador AFF A800 ou AFF C800 , você deve garantir que todas as unidades no chassi estejam firmemente encaixadas no plano médio antes de remover o nó 2. Para mais informações, consulte link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Substitua os módulos do controlador AFF A800 ou AFF C800"].
* Se você estiver atualizando um sistema com discos de armazenamento, deverá concluir toda esta seção e, em seguida, prosseguir para a seção link:set_fc_uta_uta2_config_node4.html["Defina a configuração FC ou UTA/UTA2 em node4"] , inserindo comandos no prompt do cluster.


====
.Passos
. [[man_install4_Step1]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se node4 será em ... | Então... 


| Um chassi separado do node3 | Vá para <<man_install4_Step2,Passo 2>>. 


| O mesmo chassi com node3 | Ignore as etapas 2 e 3 e vá para <<man_install4_Step4,Passo 4>>. 
|===
. [[man_install4_Step2]] Certifique-se de que o node4 tem espaço suficiente em rack.
+
Se o node4 estiver em um chassi separado do node3, você pode colocar o node4 no mesmo local que o node2. Se o node3 e o node4 estiverem no mesmo chassi, o node4 já estará no local apropriado do rack.

. Instale o node4 no rack, seguindo as instruções em _instruções de instalação e configuração_ para o modelo do nó.
. [[man_install4_Step4]]Cabo node4, movendo as conexões de node2 para node4.
+
As referências a seguir ajudam você a fazer conexões de cabos adequadas. Vá para link:other_references.html["Referências"]o link para eles.

+
** _Instruções de instalação e configuração_ para a plataforma node4
** O procedimento apropriado do compartimento de disco
** A documentação _HA PAIR Management_
+
Faça o cabo das seguintes ligações:

** Console (porta de gerenciamento remoto)
** Portas de cluster
** Portas de dados
** Portas de gerenciamento de clusters e nós
** Armazenamento
** Configurações SAN: Portas de switch iSCSI Ethernet e FC


+

NOTE: Não é necessário mover a placa de interconexão/placa FC_VI ou a conexão de cabo de interconexão/FC_VI de node2 GbE para node4 GbE, pois a maioria dos modelos de plataforma tem modelos de placa de interconexão exclusivos.

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se node4 estiver em... | Então... 


| O mesmo chassi que node3 | Vá para <<man_install4_Step8,Passo 8>>. 


| Um chassi separado do node3 | Vá para <<man_install4_Step6,Passo 6>>. 
|===
. [[man_install4_Step6]]Ligue a alimentação para node4 e, em seguida, interrompa a inicialização pressionando Ctrl-C para acessar o prompt do ambiente de inicialização.
+

NOTE: Ao inicializar o node4, você poderá ver a seguinte mensagem:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]se você vir a mensagem de aviso no passo 6, execute as seguintes ações:
+
.. Verifique se há mensagens do console que possam indicar um problema que não seja uma bateria NVRAM fraca e, se necessário, tome qualquer ação corretiva necessária.
.. Deixe a bateria carregar e o processo de arranque terminar.
+

WARNING: *Não anule o atraso.  Não permitir que a bateria carregue pode resultar em perda de dados.*



. [[man_install4_Step8]]No prompt do modo de manutenção, digite o seguinte comando:
+
`halt`

+
O sistema pára no prompt do ambiente de inicialização.

. Configurar o node4 para ONTAP:
+
`set-defaults`


