= Configurar portas FC no node4
:allow-uri-read: 




== Configurar portas FC no node4

Se o node4 tiver portas FC, integradas ou em um adaptador FC, você precisará definir configurações de porta no nó antes de colocá-lo em serviço, pois as portas não estão pré-configuradas. Se as portas não estiverem configuradas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node2 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou um adaptador UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node4>>.


IMPORTANT: Digite os comandos desta seção no prompt do cluster.

.Passos
. Exibir informações sobre todos os adaptadores de rede FC e convergentes no sistema:
+
`system node hardware unified-connect show`

. Compare as configurações de FC nos novos nós com as configurações que você capturou anteriormente do nó original.
. Modifique as portas FC no node4 conforme necessário:
+
** Para programar portas de destino:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Para programar portas do iniciador:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` É o tipo FC4, alvo ou iniciador.



. Verifique as novas configurações inserindo o seguinte comando e examinando a saída:
+
`system node unified-connect show`

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se as configurações de FC padrão nos novos nós forem... | Então... 


| O mesmo que aqueles que você capturou nos nós originais | Vá para<<man_config_4_Step9,Passo 9>> . 


| Diferente dos que você capturou nos nós originais | Vá para<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]Sair do modo de manutenção:
+
`halt`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Inicialize o node4 inserindo o seguinte comando no prompt do ambiente de inicialização:
+
`boot_ontap`

. [[man_config_4_Step9]]Execute uma das seguintes ações:
+
** Vá para <<Verifique e configure as portas UTA/UTA2 no node4>> se o node4 tiver uma placa UTA/UTA2A ou portas integradas UTA/UTA2.
** Ignore a seção e vá para link:map_ports_node2_node4.html["Portas de mapa de node2 a node4"] se node4 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2.



