= 
:allow-uri-read: 


Você deve instalar o node3 no rack, transferir as conexões do node1 para node3, inicializar node3 e instalar o ONTAP. Você também deve reatribuir qualquer um dos discos sobressalentes do node1, todos os discos pertencentes ao volume raiz e quaisquer agregados que não sejam raiz não relocados para o node2 anterior.

.Sobre esta tarefa
Você deve inicializar o node3 pela rede se ele não tiver a mesma versão do ONTAP 9 que está instalada no node1. Depois de instalar o node3, inicialize-o a partir da imagem ONTAP 9 armazenada no servidor web. Em seguida, pode transferir os ficheiros corretos para o dispositivo multimédia de arranque para as subsequentes inicializações do sistema. link:prepare_for_netboot.html["Prepare-se para netboot"]Consulte .

No entanto, você não precisa inicializar o node3 pela rede se ele tiver a mesma versão ou uma versão posterior do ONTAP 9 instalada no node1.

[IMPORTANT]
====
* Para uma atualização do controlador AFF A800 ou AFF C800, você deve garantir que todas as unidades no chassi estejam firmemente encaixadas no plano médio antes de remover o nó 1. Para obter mais informações, link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["Substitua os módulos do controlador AFF A800 ou AFF C800"]consulte .
* Se você estiver atualizando um sistema da série V conetado a storages de armazenamento ou a um sistema com software de virtualização FlexArray conetado a storages de armazenamento, você deve concluir <<man_install3_step1,Passo 1>> o <<man_install3_step5,Passo 5>>, deixe esta seção em <<man_install3_step6,Passo 6>> e siga as instruções no link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurar portas FC no node3"] e link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Verifique e configure as portas UTA/UTA2 no node3"]conforme necessário, inserindo comandos no modo de manutenção. Em seguida, você deve retornar a esta seção e retomar com <<man_install3_step7,Passo 7>>.
* Se você estiver atualizando um sistema com discos de armazenamento, deverá concluir toda esta seção e então ir para link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurar portas FC no node3"] e link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Verifique e configure as portas UTA/UTA2 no node3"] , inserindo comandos no prompt do cluster.


====
.Passos
. [[man_install3_step1]]Certifique-se de que você tem espaço em rack para node3.
+
Se node1 e node2 estivessem em chassi separado, você pode colocar node3 no mesmo local de rack que node1. No entanto, se node1 estava no mesmo chassi com node2, então você deve colocar node3 em seu próprio espaço de rack, de preferência perto do local de node1.

. [[step2]]instale o node3 no rack, seguindo as _instruções de instalação e configuração_ para o modelo do nó.
+

NOTE: Se você estiver atualizando para um sistema com ambos os nós no mesmo chassi, instale node4 no chassi e node3. Se você não fizer isso, quando você inicializar o node3, o nó se comportará como se estivesse em uma configuração de chassi duplo, e quando você inicializar o node4, a interconexão entre os nós não aparecerá.

. [[step3]]Cabo node3, movendo as conexões de node1 para node3.
+
As referências a seguir ajudam você a fazer conexões de cabos adequadas. Vá para link:other_references.html["Referências"]o link para eles.

+
** _Instruções de Instalação e Configuração_ ou _requisitos de Instalação de virtualização FlexArray e Referência_ para a plataforma node3
** O procedimento apropriado do compartimento de disco
** A documentação _HA PAIR Management_


+
Faça o cabo das seguintes ligações:

+
** Console (porta de gerenciamento remoto)
** Portas de cluster
** Portas de dados
** Portas de gerenciamento de clusters e nós
** Armazenamento
** Configurações SAN: Portas de switch iSCSI Ethernet e FC
+

NOTE: Talvez você não precise mover a placa de interconexão ou a conexão do cabo de interconexão de cluster de node1 para node3, pois a maioria dos modelos de plataforma tem um modelo de placa de interconexão exclusivo. Para a configuração MetroCluster, é necessário mover as conexões de cabo FC-VI de node1 para node3. Se o novo host não tiver uma placa FC-VI, talvez seja necessário mover a placa FC-VI.



. [[man_install3_step4]]Ligue a alimentação para node3 e, em seguida, interrompa o processo de inicialização pressionando Ctrl-C no terminal do console para acessar o prompt do ambiente de inicialização.
+
Se você estiver atualizando para um sistema com ambos os nós no mesmo chassi, o node4 também será reinicializado. No entanto, você pode ignorar a inicialização do node4 até mais tarde.

+

NOTE: Ao inicializar o node3, você poderá ver a seguinte mensagem de aviso:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]se você vir a mensagem de aviso no <<man_install3_step4,Passo 4>>, execute as seguintes ações:
+
.. Verifique se há mensagens do console que possam indicar um problema que não seja uma bateria NVRAM fraca e, se necessário, tome as medidas corretivas necessárias.
.. Deixe a bateria carregar e o processo de arranque terminar.
+

NOTE: *Atenção*: Não sobreponha o atraso; a falha em permitir que a bateria carregue pode resultar em perda de dados.



. [[man_install3_step6]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o seu sistema... | Então... 


| Tem discos e nenhum armazenamento de back-end | Pule a Etapa 7 até a Etapa 12 e vá para <<man_install3_step13,Passo 13>>. 


| É um sistema da série V ou um sistema com software de virtualização FlexArray conetado a matrizes de armazenamento  a| 
.. Vá para link:set_fc_uta_uta2_config_node3.html["Defina a configuração FC ou UTA/UTA2 em node3"] e complete as subseções link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurar portas FC no node3"] e link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Verifique e configure as portas UTA/UTA2 no node3"], conforme apropriado para o seu sistema.
.. Retorne a esta seção e conclua as etapas restantes, começando com <<man_install3_step7,Passo 7>>.



IMPORTANT: É necessário reconfigurar portas integradas FC, portas integradas CNA e placas CNA antes de inicializar o ONTAP no sistema ou série V com o software de virtualização FlexArray.

|===
. [[man_install3_step7]]Adicione as portas do iniciador FC do novo nó às zonas do switch.
+
Se o seu sistema tiver uma SAN de fita, você precisará de zoneamento para os iniciadores. Consulte a documentação de matriz de armazenamento e zoneamento para obter instruções.

. [[man_install3_step8]]Adicione as portas do iniciador FC ao storage array como novos hosts, mapeando os LUNs do array para os novos hosts.
+
Consulte a documentação de matriz de armazenamento e zoneamento para obter instruções.

. [[man_install3_step9]] modifique os valores WWPN (World Wide Port Name) no host ou grupos de volume associados aos LUNs de array no storage array.
+
A instalação de um novo módulo de controladora altera os valores WWPN associados a cada porta FC integrada.

. [[man_install3_step10]]se sua configuração usa zoneamento baseado em switch, ajuste o zoneamento para refletir os novos valores WWPN.
. [[man_install3_step11]]Verifique se os LUNs de array estão agora visíveis para node3:
+
`sysconfig -v`

+
O sistema exibe todos os LUNs do array visíveis para cada uma das portas do iniciador de FC. Se os LUNs da matriz não estiverem visíveis, você não poderá reatribuir discos de node1 para node3 posteriormente nesta seção.

. [[man_install3_step12]]pressione Ctrl-C para exibir o menu de inicialização e selecionar o modo de manutenção.
. [[man_install3_step13]]no prompt do modo de manutenção, digite o seguinte comando:
+
`halt`

+
O sistema pára no prompt do ambiente de inicialização.

. [[man_install3_step14]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema para o qual você está atualizando está em um... | Então... 


| Configuração de chassi duplo (com controladores em chassi diferente) | Vá para <<man_install3_step15,Passo 15>>. 


| Configuração de chassi único (com controladores no mesmo chassi)  a| 
.. Mude o cabo da consola de node3 para node4.
.. Ligue a alimentação ao node4 e, em seguida, interrompa o processo de inicialização pressionando Ctrl-C no terminal do console para acessar o prompt do ambiente de inicialização.
+
A energia já deve estar ligada se ambos os controladores estiverem no mesmo chassi.

+

NOTE: Deixe node4 no prompt do ambiente de inicialização; você retornará para node4 em link:install_boot_node4.html["Instale e inicialize node4"].

.. Se vir a mensagem de aviso apresentada em <<man_install3_step4,Passo 4>>, siga as instruções em <<man_install3_step5,Passo 5>>
.. Volte a ligar o cabo da consola de node4 para node3.
.. Vá para <<man_install3_step15,Passo 15>>.


|===
. [[man_install3_step15]]Configurar node3 para ONTAP:
+
`set-defaults`


