= Configurar portas FC no node3
:allow-uri-read: 




== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC adicional, você deverá definir as configurações de porta no nó antes de colocá-lo em serviço, porque as portas não são pré-configuradas quando os sistemas são enviados.  Se você não configurar as portas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]no .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Digite os comandos desta seção no prompt do cluster.

.Passos
. Exibe informações sobre todos os adaptadores de rede FC e convergentes no sistema.
+
`system node hardware unified-connect show`

. Compare as configurações de FC do nó 3 com as configurações que você capturou anteriormente do nó 1.
. [[man_config_3_step3]]Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se as configurações de FC padrão nos novos nós forem... | Então... 


| O mesmo que aqueles que você capturou no node1 | Vá para<<man_config_3_step9,Passo 9>> . 


| Diferente dos que você capturou no node1 | Vá para<<man_config_3_step4,Passo 4>> . 
|===
. [[man_config_3_step4]]Modifique as portas FC no node3 conforme necessário, inserindo um dos seguintes comandos:
+
** Para programar portas de destino:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Para programar portas do iniciador:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` É o tipo FC4: Alvo ou iniciador.



. Verifique as novas configurações inserindo o seguinte comando e examinando a saída:
+
`system node hardware unified-connect show`

. Sair do modo de manutenção:
+
`halt`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Inicialize o node3 no prompt do ambiente de inicialização:
+
`boot_ontap`

. [[man_config_3_step9]]Execute uma das seguintes ações:
+
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, pule <<Verifique e configure as portas UTA/UTA2 no node3>> e vá para link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"].



