---
sidebar: sidebar 
permalink: upgrade-arl-manual/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: Decida se deseja usar o procedimento manual ARL para atualizar controladores de storage em um par de HA com novas controladoras executando o ONTAP 9.7 ou anterior. 
---
= Decida se deve usar o procedimento de realocação agregada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este conteúdo descreve como atualizar as controladoras de storage em um par de HA com novas controladoras enquanto mantém todos os dados e discos existentes. Este é um procedimento complexo que deve ser usado apenas por administradores experientes.

Use este conteúdo nas seguintes circunstâncias:

* Não deseja adicionar as novas controladoras como um novo par de HA ao cluster e migrar os dados usando as movimentações de volume.
* Tem experiência na administração de ONTAP e está confortável com os riscos de trabalhar no modo de privilégio de diagnóstico.
* Você tem um sistema que usa configurações de 4 nós e 8 nós do Fabric MetroCluster executando o ONTAP 9.5 ou anterior.



NOTE: Você pode usar criptografia de storage NetApp (NSE), criptografia de volume NetApp (NVE) e criptografia de agregado NetApp (NAE) com este procedimento.

Se você preferir um método diferente de atualizar o hardware do controlador e estiver disposto a fazer movimentos de volume, consulte link:other_references.html["Referências"]o link para _Upgrade movendo volumes ou armazenamento_.

Consulte o link:other_references.html["Referências"]link para o _Centro de Documentação do ONTAP 9_, onde você pode acessar a documentação do produto ONTAP 9.
