---
sidebar: sidebar 
permalink: upgrade-arl-manual/map_ports_node2_node4.html 
keywords: map, node2, node4, physical ports, cluster, network, connectivity 
summary: Verifique se as portas físicas no node2 são mapeadas corretamente para o node4 durante uma atualização manual do ARL em controladores que executam o ONTAP 9.7 ou anterior. 
---
= Portas de mapa de node2 a node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você deve garantir que as portas físicas no node2 sejam mapeadas corretamente para as portas físicas no node4, o que permitirá que o node4 se comunique com outros nós no cluster e com a rede após a atualização.

.Antes de começar
Você já deve ter informações sobre as portas nos novos nós, para acessar essas informações, link:other_references.html["Referências"]consulte o link para o _Hardware Universe_. Você usa as informações mais adiante nesta seção.

A configuração de software do node4 deve corresponder à conetividade física do node4 e a conetividade IP deve ser restaurada antes de continuar com a atualização.

.Sobre esta tarefa
As configurações de porta podem variar, dependendo do modelo dos nós. Você deve tornar a porta e a configuração de LIF do nó original compatíveis com a configuração do novo nó. Isso ocorre porque o novo nó replays a mesma configuração quando ele é inicializado, ou seja, quando você inicializar o node4, o Data ONTAP tentará hospedar LIFs nas mesmas portas que foram usadas no node2.

Portanto, se as portas físicas no node2 não forem mapeadas diretamente para as portas físicas no node4, as alterações de configuração de software serão necessárias para restaurar a conetividade de cluster, gerenciamento e rede após a inicialização. Além disso, se as portas de cluster no node2 não forem mapeadas diretamente para as portas de cluster no node4, o node4 poderá não reingressar automaticamente no quórum quando for reinicializado até que uma alteração de configuração de software seja feita para hospedar as LIFs de cluster nas portas físicas corretas.

.Passos
. Registre todas as informações de cabeamento node2 para node2, as portas, domínios de broadcast e IPspaces, nesta tabela:
+
[cols="7*"]
|===
| LIF | Portas de Node2 GbE | Node2 IPspaces | Node2 domínios de broadcast | Portas de Node4 GbE | Node4 IPspaces | Node4 domínios de broadcast 


| Cluster 1 |  |  |  |  |  |  


| Cluster 2 |  |  |  |  |  |  


| Cluster 3 |  |  |  |  |  |  


| Cluster 4 |  |  |  |  |  |  


| Cluster 5 |  |  |  |  |  |  


| Cluster 6 |  |  |  |  |  |  


| Gerenciamento de nós |  |  |  |  |  |  


| Gerenciamento de clusters |  |  |  |  |  |  


| Dados 1 |  |  |  |  |  |  


| Dados 2 |  |  |  |  |  |  


| Dados 3 |  |  |  |  |  |  


| Dados 4 |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| Porta entre clusters |  |  |  |  |  |  
|===
+
Consulte a secção "Recording information" (informações de gravação node2) para obter estas informações.

. Registre todas as informações de cabeamento para node4, portas, domínios de broadcast e IPspaces na tabela anterior usando o mesmo procedimento na link:record_node2_information.html["Registe node2 informações"] seção para obter essas informações.
. Siga estas etapas para verificar se a configuração é um cluster sem switch de dois nós:
+
.. Defina o nível de privilégio como avançado:
.. Verifique se a configuração é um cluster sem switch de dois nós:
+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster: false/true
----
+
O valor deste comando deve corresponder ao estado físico do sistema.

.. Voltar ao nível de privilégios de administração:
+
[listing]
----
cluster::*> set -privilege admin
cluster::>
----


. Obtenha node4 no quórum executando as seguintes etapas:
+
.. Inicialização node4. link:install_boot_node4.html["Instale e inicialize node4"]Consulte para inicializar o nó se você ainda não tiver feito isso.
.. Verifique se as novas portas de cluster estão no domínio de broadcast de cluster:
+
`network port show -node _node_ -port _port_ -fields broadcast-domain` O exemplo a seguir mostra que a porta "e0a" está no domínio Cluster em node4:

+
[listing]
----
cluster::> network port show -node node4 -port e0a -fields broadcast-domain

node       port broadcast-domain
---------- ---- ----------------
node4      e1a  Cluster
----
.. Se as portas do cluster não estiverem no domínio de broadcast do cluster, adicione-as com o seguinte comando:
+
`broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports _node:port_`

.. Adicione as portas corretas ao domínio de broadcast de cluster:
+
`network port modify -node -port -ipspace Cluster -mtu 9000`

+
Este exemplo adiciona a porta de cluster "e1b" em node4:

+
`network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000`

+

NOTE: Para uma configuração do MetroCluster, talvez você não consiga alterar o domínio de broadcast de uma porta porque ele está associado a uma porta que hospeda o LIF de um SVM de destino de sincronização e veja erros semelhantes, mas não restritos, aos seguintes:

+
[listing]
----
command failed: This operation is not permitted on a Vserver that is configured as the destination of a MetroCluster Vserver relationship.
----
+
Digite o seguinte comando a partir da SVM de origem de sincronização correspondente no local remoto para realocar o LIF de destino de sincronização para uma porta apropriada:

+
`metrocluster vserver resync -vserver _vserver_name_`

.. Migre as LIFs de cluster para as novas portas, uma vez para cada LIF:
+
`network interface migrate -vserver Cluster -lif _lif_name_ -source-node node4 - destination-node node4 -destination-port _port_name_`

.. Modifique a porta inicial dos LIFs do cluster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Remova as portas antigas do domínio de broadcast de cluster:
+
`network port broadcast-domain remove-ports`

+
Este comando remove a porta "e0d" em node4:
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports node4:e0d`

.. Verifique se o node4 se juntou novamente ao quórum:
+
`cluster show -node node4 -fields health`



. [[man_map_2_step5]]Ajuste os domínios de broadcast que hospedam seus LIFs de cluster e LIFs de gerenciamento de nó/cluster. Confirme se cada domínio de broadcast contém as portas corretas. Uma porta não pode ser movida entre domínios de broadcast se estiver hospedando ou estiver hospedando um LIF, então você pode precisar migrar e modificar os LIFs conforme mostrado nas etapas a seguir:
+
.. Apresentar a porta inicial de um LIF:
+
`network interface show -fields home-node,home-port`

.. Exiba o domínio de broadcast que contém esta porta:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Adicionar ou remover portas de domínios de broadcast:
+
`network port broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. Modifique a porta inicial de um LIF:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ –home-port _port_name_`



. Ajuste os domínios de broadcast entre clusters e migre os LIFs entre clusters, se necessário, usando os mesmos comandos mostrados no <<man_map_2_step5,Passo 5>>.
. Ajuste quaisquer outros domínios de broadcast e migre os LIFs de dados, se necessário, usando os mesmos comandos mostrados no <<man_map_2_step5,Passo 5>>.
. Se houver portas no node2 que não existam mais no node4, siga estas etapas para excluí-las:
+
.. Acesse o nível de privilégio avançado em ambos os nós:
+
`set -privilege advanced`

.. Para excluir as portas:
+
`network port delete -node _node_name_ -port _port_name_`

.. Voltar ao nível de administração:
+
`set -privilege admin`



. Ajuste todos os grupos de failover de LIF:
`network interface modify -failover-group _failover_group_ -failover-policy _failover_policy_`
+
O comando a seguir define a política de failover para `broadcast-domain-wide` e usa as portas no grupo de failover como destinos de failover `fg1` para LIF `data1` em `node4`:

+
`network interface modify -vserver node4 -lif data1 failover-policy broadcast-domain-wide -failover-group fg1`

+
Para obter mais informações, link:other_references.html["Referências"]consulte o link para _Gerenciamento de rede_ ou os comandos _ONTAP 9: Referência de página manual_ e vá para _Configuração de configurações de failover em um LIF_.

. Verifique as alterações em node4:
+
`network port show -node node4`

. Cada LIF de cluster deve estar escutando na porta 7700. Verifique se as LIFs do cluster estão escutando na porta 7700:
+
`::> network connections listening show -vserver Cluster`

+
A escuta da porta 7700 nas portas do cluster é o resultado esperado, como mostrado no exemplo a seguir para um cluster de dois nós:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. Para cada LIF de cluster que não está escutando na porta 7700, defina o status administrativo do LIF para `down` e depois `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Repita o passo 11 para verificar se o LIF do cluster está agora a ouvir na porta 7700.


