---
sidebar: sidebar 
permalink: upgrade-arl-manual/relocate_non_root_aggr_node2_node3.html 
keywords: node2, node3, node2, aggregates, autosupport 
summary: Envie uma mensagem AutoSupport para node2 e relocate os agregados não-root do node2 para node3 durante uma atualização manual do ARL em controladores que executam o ONTAP 9.7 ou anterior. 
---
= Realocar agregados não-raiz de node2 para node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de poder substituir node2 por node4, é necessário enviar uma mensagem AutoSupport para node2 e, em seguida, realocar os agregados não-raiz que são de propriedade de node2 para node3.


CAUTION: Durante este procedimento, não relocate agregados de node3 para node2. Isso resulta em agregados ficarem offline e em uma interrupção de dados para os agregados que são relocados.

[[verify-partner-sys-id]]
.Passos
. Verifique se o ID do sistema parceiro está configurado corretamente no nó 3:
+
.. Introduza o nível de privilégio avançado:
+
`set -privilege advanced`

.. Mostrar o ID do sistema do parceiro em node3:
+
`ha interconnect config show -node <node3-node1>`

+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. Se a "ID do sistema de parceiros" estiver incorreta para o node3:
+
.. Paragem node3:
+
`halt`

.. No prompt Loader, defina o valor correto "Partner-sysid".
+
O node3 "Partner-sysid" é a ID do sistema de node2, que você pode encontrar na `ha interconnect config show` saída em <<verify-partner-sys-id,Passo 1>>.

.. Guarde as definições:
+
`saveenv`

.. No prompt DO Loader, inicialize node3 no menu de inicialização:
+
`boot_ontap menu`

.. Inicie sessão em node3.


. Envie uma mensagem AutoSupport para o NetApp para node2:
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. Verifique se a mensagem AutoSupport foi enviada:
+
`system node autosupport show -node <node2> -instance`

+
Os campos "último assunto enviado:" e "último tempo enviado:"" contêm o título da mensagem da última mensagem que foi enviada e a hora em que a mensagem foi enviada.

. [[relocate-step5]]Relocar os agregados não raiz:
+
.. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

.. Liste os agregados que são de propriedade de node2:
+
`storage aggregate show -owner-name <node2>`

.. Iniciar realocação agregada:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: O comando localiza apenas agregados não-raiz.

.. Quando solicitado, digite `y`.
+
A realocação ocorre em segundo plano. Pode levar de alguns segundos a alguns minutos para realocar um agregado. O tempo inclui as partes de interrupção do cliente e não-interrupção. O comando não relocaliza nenhum agregado off-line ou restrito.

.. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`



. Verifique o status de realocação de node2:
+
`storage aggregate relocation show -node <node2>`

+
A saída exibe "Done" para um agregado depois de ter sido relocado.

+

NOTE: Você deve esperar até que todos os agregados que são de propriedade do node2 tenham sido transferidos para o node3 antes de prosseguir para o próximo passo.

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se a relocalização de... | Então... 


| Todos os agregados tiveram sucesso | Vá para <<man_relocate_2_3_step8,Passo 8>>. 


| Todos os agregados falharam ou foram vetados  a| 
.. Apresentar uma mensagem de estado detalhada:
+
`storage aggregate show -instance`

+
Você também pode verificar os logs do EMS para ver a ação corretiva necessária.

+

NOTE: O `event log show` comando lista todos os erros que ocorreram.

.. Execute a ação corretiva.
.. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

.. Relocate quaisquer agregados com falha ou vetado:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. Quando solicitado, digite `y`.
.. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`



Se necessário, você pode forçar a realocação usando um dos seguintes métodos:

** Ao anular verificações de veto:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** Substituindo as verificações de destino:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Para obter mais informações sobre os comandos de realocação de agregados de armazenamento, vá para link:other_references.html["Referências"]vincular a _Disk e gerenciamento de agregados com a CLI_ e os comandos _ONTAP 9: Manual Page Reference_.

|===
. [[man_relocate_2_3_step8]]Verifique se todos os agregados não-root estão online no node3:
+
`storage aggregate show -node <node3> -state offline -root false`

+
Se algum agregado ficou off-line ou se tornou estrangeiro, você deve colocá-lo on-line, uma vez para cada agregado:

+
`storage aggregate online -aggregate <aggregate_name>`

. Verifique se todos os volumes estão online em node3:
+
`volume show -node <node3> -state offline`

+
Se algum volume estiver offline no node3, você deve colocá-lo online, uma vez para cada volume:

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. Verifique se o node2 não possui quaisquer agregados não-raiz online:
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
O comando output não deve exibir agregados on-line não-root porque todos os agregados on-line não-root já foram relocados para node3.


