---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: Configure node3 portas FC integradas, portas UTA/UTA2 ou placa UTA/UTA2 durante uma atualização manual do ARL nas controladoras executando o ONTAP 9.7 ou anterior. 
---
= Defina a configuração FC ou UTA/UTA2 em node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o node3 tiver portas FC integradas, portas de adaptador unificado de destino integrado (UTA/UTA2) ou uma placa UTA/UTA2, você deverá configurar as configurações antes de concluir o restante do procedimento.

.Sobre esta tarefa
Você pode precisar completar<<Configurar portas FC no node3>> ou<<Verifique e configure as portas UTA/UTA2 no node3>> , ou ambas as seções.


NOTE: Os materiais de marketing da NetApp podem usar o termo "UTA2" para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo "CNA".

Se o node3 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2 e você estiver atualizando um sistema com discos de armazenamento, você pode pular paralink:map_ports_node1_node3.html["Portas de mapa de node1 a node3"] .



== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC adicional, você deverá definir as configurações de porta no nó antes de colocá-lo em serviço, porque as portas não são pré-configuradas quando os sistemas são enviados.  Se você não configurar as portas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]no .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Digite os comandos desta seção no prompt do cluster.

.Passos
. Exibe informações sobre todos os adaptadores de rede FC e convergentes no sistema.
+
`system node hardware unified-connect show`

. Compare as configurações de FC do nó 3 com as configurações que você capturou anteriormente do nó 1.
. [[man_config_3_step3]]Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se as configurações de FC padrão nos novos nós forem... | Então... 


| O mesmo que aqueles que você capturou no node1 | Vá para<<man_config_3_step9,Passo 9>> . 


| Diferente dos que você capturou no node1 | Vá para<<man_config_3_step4,Passo 4>> . 
|===
. [[man_config_3_step4]]Modifique as portas FC no node3 conforme necessário, inserindo um dos seguintes comandos:
+
** Para programar portas de destino:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Para programar portas do iniciador:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` É o tipo FC4: Alvo ou iniciador.



. Verifique as novas configurações inserindo o seguinte comando e examinando a saída:
+
`system node hardware unified-connect show`

. Sair do modo de manutenção:
+
`halt`

. Depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Inicialize o node3 no prompt do ambiente de inicialização:
+
`boot_ontap`

. [[man_config_3_step9]]Execute uma das seguintes ações:
+
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, pule <<Verifique e configure as portas UTA/UTA2 no node3>> e vá para link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"].






== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para verificar a configuração atual da porta:

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

As PORTAS UTA/UTA2 podem ser encontradas em um adaptador ou no controlador e têm as seguintes configurações, mas você deve verificar a configuração das portas UTA/UTA2 no node3 e alterá-lo, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

NOTE: Insira os comandos desta seção no prompt do cluster, a menos que seja instruído a entrar no modo de manutenção.



.Passos
. Verifique a configuração atual da porta inserindo o seguinte comando no node3:
+
`system node hardware unified-connect show`

+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[step2]]se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. [[step3]]examine a saída do `system node hardware unified-connect show` comando OR `ucadmin show` para determinar se as portas UTA/UTA2 têm a personalidade que você deseja.
. [[step4]]Faça uma das seguintes ações:
+
[cols="35,65"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para <<man_check_3_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a Etapa 5 até a Etapa 13 e vá para<<man_check_3_step14,Passo 14>> . 
|===
. [[man_check_3_step5]]Se o sistema tiver discos de armazenamento e estiver executando o Data ONTAP 8.3 em cluster, inicialize o node3 e entre no modo de manutenção:
+
`boot_ontap maint`

. Verifique as configurações:
+
`ucadmin show`

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para<<man_check_3_step8,Passo 8>> . 


| Portas UTA/UTA2 integradas | Pule a etapa 8 e vá para<<man_check_3_step9,Passo 9>> . 
|===
. [[man_check_3_step8]]Se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver on-line, coloque a porta UTA/UTA2 off-line:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[man_check_3_step9]]Se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita e configurações do MetroCluster .  Você deve usar o destino FC para clientes SAN.



. Parar o sistema:
+
`halt`

+
O sistema pára no prompt do ambiente de inicialização.

. Introduza o seguinte comando:
+
`boot_ontap`

. [[step11]]Verifique as definições:
+
`system node hardware unified-connect show`

+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]Coloque todas as portas de destino on-line inserindo o seguinte comando, uma vez para cada porta:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_3_step14]]Cabeie a porta.

