---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_3_index.html 
keywords: relocate, retire, node1, steps, stage 3 
summary: Sequência de processo do estágio 3 para uma atualização manual do ARL em controladores que executam o ONTAP 9.7 ou anterior. 
---
= Visão geral da fase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a fase 3, você instala e inicia o node3, mapeia as portas de gerenciamento de clusters e nós de node1 a node3, verifica a instalação do node3 e move LIFs de dados e SAN LIFs pertencentes ao node1 de node2 a node3. Você também realocar todos os agregados de node2 para node3 e mover os LIFs de dados e SAN LIFs de propriedade de node2 para node3.

.Passos
. link:install_boot_node3.html["Instale e inicialize node3"]
. link:set_fc_uta_uta2_config_node3.html["Defina a configuração FC ou UTA/UTA2 em node3"]
. link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"]
. link:verify_node3_installation.html["Verifique a instalação do node3"]
. link:move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html["Mova LIFs de dados nas de propriedade do node1 de node2 para node3 e verifique os LIFs SAN no node3"]
. link:relocate_non_root_aggr_node2_node3.html["Realocar agregados não-raiz de node2 para node3"]
. link:move_nas_lifs_node2_node3.html["Mover LIFs de dados nas de propriedade do node2 para o node3"]

