---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configure e gerencie a criptografia de armazenamento, gerencie chaves de autenticação e quiesce as relações do SnapMirror ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` o comando.' 
---
= Conclua a preparação para a atualização
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre licenciamento ONTAP e gerenciamento de criptografia de armazenamento usando o Onboard Key Manager (OKM). Opcionalmente, suspenda os relacionamentos SnapMirror.



== Saiba mais sobre o licenciamento ONTAP

Alguns recursos exigem licenças, que são emitidas como _pacotes_ que incluem um ou mais recursos. Cada nó no cluster deve ter sua própria chave para cada recurso a ser usado no cluster.

Se você não tiver novas chaves de licença, os recursos atualmente licenciados no cluster estarão disponíveis para o novo controlador. No entanto, o uso de recursos não licenciados no controlador pode colocá-lo fora de conformidade com o contrato de licença, portanto, você deve instalar a nova chave de licença ou chaves para o novo controlador após a conclusão da atualização.

Consulte o link:other_references.html["Referências"]link para o _Site de suporte NetApp_, onde você pode obter novas chaves de licença de 28 carateres para o ONTAP. As chaves estão disponíveis na seção _meu suporte_ em _licenças de software_. Se o site não tiver as chaves de licença necessárias, entre em Contato com o representante de vendas da NetApp.

Para obter informações detalhadas sobre o licenciamento do ONTAP, consulte link:other_references.html["Referências"] para acessar o _System Administration Reference_.



== Gerencie a criptografia de armazenamento usando o Gerenciador de chaves integrado

Utilize o Gerenciador de Chaves Integrado (OKM) para gerenciar as chaves de criptografia. Se o OKM estiver configurado, você deve anotar a senha e o material de backup antes de iniciar a atualização.

.Passos
. Grave a frase-passe de todo o cluster.
+
Esta é a senha que foi inserida quando o OKM foi configurado ou atualizado usando a CLI ou API REST.

. Verifique a senha e a operação do key-manager:
+
`security key-manager onboard sync`

+
Quando solicitado, insira a senha OKM de todo o cluster que você registrou na etapa anterior.

. Verifique se cc-mode está ativado consultando a saída do seguinte comando:
+
`security key-manager config show`

. Faça backup das informações do key-manager:
+
`security key-manager onboard show-backup`





== Opcionalmente, suspenda os SnapMirror relacionamentos

Antes de continuar com o procedimento, você deve confirmar que todas as relações do SnapMirror são silenciadas. Quando um relacionamento do SnapMirror é interrompido, ele permanece quieto em reinicializações e failovers.

.Passos
. Verifique o status da relação do SnapMirror no cluster de destino:
+
`snapmirror show`

+
[NOTE]
====
Se o status for "transferência", você deve cancelar essas transferências:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
A interrupção falha se a relação SnapMirror não estiver no estado "transferindo".

. Quiesce todas as relações entre o cluster:
+
`snapmirror quiesce -destination-vserver *`



.O que se segue?
Após a preparação para a atualização, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Realocar agregados não raiz e LIFs de dados NAS pertencentes ao node1 para o node2"].
