---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Entenda se você pode atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Diretrizes para atualização de controladores com ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para entender se você pode usar o ARL para atualizar um par de controladores executando o ONTAP 9.8 ou posterior depende da plataforma e da configuração dos controladores original e de substituição.



[[supported-upgrades-for-arl]]
== Atualizações suportadas para ARL

Ao atualizar um par de nós usando este procedimento ARL para o ONTAP 9.8 ou posterior, você deve verificar se o ARL pode ser executado nos controladores original e de substituição.

Você deve verificar o tamanho de todos os agregados definidos e o número de discos suportados pelo sistema original. Em seguida, você deve comparar os tamanhos de agregado e o número de discos suportados com o tamanho de agregado e o número de discos suportados pelo novo sistema. Consulte link:other-references.html["Referências"] para acessar o _Hardware Universe_, onde essas informações estão disponíveis. O tamanho de agregado e o número de discos suportados pelo novo sistema devem ser iguais ou maiores que o tamanho de agregado e o número de discos suportados pelo sistema original.

Você deve validar nas regras de mistura de clusters se novos nós podem se integrar ao cluster com os nós existentes quando o controlador original for substituído. Para obter mais informações sobre regras de mistura de clusters, consulte link:other-references.html["Referências"] para acessar o _Hardware Universe_.


NOTE: Se você estiver atualizando um sistema que suporta unidades internas (por exemplo, um FAS2700 ou AFF A250), mas NÃO possui unidades internas, consulte link:other-references.html["Referências"] e utilize o procedimento no conteúdo _Relocação de Agregados para Atualização Manual do Hardware do Controlador_ que seja adequado para a sua versão do ONTAP.

Se você tiver um sistema com mais de duas portas de cluster por nó, como um sistema FAS8080 ou AFF8080, antes de iniciar a atualização, deverá migrar e voltar a home as LIFs de cluster para duas portas de cluster por nó. Se você executar a atualização da controladora com mais de duas portas de cluster por nó, LIFs de cluster podem estar ausentes na nova controladora após a atualização.

A atualização do controlador usando ARL é suportada em sistemas configurados com volumes SnapLock Enterprise e SnapLock Compliance.



[[two-node-switchless-clusters]]
== Clusters sem switch de dois nós

Se você estiver atualizando nós em um cluster sem switch de dois nós, poderá deixar os nós no cluster sem switch durante a atualização. Você não precisa convertê-los em um cluster comutado.



[[upgrades-not-supported-for-arl]]
== Atualizações não suportadas para ARL

Você não pode executar as seguintes atualizações:

* Para substituir as controladoras que não são compatíveis com as gavetas de disco conectadas às controladoras originais
+
Consulte link:other-references.html["Referências"] para acessar o _Hardware Universe_ e obter informações sobre suporte a discos.

* Para controladores de nível básico com acionamentos internos, por exemplo: um FAS2750.
+
Se você deseja atualizar controladores de nível básico com unidades internas, consulte link:other-references.html["Referências"] para acessar _Atualizar movendo volumes ou armazenamento_ e vá para o procedimento _Atualizando um par de nós executando Clustered Data ONTAP movendo volumes_.





[[metrocluster-fc-configuration]]
== Configuração FC do MetroCluster

Em uma configuração MetroCluster FC, você precisa substituir os nós do local de failover/recuperação de desastre o mais rápido possível. A incompatibilidade nos modelos de controladora em um MetroCluster não é suportada porque a incompatibilidade do modelo do controlador pode fazer com que o espelhamento de recuperação de desastres fique offline. Use o `-skip-metrocluster-check true` comando para ignorar as verificações do MetroCluster quando estiver substituindo nós no segundo local.



[[troubleshoot]]
== Solucionar problemas

Você pode encontrar uma falha ao atualizar o par de nós. O nó pode falhar, os agregados podem não ser relocados ou LIFs podem não migrar. A causa da falha e sua solução dependem de quando a falha ocorreu durante o procedimento de atualização.

Caso ocorra algum problema, consulte o link:aggregate_relocation_failures.html["Solucionar problemas"] seção no final do procedimento para mais informações e possíveis soluções. As informações sobre as falhas que podem ocorrer estão listadas por fase do procedimento na seção link:overview_of_the_arl_upgrade.html["Sequência de atualização do ARL"] .

Se você não encontrar uma solução para o problema que encontrou, entre em Contato com o suporte técnico.

.O que se segue?
Após revisar as diretrizes para atualização de controladores com ARL, link:verify_health_of_metrocluster_config.html["verificar a integridade da configuração MetroCluster"].
