---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node3.html 
keywords: installing, booting, node3, ontap 
summary: 'Instale e inicialize o node3 e instale o software ONTAP ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Instale e inicialize node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você deve instalar o node3 no rack, transferir as conexões do node1 para node3, inicializar node3 e instalar o ONTAP. Em seguida, você deve reatribuir qualquer um dos discos sobressalentes do node1, todos os discos pertencentes ao volume raiz e quaisquer agregados não-raiz que não foram relocados para o node2 anteriormente no processo, conforme descrito nesta seção.

.Sobre esta tarefa
A operação de relocalização é interrompida no início desta fase. Esse processo é amplamente automatizado; a operação é interrompida para permitir que você verifique seu status. Tem de retomar manualmente a operação. Além disso, você deve verificar se os LIFs SAN foram movidos com sucesso para node3.

Você precisa netboot node3 se ele não tiver a mesma versão do ONTAP 9 instalada no node1. Depois de instalar o node3, inicialize-o a partir da imagem ONTAP 9 armazenada no servidor web. Em seguida, pode transferir os ficheiros corretos para o dispositivo multimédia de arranque para as subsequentes inicializações do sistema, seguindo as instruções em link:prepare_for_netboot.html["Prepare-se para netboot"].

.Importante:
* Se você estiver atualizando um sistema da série V conetado a matrizes de armazenamento ou um sistema com software de virtualização FlexArray conetado a matrizes de armazenamento, você precisará concluir <<auto_install3_step1,Passo 1>> através <<auto_install3_step21,Passo 21>>do , em seguida, deixe esta seção e siga as instruções nas link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurar portas FC no node3"]seções e link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Verifique e configure as portas UTA/UTA2 no node3"]conforme necessário, inserindo comandos no modo de manutenção. Em seguida, você deve retornar a esta seção e retomar com <<auto_install3_step23,Passo 23>>.
* Se você estiver atualizando um sistema com discos de armazenamento, será necessário concluir toda esta seção e, em seguida, ir para as link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurar portas FC no node3"]seções elink:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Verifique e configure as portas UTA/UTA2 no node3"], digitando comandos no prompt do cluster.


.Passos
. [[auto_install3_step1]]Certifique-se de que você tem espaço em rack para node3.
+
Se node1 e node2 estivessem em chassi separado, você pode colocar node3 no mesmo local de rack que node1. No entanto, se node1 estava no mesmo chassi com node2, então você precisa colocar node3 em seu próprio espaço de rack, de preferência perto do local de node1.

. [[auto_install3_step2]]instale o node3 no rack, seguindo as _instruções de instalação e configuração_ para o modelo do seu nó.
+

NOTE: Se você estiver atualizando para um sistema com ambos os nós no mesmo chassi, instale node4 no chassi e node3. Se você não fizer isso, quando você inicializar o node3, o nó se comportará como se estivesse em uma configuração de chassi duplo, e quando você inicializar o node4, a interconexão entre os nós não aparecerá.

. [[auto_install3_step3]]Cabo node3, movendo as conexões de node1 para node3.
+
Faça o cabeamento das seguintes conexões, usando as _instruções de instalação e configuração_ ou os _requisitos de instalação de virtualização FlexArray e Referência_ para a plataforma node3, o documento apropriado de compartimento de disco e _gerenciamento de pares HA_.

+
Consulte o link:other_references.html["Referências"]link para o _FlexArray requisitos de instalação de virtualização e Referência_ e _gerenciamento de pares HA_.

+
** Console (porta de gerenciamento remoto)
** Portas de cluster
** Portas de dados
** Portas de gerenciamento de clusters e nós
** Armazenamento
** Configurações SAN: Portas de switch iSCSI Ethernet e FC
+

NOTE: Talvez você não precise mover a placa de interconexão ou a conexão do cabo de interconexão de cluster de node1 para node3, pois a maioria dos modelos de plataforma tem um modelo de placa de interconexão exclusivo. Para a configuração MetroCluster, você precisa mover as conexões de cabo FC-VI de node1 para node3. Se o novo host não tiver uma placa FC-VI, talvez seja necessário mover a placa FC-VI.



. [[auto_install3_step4]]Ligue a alimentação para node3 e, em seguida, interrompa o processo de inicialização pressionando Ctrl-C no terminal do console para acessar o prompt do ambiente de inicialização.
+
Se você estiver atualizando para um sistema com ambos os nós no mesmo chassi, o node4 também será reinicializado. No entanto, você pode ignorar a inicialização do node4 até mais tarde.

+

NOTE: Ao inicializar o node3, você poderá ver a seguinte mensagem de aviso:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]se a mensagem de aviso for exibida no <<auto_install3_step4,Passo 4>>, execute as seguintes ações:
+
.. Verifique se há mensagens do console que possam indicar um problema que não seja uma bateria NVRAM fraca e, se necessário, tome as medidas corretivas necessárias.
.. Deixe a bateria carregar e o processo de arranque terminar.
+

WARNING: *Atenção: Não sobreponha o atraso; a falha em permitir que a bateria carregue pode resultar em perda de dados.*

+

NOTE: link:prepare_for_netboot.html["Prepare-se para netboot"]Consulte a .





. [[step6]]Configure a conexão netboot escolhendo uma das seguintes ações.
+

NOTE: Você deve usar a porta de gerenciamento e o IP como conexão netboot. Não use um IP de LIF de dados ou uma interrupção de dados pode ocorrer enquanto a atualização está sendo realizada.

+
[cols="30,70"]
|===
| Se o DHCP (Dynamic Host Configuration Protocol) for... | Então... 


| Em execução | Configure a conexão automaticamente usando o seguinte comando no prompt do ambiente de inicialização:
`ifconfig e0M -auto` 


| Não está a funcionar  a| 
Configure manualmente a conexão usando o seguinte comando no prompt do ambiente de inicialização:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` É o endereço IP do sistema de armazenamento (obrigatório).
`_netmask_` é a máscara de rede do sistema de armazenamento (obrigatório).
`_gateway_` é o gateway para o sistema de armazenamento (obrigatório).
`_dns_addr_` É o endereço IP de um servidor de nomes em sua rede (opcional).
`_dns_domain_` É o nome de domínio do serviço de nomes de domínio (DNS) (opcional).


NOTE: Outros parâmetros podem ser necessários para sua interface. Insira `help ifconfig` no prompt do firmware para obter detalhes.

|===
. [[step7]]execute netboot no node3:
+
[cols="30,70"]
|===
| Para... | Então... 


| Sistemas da série FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Todos os outros sistemas | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
O `<path_to_the_web-accessible_directory>` deve levar ao local onde você baixou o `<ontap_version>_image.tgz` na link:prepare_for_netboot.html["Prepare-se para netboot"]seção .

+

NOTE: Não interrompa a inicialização.

. [[step8]]no menu de inicialização, selecione a opção `(7) Install new software first`.
+
Esta opção de menu transfere e instala a nova imagem ONTAP no dispositivo de arranque.

+
Ignore a seguinte mensagem:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
A observação se aplica a atualizações sem interrupções do ONTAP e não a atualizações de controladores.

+

NOTE: Sempre use netboot para atualizar o novo nó para a imagem desejada. Se você usar outro método para instalar a imagem no novo controlador, a imagem incorreta pode ser instalada. Este problema aplica-se a todas as versões do ONTAP. O procedimento netboot combinado com opção `(7) Install new software` limpa a Mídia de inicialização e coloca a mesma versão do ONTAP em ambas as partições de imagem.

. [[step9]]se você for solicitado a continuar o procedimento, digite `y` e, quando solicitado para o pacote, digite o URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]]conclua as seguintes subetapas para reinicializar o módulo do controlador:
+
.. Introduza `n` para ignorar a recuperação da cópia de segurança quando vir o seguinte aviso:
+
`Do you want to restore the backup configuration now? {y|n}`

.. Digite `y` para reiniciar quando você vir o seguinte prompt:
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
O módulo do controlador reinicializa, mas pára no menu de inicialização porque o dispositivo de inicialização foi reformatado e os dados de configuração devem ser restaurados.



. [[step11]]Selecione o modo de manutenção `5` no menu de inicialização e entre `y` quando você for solicitado a continuar com a inicialização.
. [[step12]]Verifique se o controlador e o chassi estão configurados como ha:
+
`ha-config show`

+
O exemplo a seguir mostra a saída do `ha-config show` comando:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Registros do sistema em uma PROM, quer estejam em um par de HA ou em uma configuração independente. O estado deve ser o mesmo em todos os componentes do sistema autônomo ou do par de HA.

. [[step13]]se o controlador e o chassi não estiverem configurados como ha, use os seguintes comandos para corrigir a configuração:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Se você tiver uma configuração MetroCluster, use os seguintes comandos para modificar o controlador e o chassi:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[step14]]Sair do modo de manutenção:
+
`halt`

+
Interrompa o AUTOBOOT pressionando Ctrl-C no prompt do ambiente de inicialização.

. [[step15]]em node2, verifique a data, hora e fuso horário do sistema:
+
`date`

. [[step16]]em node3, verifique a data usando o seguinte comando no prompt do ambiente de inicialização:
+
`show date`

. [[step17]]se necessário, defina a data em node3:
+
`set date _mm/dd/yyyy_`

. [[step18]]no node3, verifique a hora usando o seguinte comando no prompt do ambiente de inicialização:
+
`show time`

. [[step19]]se necessário, defina a hora em node3:
+
`set time _hh:mm:ss_`

. [[step20]]no boot Loader, defina a ID do sistema do parceiro em node3:
+
`setenv partner-sysid _node2_sysid_`

+
Para node3, `partner-sysid` deve ser o de node2.

+
.. Guarde as definições:
+
`saveenv`



. [[auto_install3_step21]]Verifique o `partner-sysid` para node3:
+
`printenv partner-sysid`

. [[step22]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o seu sistema... | Descrição 


| Tem discos e nenhum armazenamento de back-end | Vá para <<auto_install3_step27,Passo 27>> 


| É um sistema da série V ou um sistema com software de virtualização FlexArray conetado a matrizes de armazenamento  a| 
.. Vá para a seção link:set_fc_or_uta_uta2_config_on_node3.html["Definir a configuração FC ou UTA/UTA2 em node3"] e preencha as subseções nesta seção.
.. Retorne a esta seção e conclua as etapas restantes, começando com <<auto_install3_step23,Passo 23>>.



IMPORTANT: É necessário reconfigurar portas integradas FC, portas integradas CNA e placas CNA antes de inicializar o ONTAP no sistema ou série V com o software de virtualização FlexArray.

|===
. [[auto_install3_step23]]Adicione as portas do iniciador FC do novo nó às zonas do switch.
+
Se o seu sistema tiver uma SAN de fita, você precisará de zoneamento para os iniciadores. Se necessário, modifique as portas integradas para o iniciador consultando o link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configuração de portas FC no node3"]. Consulte a documentação do storage array e zoneamento para obter mais instruções sobre zoneamento.

. [[step24]]Adicione as portas do iniciador FC ao storage array como novos hosts, mapeando os LUNs do array para os novos hosts.
+
Consulte a documentação de matriz de armazenamento e zoneamento para obter instruções.

. [[step25]]modifique os valores WWPN (nome da porta mundial) no host ou grupos de volume associados aos LUNs de array no storage array.
+
A instalação de um novo módulo de controladora altera os valores WWPN associados a cada porta FC integrada.

. [[step26]]se sua configuração usa zoneamento baseado em switch, ajuste o zoneamento para refletir os novos valores WWPN.


[[auto_install3_step27]]
. Se você tiver unidades de criptografia de armazenamento NetApp (NSE) instaladas, execute as seguintes etapas.
+

NOTE: Se ainda não o tiver feito anteriormente no procedimento, consulte o artigo da base de dados de Conhecimento https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Como saber se uma unidade tem certificação FIPS"^] para determinar o tipo de unidades de encriptação automática que estão a ser utilizadas.

+
.. Defina `bootarg.storageencryption.support` para `true` ou `false`:
+
[cols="35,65"]
|===
| Se as seguintes unidades estiverem em uso... | Então... 


| Unidades NSE que estejam em conformidade com os requisitos de autocriptografia FIPS 140-2 nível 2 | `setenv bootarg.storageencryption.support *true*` 


| SEDs não FIPS de NetApp | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Não é possível combinar unidades FIPS com outros tipos de unidades no mesmo nó ou par de HA. É possível misturar SEDs com unidades sem criptografia no mesmo nó ou par de HA.

====
.. Vá para o menu de inicialização especial e selecione opção `(10) Set Onboard Key Manager recovery secrets`.
+
Introduza a frase-passe e as informações de cópia de segurança que registou o procedimento anterior. link:manage_storage_encryption_using_okm.html["Gerencie a criptografia de armazenamento usando o Gerenciador de chaves integrado"]Consulte .



. Inicialize o nó no menu de inicialização:
+
`boot_ontap menu`

+
Se você não tiver uma configuração FC ou UTA/UTA2, execute link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step1["Reatribuir discos node1 a node3, passo 1"] para que o node3 possa reconhecer os discos do node1.

. [[step29]]para uma configuração MetroCluster, sistemas e sistemas da série V com software de virtualização FlexArray conetado a arrays de armazenamento, você deve definir e configurar as portas FC ou UTA/UTA2 no node3 para detetar os discos conetados ao nó. Para concluir esta tarefa, vá para a secção link:set_fc_or_uta_uta2_config_on_node3.html["Defina a configuração FC ou UTA/UTA2 em node3"].

