---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: 'Instale e inicialize o node4 e instale o software ONTAP ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Instale e inicialize node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você deve instalar o node4 no rack, transferir as conexões do node2 para node4, inicializar node4 e instalar o ONTAP. Em seguida, você deve reatribuir qualquer um dos discos sobressalentes do node2, todos os discos pertencentes ao volume raiz e quaisquer agregados não-raiz que não foram relocados para o node3 anteriormente no processo, conforme descrito nesta seção.

.Sobre esta tarefa
A operação de relocalização é interrompida no início desta fase. Este processo é principalmente automatizado; a operação é interrompida para permitir que você verifique seu status. Tem de retomar manualmente a operação.

Você precisa netboot node4 se ele não tiver a mesma versão do ONTAP 9 instalada no node2. Depois de instalar o node4, inicialize-o a partir da imagem ONTAP 9 armazenada no servidor web. Em seguida, pode transferir os ficheiros corretos para o dispositivo multimédia de arranque para as subsequentes inicializações do sistema, seguindo as instruções em link:prepare_for_netboot.html["Prepare-se para netboot"].

.Importante:
* Se você estiver atualizando um sistema da série V conetado a matrizes de armazenamento ou um sistema com software de virtualização FlexArray conetado a matrizes de armazenamento, você deve concluir <<auto_install4_step1,Passo 1>> através <<auto_install4_step21,Passo 21>>do , em seguida, deixar esta seção e seguir as instruções para link:set_fc_or_uta_uta2_config_node4.html#configure-fc-ports-on-node4["Configurar portas FC no node4"] e para link:set_fc_or_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["Verifique e configure as portas UTA/UTA2 no node4"], inserindo comandos no modo de manutenção. Em seguida, você deve retornar a esta seção e retomar com <<auto_install4_step23,Passo 23>>.
* No entanto, se você estiver atualizando um sistema com discos de armazenamento, deve concluir toda esta seção e, em seguida, prosseguir para link:set_fc_or_uta_uta2_config_node4.html["Defina a configuração FC ou UTA/UTA2 em node4"], inserindo comandos no prompt do cluster.


.Passos
. [[auto_install4_step1]]Certifique-se de que o node4 tem espaço suficiente em rack.
+
Se o node4 estiver em um chassi separado do node2, você pode colocar o node4 no mesmo local que o node3. Se o node2 e o node4 estiverem no mesmo chassi, o node4 já estará no local apropriado do rack.

. Instale o node4 no rack, seguindo as instruções em _instruções de instalação e configuração_ para o modelo do nó.
. Cabo node4, movendo as conexões de node2 para node4.
+
Faça o cabeamento das seguintes conexões, usando as instruções em _instruções de instalação e configuração_ ou os _requisitos de instalação de virtualização FlexArray e Referência_ para a plataforma node4, o documento apropriado de compartimento de disco e _gerenciamento de pares HA_.

+
Consulte o link:other_references.html["Referências"]link para o _FlexArray requisitos de instalação de virtualização e Referência_ e _gerenciamento de pares HA_.

+
** Console (porta de gerenciamento remoto)
** Portas de cluster
** Portas de dados
** Portas de gerenciamento de clusters e nós
** Armazenamento
** Configurações SAN: Portas de switch iSCSI Ethernet e FC
+

NOTE: Talvez você não precise mover a placa de interconexão/placa FC-VI ou a conexão de cabo de interconexão/FC-VI de node2 GbE para node4 GbE, pois a maioria dos modelos de plataforma tem modelos de placa de interconexão exclusivos. Para a configuração MetroCluster, é necessário mover as conexões de cabo FC-VI de node2 para node4. Se o novo host não tiver uma placa FC-VI, talvez seja necessário mover a placa FC-VI.



. Ligue a alimentação ao node4 e, em seguida, interrompa o processo de inicialização pressionando Ctrl-C no terminal do console para acessar o prompt do ambiente de inicialização.
+

NOTE: Ao inicializar o node4, você poderá ver a seguinte mensagem de aviso:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. Se vir a mensagem de aviso no passo 4, execute as seguintes acões:
+
.. Verifique se há mensagens do console que possam indicar um problema que não seja uma bateria NVRAM fraca e, se necessário, tome as medidas corretivas necessárias.
.. Deixe a bateria carregar e o processo de arranque terminar.
+

WARNING: *Atenção: Não sobreponha o atraso; a falha em permitir que a bateria carregue pode resultar em perda de dados.*

+

NOTE: link:prepare_for_netboot.html["Prepare-se para netboot"]Consulte a .





. [[step6]]Configure a conexão netboot escolhendo uma das seguintes ações.
+

NOTE: Você deve usar a porta de gerenciamento e o IP como conexão netboot. Não use um IP de LIF de dados ou uma interrupção de dados pode ocorrer enquanto a atualização está sendo realizada.

+
[cols="30,70"]
|===
| Se o DHCP (Dynamic Host Configuration Protocol) for... | Então... 


| Em execução | Configure a conexão automaticamente usando o seguinte comando no prompt do ambiente de inicialização: 
`ifconfig e0M -auto` 


| Não está a funcionar  a| 
Configure manualmente a conexão inserindo o seguinte comando no prompt do ambiente de inicialização:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` É o endereço IP do sistema de armazenamento (obrigatório).
`_netmask_` é a máscara de rede do sistema de armazenamento (obrigatório).
`_gateway_` é o gateway para o sistema de armazenamento (obrigatório).
`_dns_addr_` É o endereço IP de um servidor de nomes em sua rede (opcional).
`_dns_domain_` É o nome de domínio DNS (opcional).


NOTE: Outros parâmetros podem ser necessários para sua interface. Insira `help ifconfig` no prompt do firmware para obter detalhes.

|===
. Execute netboot no node4:
+
[cols="30,70"]
|===
| Para... | Então... 


| Sistemas da série FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Todos os outros sistemas | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
O `<path_to_the_web-accessible_directory>` deve levar ao local onde você baixou o `<ontap_version>_image.tgz` na Etapa 1 na link:prepare_for_netboot.html["Prepare-se para netboot"]seção .

+

NOTE: Não interrompa a inicialização.

. No menu de inicialização, selecione a opção `(7) Install new software first`.
+
Esta opção de menu transfere e instala a nova imagem ONTAP no dispositivo de arranque.

+
Ignore a seguinte mensagem:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
A observação se aplica a atualizações sem interrupções do ONTAP e não a atualizações de controladores.

+

NOTE: Sempre use netboot para atualizar o novo nó para a imagem desejada. Se você usar outro método para instalar a imagem no novo controlador, a imagem incorreta pode ser instalada. Este problema aplica-se a todas as versões do ONTAP. O procedimento netboot combinado com opção `(7) Install new software` limpa a Mídia de inicialização e coloca a mesma versão do ONTAP em ambas as partições de imagem.

. Se você for solicitado a continuar o procedimento, digite `y` e, quando solicitado, digite o URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. Conclua as seguintes subetapas para reinicializar o módulo do controlador:
+
.. Introduza `n` para ignorar a recuperação da cópia de segurança quando vir o seguinte aviso:
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. Reinicie entrando `y` quando você vir o seguinte prompt:
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
O módulo do controlador reinicializa, mas pára no menu de inicialização porque o dispositivo de inicialização foi reformatado e os dados de configuração devem ser restaurados.



. Selecione o modo de manutenção `5` no menu de inicialização e entre `y` quando você for solicitado a continuar com a inicialização.
. Verifique se o controlador e o chassi estão configurados como HA:
+
`ha-config show`

+
O exemplo a seguir mostra a saída do `ha-config show` comando:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Registros do sistema em uma PROM, quer estejam em um par de HA ou em uma configuração independente. O estado deve ser o mesmo em todos os componentes do sistema autônomo ou do par de HA.

. Se a controladora e o chassi não estiverem configurados como HA, use os seguintes comandos para corrigir a configuração:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Se você tiver uma configuração MetroCluster, use os seguintes comandos para modificar o controlador e o chassi:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. Sair do modo de manutenção:
+
`halt`

+
Interrompa o AUTOBOOT pressionando Ctrl-C no prompt do ambiente de inicialização.

. [[auto_install4_step15]]no node3, verifique a data, hora e fuso horário do sistema:
+
`date`

. Em node4, verifique a data usando o seguinte comando no prompt do ambiente de inicialização:
+
`show date`

. Se necessário, defina a data em node4:
+
`set date _mm/dd/yyyy_`

. No node4, verifique a hora usando o seguinte comando no prompt do ambiente de inicialização:
+
`show time`

. Se necessário, defina a hora em node4:
+
`set time _hh:mm:ss_`

. No boot Loader, defina o ID do sistema do parceiro em node4:
+
`setenv partner-sysid _node3_sysid_`

+
Para node4, `partner-sysid` deve ser o de node3.

+
Guarde as definições:

+
`saveenv`

. [[auto_install4_step21]] Verifique o `partner-sysid` para node4:
+
`printenv partner-sysid`

. [[step22]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o seu sistema... | Então... 


| Tem discos e nenhum armazenamento de back-end | Vá para <<auto_install4_step27,Passo 27>>. 


| É um sistema da série V ou um sistema com software de virtualização FlexArray conetado a matrizes de armazenamento  a| 
.. Vá para a seção link:set_fc_or_uta_uta2_config_node4.html["Defina a configuração FC ou UTA/UTA2 em node4"] e preencha as subseções nesta seção.
.. Retorne a esta seção e conclua as etapas restantes, começando com <<auto_install4_step23,Passo 23>>.



IMPORTANT: É necessário reconfigurar portas integradas FC, portas integradas CNA e placas CNA antes de inicializar o ONTAP no sistema ou série V com o software de virtualização FlexArray.

|===


. [[auto_install4_step23]]Adicione as portas do iniciador FC do novo nó às zonas do switch.
+
Se o seu sistema tiver uma SAN de fita, você precisará de zoneamento para os iniciadores. Se necessário, modifique as portas integradas para o iniciador consultando o link:set_fc_or_uta_uta2_config_node4.html#configure-fc-ports-on-node4["Configurar portas FC no node4"]. Consulte a documentação do storage array e zoneamento para obter mais instruções sobre zoneamento.

. Adicione as portas do iniciador de FC ao storage array como novos hosts, mapeando as LUNs do array para os novos hosts.
+
Consulte a documentação de matriz de armazenamento e zoneamento para obter instruções.

. Modifique os valores WWPN (nome da porta mundial) no host ou nos grupos de volume associados aos LUNs da matriz de armazenamento.
+
A instalação de um novo módulo de controladora altera os valores WWPN associados a cada porta FC integrada.

. Se sua configuração usar zoneamento baseado em switch, ajuste o zoneamento para refletir os novos valores WWPN.


. [[auto_install4_step27]]se você tiver unidades de criptografia de armazenamento NetApp (NSE) instaladas, execute as seguintes etapas.
+

NOTE: Se ainda não o tiver feito anteriormente no procedimento, consulte o artigo da base de dados de Conhecimento https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Como saber se uma unidade tem certificação FIPS"^] para determinar o tipo de unidades de encriptação automática que estão a ser utilizadas.

+
.. Defina `bootarg.storageencryption.support` como `true` ou `false`.
+
[cols="35,65"]
|===
| Se as seguintes unidades estiverem em uso... | Então... 


| Unidades NSE que estejam em conformidade com os requisitos de autocriptografia FIPS 140-2 nível 2 | `setenv bootarg.storageencryption.support *true*` 


| SEDs não FIPS de NetApp | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Não é possível combinar unidades FIPS com outros tipos de unidades no mesmo nó ou par de HA. É possível misturar SEDs com unidades sem criptografia no mesmo nó ou par de HA.

====
.. Vá para o menu de inicialização especial e selecione opção `(10) Set Onboard Key Manager recovery secrets`.
+
Introduza a frase-passe e as informações de cópia de segurança que registou o procedimento anterior. link:manage_storage_encryption_using_okm.html["Gerencie a criptografia de armazenamento usando o Gerenciador de chaves integrado"]Consulte .



. Nó de inicialização no menu de inicialização:
+
`boot_ontap menu`

+
Se você não tiver uma configuração FC ou UTA/UTA2, preforme link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step1["Reatribuir discos node2 a node4, passo 1"] para que o node4 possa reconhecer os discos do node2.

. [[step29]]para a configuração do MetroCluster, os sistemas e sistemas da série V com o software de virtualização FlexArray ligados a matrizes de armazenamento, tem de definir e configurar as portas FC ou UTA/UTA2 no node4 para detetar os discos ligados ao nó. Para concluir esta tarefa, vá para a secção link:set_fc_or_uta_uta2_config_node4.html["Defina a configuração FC ou UTA/UT2 em node4"].

