---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/manage-authentication-using-kmip-servers.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configure e gerencie a criptografia de armazenamento, gerencie chaves de autenticação e quiesce as relações do SnapMirror ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` o comando.' 
---
= Gerenciar a autenticação usando servidores KMIP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Com o ONTAP 9.8 ou posterior, você pode usar servidores KMIP (Key Management Interoperability Protocol) para gerenciar chaves de autenticação.

.Passos
. Adicionar um novo controlador:
+
`security key-manager external enable`

. Adicione o gerenciador de chaves:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Verifique se os servidores de gerenciamento de chaves estão configurados e disponíveis para todos os nós no cluster:
+
`security key-manager external show-status`

. Restaure as chaves de autenticação de todos os servidores de gerenciamento de chaves vinculados para o novo nó:
+
`security key-manager external restore -node _new_controller_name_`


