---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'Verifique se LIFs de dados nas do node2 que estão no node3 são relocados de node3 para node4 ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Migre agregados que não sejam raiz e LIFs de dados nas pertencentes ao node2 de node3 para node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Após verificar a configuração de rede no nó 4, você precisa realocar as LIFs de dados NAS pertencentes ao nó 2 do nó 3 para o nó 4 e confirmar se as LIFs SAN existem no nó 4.

.Sobre esta tarefa
As LIFs remotas gerenciam o tráfego para as LUNs SAN durante o procedimento de atualização. A movimentação de LIFs SAN não é necessária para a integridade do cluster ou do serviço durante a atualização. As interfaces LIF da SAN não são movidas a menos que precisem ser mapeadas para novas portas.

Você verifica se as LIFs estão íntegras e localizadas nas portas corretas depois de colocar o nó 4 online.


NOTE: Se você estiver alterando a velocidade da porta das placas de interface de rede Ethernet baseadas em T6 ou das portas da placa-mãe, você pode observar pacotes mal formados sendo recebidos após a conversão de velocidade. Consulte https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp Bugs Online Bug ID 1570339"^] e o artigo da base de conhecimento https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["Erros de CRC em portas T6 após a conversão de 40GbE para 100GbE"^] para obter orientação.

.Passos
. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema executa as seguintes tarefas:

+
** Verificação do quorum do cluster
** Verificação da ID do sistema
** Verificação da versão da imagem
** Verificação da plataforma alvo
** Verificação de acessibilidade da rede


+
O sistema interrompe a operação nesta etapa da verificação de acessibilidade da rede.

. Retomar a operação de realocação:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações:

+
** Verificação de integridade do cluster
** Verificação do status de LIF do cluster


+
Depois de executar essas verificações, o sistema relocaliza os agregados não-raiz e LIFs de dados nas de propriedade do node2 para a nova controladora, node4. A operação de substituição do controlador é interrompida após a conclusão da realocação de recursos.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
[source, cli]
----
system controller replace show-details
----
+
Se o procedimento de substituição do controlador estiver em pausa, verifique e corrija o erro, se houver, e então o problema `resume` para continuar a operação.

. Caso necessário, restaure e reverta as LIFs deslocadas ou migre e modifique manualmente as LIFs do nó 2 que não foram realocadas automaticamente para o nó 4.
+
[role="tabbed-block"]
====
.Restaurar e reverter LIFs deslocados
--
.. Liste quaisquer LIFs deslocados:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Se algum LIFs for deslocado, restaure o nó inicial de volta para node4:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrar e modificar LIFs manualmente
--
.. Migre os LIFs que não foram realocados automaticamente para o nó 4:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. Modifique o nó inicial e a porta inicial para as LIFs migradas:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. Retome a operação para solicitar ao sistema que execute as verificações posteriores necessárias:
+
[source, cli]
----
system controller replace resume
----
+
O sistema efetua as seguintes verificações posteriores:

+
** Verificação do quorum do cluster
** Verificação de integridade do cluster
** Verificação de reconstrução de agregados
** Verificação do status do agregado
** Verificação do estado do disco
** Verificação do status de LIF do cluster
** Verificação do volume



