---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/reassign-node1-disks-to-node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Você precisa reatribuir os discos que pertenciam ao node1 ao node3 ao atualizar controladores executando o ONTAP 9,8 ou posterior usando `system controller replace` comandos.' 
---
= Reatribuir discos node1 a node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você precisa reatribuir os discos que pertenciam ao node1 ao node3 antes de verificar a instalação do node3.

.Passos
. [[reassign-node1-node3-app-step1]]Verifique se o node1 parou no menu de inicialização.  Reatribuir os discos do nó1 ao nó3:
+
`boot_after_controller_replacement`

+
Após um curto atraso, você será solicitado a digitar o nome do nó que está sendo substituído. Se houver discos compartilhados (também chamados de Advanced Disk Partitioning (ADP) ou Partitioned Disks), você será solicitado a digitar o nome do nó do parceiro HA.

+
Esses prompts podem ser enterrados nas mensagens do console. Se não introduzir um nome de nó ou introduzir um nome incorreto, ser-lhe-á pedido que introduza o nome novamente.

+
.Expanda o exemplo de saída do console
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: No exemplo de saída do console acima, o ONTAP solicitará o nome do nó do parceiro se o sistema usar discos de particionamento avançado de disco (ADP).

. Se o sistema entrar em um loop de reinicialização com a mensagem `no disks found` , indica que o sistema redefiniu as portas FC ou UTA/UTA2 de volta ao modo de destino e, portanto, não consegue ver nenhum disco.  Selecione uma das seguintes tarefas para resolver este problema:
+
** Executar<<reassign-node1-node3-app-step3,Passo 3>> para<<reassign-node1-node3-app-step8,Passo 8>> no nó 3
** Ir para a seçãolink:verify_node3_installation.html["Verifique a instalação do node3"]


. [[reassign-node1-node3-app-step3]]pressione Ctrl-C durante o AUTOBOOT para parar o nó no prompt Loader>.
. No prompt Loader, entre no modo de manutenção:
+
`boot_ontap maint`

. No modo de manutenção, exiba todas as portas do iniciador definidas anteriormente que estão agora no modo de destino:
+
`ucadmin show`

+
Altere as portas novamente para o modo iniciador:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. Verifique se as portas foram alteradas para o modo iniciador:
+
`ucadmin show`

. Sair do modo de manutenção:
+
`halt`

+
[NOTE]
====
Se você estiver atualizando de um sistema que suporte discos externos para um sistema que também suporte discos externos, vá para <<reassign-node1-node3-app-step8,Passo 8>>.

Se você estiver atualizando de um sistema que suporte discos externos para um sistema que suporte discos internos e externos, por exemplo, um sistema AFF A800, vá para <<reassign-node1-node3-app-step9,Passo 9>>.

====
. [[reassign-node1-node3-app-step8]]no prompt DO Loader, inicie:
+
`boot_ontap menu`

+
Agora, na inicialização, o nó pode detetar todos os discos que foram atribuídos anteriormente a ele e pode inicializar como esperado.

+
Quando os nós de cluster que você está substituindo usam criptografia de volume raiz, o ONTAP não consegue ler as informações de volume dos discos. Restaure as chaves para o volume raiz.

+

NOTE: Isto aplica-se apenas quando o volume raiz está a utilizar a encriptação de volume NetApp.

+
.. Voltar ao menu de arranque especial:
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Selecione *(10) Definir segredos de recuperação do Onboard Key Manager*
.. Digite `y` no seguinte prompt:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. No prompt, insira a senha do gerenciador de chaves.
.. Insira os dados de backup quando solicitado.
+

NOTE: Tem de ter obtido a frase-passe e os dados de cópia de segurança na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]secção deste procedimento.

.. Depois de o sistema reiniciar para o menu de inicialização especial, execute a opção *(1) normal Boot*
+

NOTE: Você pode encontrar um erro nesta fase. Se ocorrer um erro, repita as subetapas em <<reassign-node1-node3-app-step8,Passo 8>> até que o sistema inicialize normalmente.



. [[reassign-node1-node3-app-step9]]se você estiver atualizando de um sistema com discos externos para um sistema que suporte discos internos e externos (sistemas AFF A800, por exemplo), defina o agregado node1 como o agregado raiz para confirmar que o node3 inicializa a partir do agregado raiz do node1. Para definir o agregado raiz, vá para o menu de inicialização e selecione a opção `5` para entrar no modo de manutenção.
+

CAUTION: *Você deve executar as seguintes subetapas na ordem exata mostrada; a falha em fazê-lo pode causar uma interrupção ou até mesmo perda de dados.*

+
O procedimento a seguir define node3 para inicializar a partir do agregado raiz de node1:

+
.. Entre no modo de manutenção:
+
`boot_ontap maint`

.. Verifique as informações de RAID, Plex e checksum para o agregado node1:
+
`aggr status -r`

.. Verifique o status do agregado node1:
+
`aggr status`

.. Se necessário, coloque o agregado node1 online:
+
`aggr_online root_aggr_from___node1__`

.. Evite que o node3 inicialize a partir do seu agregado raiz original:
+
`aggr offline _root_aggr_on_node3_`

.. Defina o agregado de raiz node1 como o novo agregado de raiz para node3:
+
`aggr options aggr_from___node1__ root`

.. Verifique se o agregado raiz do node3 está offline e o agregado raiz dos discos trazidos do node1 está online e definido como root:
+
`aggr status`

+

NOTE: A falha na execução da subetapa anterior pode fazer com que o node3 seja inicializado a partir do agregado raiz interno, ou pode fazer com que o sistema assuma que existe uma nova configuração de cluster ou peça para que você identifique uma.

+
O seguinte mostra um exemplo da saída do comando:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



