---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/relocate-failed-or-vetoed-aggr-node2.html 
keywords: relocating, failed, vetoed, aggregates, relocation, operation 
summary: 'Realoque manualmente agregados com falha ou vetados para o node2 ao atualizar controladores executando ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Realocar agregados com falha ou vetados para o nó 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se algum agregado não for realocado ou for vetado, você precisará realocá-lo manualmente para o nó 2 ou, se necessário, substituir os vetos ou as verificações de destino.

.Sobre esta tarefa
O sistema pausa a operação de realocação devido ao erro.

.Passos
. Verifique os logs do sistema de gerenciamento de eventos (EMS) para determinar por que o agregado não conseguiu se realocar ou foi vetado.
. Relocate quaisquer agregados com falha ou vetado:
+
`storage aggregate relocation start -node <node1> -destination <node2> -aggregate-list <aggregate_name> -ndo-controller-upgrade true`

. Quando solicitado, digite `y`.
. Você pode forçar a realocação usando um dos seguintes métodos:
+
[cols="35,65"]
|===
| Opção | Descrição 


| Anular verificações de veto | Use o seguinte comando:
`storage aggregate relocation start -node node1 -destination node2 -aggregate-list <aggregate_list> -ndo-controller-upgrade true -override-vetoes true` 


| Anular verificações de destino | Use o seguinte comando:
`storage aggregate relocation start -node node1 -destination node2 -aggregate-list <aggregate_list> -ndo-controller-upgrade true -override-vetoes true -override-destination-checks true` 
|===

