---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/restore_key-manager_configuration_node3.html 
keywords: restoring, key-manager, configuration, node3, nve, arl, encryption, netapp, volume 
summary: 'Se necessário, restaure a configuração do gerenciador de chaves no node3 ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Restaure a configuração do gerenciador de chaves no node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se você estiver usando o NetApp volume Encryption (NVE) e o NetApp Aggregate Encryption (NAE) para criptografar volumes no sistema que você está atualizando, a configuração de criptografia deve ser sincronizada com os novos nós. Se você não sincronizar o gerenciador de chaves, quando você realocar os agregados node1 de node2 para node3 usando ARL, falhas podem ocorrer porque o node3 não tem as chaves de criptografia necessárias para colocar os volumes e agregados criptografados on-line.

.Sobre esta tarefa
Sincronize a configuração de criptografia com os novos nós executando as seguintes etapas:

.Passos
. Executar o seguinte comando a partir de node3:
+
`security key-manager onboard sync`

. Verifique se a chave SVM-KEK foi restaurada para "true" no node3 antes de realocar os agregados de dados:
+
[listing]
----
::> security key-manager key query -node node3 -fields restored -key-type SVM-KEK
----
+
.Exemplo
[listing]
----
::> security key-manager key query -node node3 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node3    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

