---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Configure node3 portas FC integradas, portas UTA/UTA2 ou a placa UTA/UTA2 ao atualizar as controladoras executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Defina a configuração FC ou UTA/UTA2 em node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o node3 tiver portas FC integradas, portas de adaptador unificado de destino integrado (UTA/UTA2) ou uma placa UTA/UTA2, você deverá configurar as configurações antes de concluir o restante do procedimento.

.Sobre esta tarefa
Talvez seja necessário preencher a <<Configurar portas FC no node3>>seção , a <<Verifique e configure as portas UTA/UTA2 no node3>>seção ou ambas as seções.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas de adaptador de rede convergente (CNA). No entanto, a CLI usa o termo CNA.

* Se o node3 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2 e estiver atualizando um sistema com discos de storage, será possível pular para link:reassign-node1-disks-to-node3.html["Reatribuir discos node1 a node3"]o .
* No entanto, se você tiver um sistema V-Series ou um sistema com software de virtualização FlexArray com storage arrays, e o node3 não tiver portas FC integradas, portas UTA/UTA integradas ou uma placa UTA/UTA2, retorne ao _Instalar e inicialize node3_ e continue o procedimento em link:install_boot_node3.html#auto_install3_step23["Passo 23"].




== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC, você precisará definir configurações de porta no nó antes de colocá-lo em serviço, pois as portas não estão pré-configuradas. Se as portas não estiverem configuradas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Se o sistema tiver discos de armazenamento, introduza os comandos nesta secção no prompt do cluster. Se você tiver um 'sistema Série V' ou tiver software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, digite os comandos nesta seção no modo de manutenção.

. [[step1]]Compare as configurações FC no node3 com as configurações que você capturou anteriormente de node1.
. [[step2]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
No modo de manutenção (opção 5 no menu de inicialização), modifique as portas FC no node3 conforme necessário:

** Para programar portas de destino:


`ucadmin modify -m fc -t target _adapter_`

** Para programar portas do iniciador:


`ucadmin modify -m fc -t initiator _adapter_`

`-t` É o tipo FC4: Alvo ou iniciador.



| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
No modo de manutenção (opção 5 no menu de inicialização), modifique as portas FC no node3 conforme necessário:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` É o tipo FC4, alvo ou iniciador.


NOTE: As portas FC devem ser programadas como iniciadores.

|===
. [[step3]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento | Verifique as novas configurações usando o seguinte comando e examinando a saída: 
`ucadmin show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Verifique as novas configurações usando o seguinte comando e examinando a saída: 
`ucadmin show` 
|===
. [[step4]]Sair do modo de manutenção:
+
`halt`

. Inicie o sistema a partir do prompt Loader:
+
`boot_ontap menu`

. [[step6]]depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Selecione a opção `5` no menu de arranque para o modo de manutenção.


. [[auto_check3_step8]]execute uma das seguintes ações:
+
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, ignore _verificar e configurar portas UTA/UTA2 no node3_ e vá para link:reassign-node1-disks-to-node3.html["Reatribuir discos node1 a node3"].




| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, ignore _verificar e configurar portas UTA/UTA2 no node3_ e retorne a _Instalar e inicializar node3_ e continue o procedimento em link:install_boot_node3.html#auto_install3_step23["Passo 23"].


|===




== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para verificar a configuração atual da porta:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

As PORTAS UTA/UTA2 podem ser encontradas em um adaptador ou no controlador e têm as seguintes configurações, mas você deve verificar a configuração das portas UTA/UTA2 no node3 e alterá-lo, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

WARNING: *Atenção*: Se o seu sistema tiver discos de armazenamento, você insere os comandos nesta seção no prompt do cluster, a menos que seja direcionado para entrar no modo de manutenção. Se você tiver um sistema da série V ou tiver um software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, digite os comandos nesta seção no prompt do modo de manutenção. Você deve estar no modo Manutenção para configurar portas UTA/UTA2.



.Passos
. [[step1]]Verifique como as portas estão atualmente configuradas inserindo o seguinte comando em node3:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Nenhuma ação necessária. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2]]se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. [[step3]]examine a saída do `ucadmin show` comando e determine se as portas UTA/UTA2 têm a personalidade que você deseja.
. [[step4]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para <<auto_check3_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a Etapa 5 até a Etapa 12 e vá para <<auto_check3_step13,Passo 13>>. 
|===
. [[auto_check3_step5]]execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para <<auto_check3_step7,Passo 7>> 


| Portas UTA/UTA2 integradas | Pule a Etapa 7 e vá para <<auto_check3_step8,Passo 8>>. 
|===
. [[step6]]se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver online, coloque a porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check3_step7]]se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita, sistemas de virtualização FlexArray e configurações MetroCluster. Você deve usar o destino FC para clientes SAN.



. [[auto_check3_step8]]Verifique as definições:
+
`ucadmin show`

. [[step9]]Verifique as definições:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `ucadmin show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[step10]]coloque quaisquer portas de destino online inserindo um dos seguintes comandos, uma vez para cada porta:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `fcp config _adapter_name_ up` 
|===
. [[step11]]Ligue a porta.


. [[auto_check3_step12]]execute uma das seguintes ações:
+
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Vá para link:reassign-node1-disks-to-node3.html["Reatribuir discos node1 a node3"]. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Retorne a _Install and boot node3_ e retome o procedimento link:install_boot_node3.html#auto_install3_step23["Passo 23"]. 
|===
. [[auto_check3_step13]]Sair do modo de manutenção:
+
`halt`

. [[step14]]Inicialize o nó no menu de inicialização executando `boot_ontap menu`. Se você estiver atualizando para um A800, vá para link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["Reatribuir discos node1 a node3, passo 9"].

