---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Configure node3 portas FC integradas, portas UTA/UTA2 ou a placa UTA/UTA2 ao atualizar as controladoras executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Defina a configuração FC ou UTA/UTA2 em node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o node3 tiver portas FC integradas, portas de adaptador unificado de destino integrado (UTA/UTA2) ou uma placa UTA/UTA2, você deverá configurar as configurações antes de concluir o restante do procedimento.

.Sobre esta tarefa
Talvez seja necessário preencher a <<Configurar portas FC no node3>>seção , a <<Verifique e configure as portas UTA/UTA2 no node3>>seção ou ambas as seções.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas de adaptador de rede convergente (CNA). No entanto, a CLI usa o termo CNA.

* Se o node3 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2 e estiver atualizando um sistema com discos de storage, você poderá pular para a link:verify_node3_installation.html["Verifique a instalação do node3"] seção.
* No entanto, se você tiver um sistema V-Series ou um sistema com software de virtualização FlexArray com storage arrays, e o node3 não tiver portas FC integradas, portas UTA/UTA integradas ou uma placa UTA/UTA2, retorne à seção _Instalar e inicializar node3_ e continue a seção em link:install_boot_node3.html#auto_install3_step23["Passo 23"].


.Opções
* <<Configurar portas FC no node3>>
* <<Verifique e configure as portas UTA/UTA2 no node3>>




== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC, você precisará definir configurações de porta no nó antes de colocá-lo em serviço, pois as portas não estão pré-configuradas. Se as portas não estiverem configuradas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]seção .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Se o sistema tiver discos de armazenamento, introduza os comandos nesta secção no prompt do cluster. Se você tiver um 'sistema Série V' ou tiver software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, digite os comandos nesta seção no modo de manutenção.

. [[step1]]Compare as configurações FC no node3 com as configurações que você capturou anteriormente de node1.
. [[step2]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
No modo de manutenção (opção 5 no menu de inicialização), modifique as portas FC no node3 conforme necessário:

** Para programar portas de destino:


`ucadmin modify -m fc -t target _adapter_`

** Para programar portas do iniciador:


`ucadmin modify -m fc -t initiator _adapter_`

`-t` É o tipo FC4: Alvo ou iniciador.



| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
No modo de manutenção (opção 5 no menu de inicialização), modifique as portas FC no node3 conforme necessário:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` É o tipo FC4, alvo ou iniciador.


NOTE: As portas FC devem ser programadas como iniciadores.

|===
. [[step3]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento | Verifique as novas configurações usando o seguinte comando e examinando a saída: 
`ucadmin show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Verifique as novas configurações usando o seguinte comando e examinando a saída: 
`ucadmin show` 
|===
. [[step4]]Sair do modo de manutenção:
+
`halt`

. Inicie o sistema a partir do prompt Loader:
+
`boot_ontap menu`

. [[step6]]depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. Selecione a opção `5` no menu de arranque para o modo de manutenção.


. [[auto_check3_step8]]execute uma das seguintes ações:
+
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para a seção <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, ignore a seção <<Verifique e configure as portas UTA/UTA2 no node3>> e vá para a link:verify_node3_installation.html["Verifique a instalação do node3"]seção .




| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para a seção <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, ignore a seção <<Verifique e configure as portas UTA/UTA2 no node3>> e retorne à seção _Instalar e inicializar node3_ e continue em link:install_boot_node3.html#auto_install3_step23["Passo 23"].


|===




== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para verificar a configuração atual da porta:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

As PORTAS UTA/UTA2 podem ser encontradas em um adaptador ou no controlador e têm as seguintes configurações, mas você deve verificar a configuração das portas UTA/UTA2 no node3 e alterá-lo, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

WARNING: *Atenção*: Se o seu sistema tiver discos de armazenamento, você insere os comandos nesta seção no prompt do cluster, a menos que seja direcionado para entrar no modo de manutenção. Se você tiver um sistema da série V ou tiver um software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, digite os comandos nesta seção no prompt do modo de manutenção. Você deve estar no modo Manutenção para configurar portas UTA/UTA2.



.Passos
. [[step1]]Verifique como as portas estão atualmente configuradas inserindo o seguinte comando em node3:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Nenhuma ação necessária. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
O sistema exibe a saída semelhante ao seguinte exemplo:

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2]]se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. [[step3]]examine a saída do `ucadmin show` comando e determine se as portas UTA/UTA2 têm a personalidade que você deseja.
. [[step4]]Faça uma das seguintes ações:
+
[cols="30,70"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para <<auto_check3_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a Etapa 5 até a Etapa 12 e vá para <<auto_check3_step13,Passo 13>>. 
|===
. [[auto_check3_step5]]execute uma das seguintes ações:
+
[cols="30,70"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para <<auto_check3_step7,Passo 7>> 


| Portas UTA/UTA2 integradas | Pule a Etapa 7 e vá para <<auto_check3_step8,Passo 8>>. 
|===
. [[step6]]se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver online, coloque a porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[auto_check3_step7]]se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você deve usar o iniciador FC para unidades de fita, sistemas de virtualização FlexArray e configurações MetroCluster. Você deve usar o destino FC para clientes SAN.



. [[auto_check3_step8]]Verifique as definições:
+
`ucadmin show`

. [[step9]]Verifique as definições:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `ucadmin show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[step10]]coloque quaisquer portas de destino online inserindo um dos seguintes comandos, uma vez para cada porta:
+
[cols="30,70"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `fcp config _adapter_name_ up` 
|===
. [[step11]]Ligue a porta.


. [[auto_check3_step12]]execute uma das seguintes ações:
+
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Vá para link:verify_node3_installation.html["Verifique a instalação do node3"]. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Retorne à seção _Instalar e inicializar node3_ e continue em link:install_boot_node3.html#auto_install3_step23["Passo 23"]. 
|===
. [[auto_check3_step13]]Sair do modo de manutenção:
+
`halt`

. [[step14]]Inicialize o nó no menu de inicialização executando `boot_ontap menu`. Se você estiver atualizando para um A800, vá para <<auto_check3_step23,Passo 23>>.


. No node3, vá para o menu de inicialização e, usando 22/7, selecione a opção oculta `boot_after_controller_replacement` . No prompt, digite node1 para reatribuir os discos de node1 a node3, conforme o exemplo a seguir.
+
.Expanda o exemplo de saída do console
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: No exemplo de saída do console acima, o ONTAP solicitará o nome do nó do parceiro se o sistema usar discos de particionamento avançado de disco (ADP).

. Se o sistema entrar em um loop de reinicialização com a mensagem `no disks found`, isso indica que o sistema redefiniu as portas FC ou UTA/UTA2 de volta ao modo de destino e, portanto, não consegue ver nenhum disco. Para resolver isso, continue com <<auto_check3_step17,Passo 17>> para <<auto_check3_step22,Passo 22>>ou vá para a seção link:verify_node3_installation.html["Verifique a instalação do node3"].
. [[auto_check3_step17]]pressione Ctrl-C durante o AUTOBOOT para parar o nó no prompt Loader>.
. [[step18]]no prompt DO Loader, entre no modo de manutenção:
+
`boot_ontap maint`

. [[step19]]no modo de manutenção, exiba todas as portas do iniciador definidas anteriormente que estão agora no modo de destino:
+
`ucadmin show`

+
Altere as portas novamente para o modo iniciador:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[step20]]Verifique se as portas foram alteradas para o modo iniciador:
+
`ucadmin show`

. [[step21]]Sair do modo de manutenção:
+
`halt`

+
[NOTE]
====
Se você estiver atualizando de um sistema que suporte discos externos para um sistema que também suporte discos externos, vá para <<auto_check3_step22,Passo 22>>.

Se você estiver atualizando de um sistema que suporte discos externos para um sistema que suporte discos internos e externos, por exemplo, um sistema AFF A800, vá para <<auto_check3_step23,Passo 23>>.

====
. [[auto_check3_step22]]no prompt DO Loader, inicialize:
+
`boot_ontap menu`

+
Agora, na inicialização, o nó pode detetar todos os discos que foram atribuídos anteriormente a ele e pode inicializar como esperado.

+
Quando os nós de cluster que você está substituindo usam criptografia de volume raiz, o ONTAP não consegue ler as informações de volume dos discos. Restaure as chaves para o volume raiz.

+

NOTE: Isto aplica-se apenas quando o volume raiz está a utilizar a encriptação de volume NetApp.

+
.. Voltar ao menu de arranque especial:
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Selecione *(10) Definir segredos de recuperação do Onboard Key Manager*
.. Digite `y` no seguinte prompt:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. No prompt, insira a senha do gerenciador de chaves.
.. Insira os dados de backup quando solicitado.
+

NOTE: Tem de ter obtido a frase-passe e os dados de cópia de segurança na link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]secção deste procedimento.

.. Depois de o sistema reiniciar para o menu de inicialização especial, execute a opção *(1) normal Boot*
+

NOTE: Você pode encontrar um erro nesta fase. Se ocorrer um erro, repita as subetapas em <<auto_check3_step22,Passo 22>> até que o sistema inicialize normalmente.



. [[auto_check3_step23]]se você estiver atualizando de um sistema com discos externos para um sistema que suporta discos internos e externos (sistemas AFF A800, por exemplo), defina o agregado node1 como o agregado raiz para confirmar que o node3 inicializa a partir do agregado raiz de node1. Para definir o agregado raiz, vá para o menu de inicialização e selecione a opção `5` para entrar no modo de manutenção.
+

CAUTION: *Você deve executar as seguintes subetapas na ordem exata mostrada; a falha em fazê-lo pode causar uma interrupção ou até mesmo perda de dados.*

+
O procedimento a seguir define node3 para inicializar a partir do agregado raiz de node1:

+
.. Entre no modo de manutenção:
+
`boot_ontap maint`

.. Verifique as informações de RAID, Plex e checksum para o agregado node1:
+
`aggr status -r`

.. Verifique o status do agregado node1:
+
`aggr status`

.. Se necessário, coloque o agregado node1 online:
+
`aggr_online root_aggr_from___node1__`

.. Evite que o node3 inicialize a partir do seu agregado raiz original:
+
`aggr offline _root_aggr_on_node3_`

.. Defina o agregado de raiz node1 como o novo agregado de raiz para node3:
+
`aggr options aggr_from___node1__ root`

.. Verifique se o agregado raiz do node3 está offline e o agregado raiz dos discos trazidos do node1 está online e definido como root:
+
`aggr status`

+

NOTE: A falha na execução da subetapa anterior pode fazer com que o node3 seja inicializado a partir do agregado raiz interno, ou pode fazer com que o sistema assuma que existe uma nova configuração de cluster ou peça para que você identifique uma.

+
O seguinte mostra um exemplo da saída do comando:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



