---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Sequência de processo do estágio 5 para uma atualização do ARL usando `system controller replace` comandos em controladores que executam o ONTAP 9.8 ou posterior.' 
---
= Visão geral da fase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante o Estágio 5, você instala e inicia o node4, verifique se as portas de gerenciamento de clusters e nós do node2 estão online no node4 e verifique a instalação do node4. Se estiver usando o NVE, você restaurará a configuração do gerenciador de chaves. Se necessário, defina a configuração FC ou UTA/UTA2 em node4. Você também relocaliza node2 LIFs de dados nas e agregados não-raiz de node3 para node4 e verifica se os LIFs SAN existem no node4.

.Passos
. link:install_boot_node4.html["Instale e inicialize node4"]
. link:set_fc_or_uta_uta2_config_node4.html["Defina a configuração FC ou UTA/UTA2 em node4"]
. link:verify_node4_installation.html["Verifique a instalação do node4"]
. link:restore_key-manager_config_node4.html["Restaure a configuração do gerenciador de chaves no node4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Migre agregados que não sejam raiz e LIFs de dados nas pertencentes ao node2 de node3 para node4"]

