---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_2_index.html 
keywords: relocating, retiring, node1, lif, stage 2 
summary: 'Sequência de processo do estágio 2 para uma atualização do ARL usando `system controller replace` comandos em controladores que executam o ONTAP 9.8 ou posterior.' 
---
= Visão geral da fase 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a fase 2, você realocar node1 agregados não-raiz e LIFs de dados nas para node2. Esse processo é amplamente automatizado; a operação é interrompida para permitir que você verifique seu status. Tem de retomar manualmente a operação. Se necessário, você realocar agregados com falha ou vetado. Você também Registra as informações necessárias do node1, aposenta node1 e prepara para netboot node3 e node4 posteriormente no procedimento.

.Passos
. link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Realocar agregados não-raiz e LIFs de dados nas de propriedade do node1 para o node2"]
. link:relocate_failed_or_vetoed_aggr.html["Realocar agregados com falha ou vetado"]
. link:retire_node1.html["Aposentar-se node1"]
. link:prepare_for_netboot.html["Prepare-se para netboot"]

