---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/verify_health_of_metrocluster_config.html 
keywords: verifying, health, metrocluster, configuration, fabric, mcc 
summary: 'Verifique a integridade da configuração do MetroCluster e a operação correta ao atualizar controladores executando o ONTAP 9.8 ou posterior usando `system controller replace` comandos.' 
---
= Verifique a integridade da configuração do MetroCluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de iniciar uma atualização em uma configuração do Fabric MetroCluster, verifique a integridade da configuração do MetroCluster para verificar o funcionamento correto.

.Passos
. Verifique se os componentes do MetroCluster estão em bom estado:
+
`metrocluster check run`

+
....
metrocluster_siteA::*> metrocluster check run
....
+
A operação é executada em segundo plano.

. Após a `metrocluster check run` conclusão da operação, veja os resultados:
+
`metrocluster check show`

+
Após cerca de cinco minutos, são apresentados os seguintes resultados:

+
[listing]
----
metrocluster_siteA::*> metrocluster check show
Last Checked On: 4/7/2019 21:15:05
Component            Result
---------------      -------
nodes                ok
lifs                 ok
config-replication   ok
aggregates           warning
clusters             ok
connections          not-applicable
volumes              ok
7 entries were displayed.
----
. Verificar o estado do funcionamento da verificação do MetroCluster em curso:
+
`metrocluster operation history show -job-id 38`

. Verifique se não há alertas de saúde:
+
`system health alert show`


