---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Decida se deve usar o procedimento ARL que atualiza os modelos de controlador no mesmo chassi. 
---
= Decida se deve usar o procedimento de realocação agregada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este conteúdo descreve como atualizar controladores de storage em um par de HA e, ao mesmo tempo, manter todos os dados e discos existentes. Este é um procedimento complexo que deve ser usado apenas por administradores experientes.



== Suporte para atualizações ARL

Pode utilizar este procedimento nas seguintes circunstâncias:

* A atualização do controlador está listada no link:index.html#supported-systems,["matriz de sistemas suportados"].
* Você verificou com seu representante de vendas da NetApp que recebeu o hardware necessário para a atualização da controladora:
+
** Dois controladores AFF A90, AFF A70 ou AFF C80 e todos os módulos de e/S. O comprimento necessário de 100GbE cabos.
** Dois controladores e módulos de e/S AFF A50, AFF A30, AFF C30 ou AFF C60. Os cabos necessários.
** Controlador ASA A150, AFF A150 ou FAS2820
** Controlador ASA A900, AFF A900 ou FAS9500 e módulos NVRAM e as peças


* Você está executando a versão mínima do ONTAP para sua atualização. Para obter mais informações, link:index.html["Visão geral"]consulte .
* Não deseja adicionar as novas controladoras como um novo par de HA ao cluster e migrar os dados usando as movimentações de volume.
* Tem experiência na administração de ONTAP e está confortável com os riscos de trabalhar no modo de privilégio de diagnóstico.
* Seus sistemas estão executando o ONTAP 9.15.1 ou posterior e estão usando switches Ethernet para se conetar ao storage conetado à Ethernet.




== Não suportado para atualizações ARL

Você não pode usar este procedimento nas seguintes circunstâncias:

* Você está usando o software de virtualização FlexArray no sistema existente que está sendo atualizado.
* Você está atualizando uma configuração IP do MetroCluster.
+
Para atualizar uma configuração IP do MetroCluster, link:other_references.html["Referências"] consulte para vincular ao conteúdo _Atualização e expansão_ do MetroCluster.




NOTE: Você pode usar criptografia de storage NetApp (NSE), criptografia de volume NetApp (NVE) e criptografia de agregado NetApp (NAE) com este procedimento.

Se você preferir um método diferente de atualizar o hardware do controlador e estiver disposto a fazer movimentos de volume, consulte link:other_references.html["Referências"]o link para _Upgrade movendo volumes ou armazenamento_.

Consulte o link:other_references.html["Referências"]link para o _Centro de Documentação do ONTAP 9_, onde você pode acessar a documentação do produto ONTAP 9.
