---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Decida se deve usar o procedimento ARL que atualiza os modelos de controlador no mesmo chassi. 
---
= Decida se deve usar este procedimento de realocação agregada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existem vários métodos de realocação agregada (ARL) para atualizar o hardware do controlador. Este conteúdo descreve como atualizar controladores de armazenamento em um par de HA, convertendo o sistema existente para o sistema de substituição, mantendo o chassi e os discos do sistema existente. Você só deve usar este procedimento complexo se for um administrador ONTAP experiente.

Para ajudar você a decidir se este procedimento ARL é adequado para a atualização de hardware do seu controlador, você deve revisar todas as seguintes circunstâncias para atualizações suportadas e não suportadas.



== Suportado para esta atualização ARL

Você pode usar este procedimento ARL nas seguintes circunstâncias:

* A atualização do seu controlador está listada em <<supported-systems,matriz de sistemas suportados>> .
* Você verificou com seu representante de vendas da NetApp que recebeu o hardware necessário para a atualização da controladora:
+
** Dois controladores AFF A90, AFF A70 ou AFF C80 e todos os módulos de e/S. Os comprimentos necessários de 100GbE cabos.
** Dois controladores e módulos de e/S A50, AFF A30, AFF C30 ou AFF C60 AFF e dois cabos necessários
** Controlador ASA A150, AFF A150 ou FAS2820
** Controlador ASA A900, AFF A900 ou FAS9500 e módulos e peças NVRAM


* Você está executando a versão mínima do ONTAP para sua atualização. Para obter mais informações, consulte o <<supported-systems,combinações de atualização de sistema suportadas>>.
* Tem experiência na administração de ONTAP e está confortável com os riscos de trabalhar no modo de privilégio de diagnóstico.
* Seus sistemas estão executando o ONTAP 9.15.1 ou posterior e estão usando switches Ethernet para se conetar ao storage conetado à Ethernet.



NOTE: Você pode usar criptografia de storage NetApp (NSE), criptografia de volume NetApp (NVE) e criptografia de agregado NetApp (NAE) com este procedimento.



== Não suportado para esta atualização ARL

Você não pode usar este procedimento ARL nas seguintes circunstâncias:

* Você deseja adicionar as novas controladoras como um novo par de HA ao cluster e migrar os dados usando as movimentações de volume.
* Você está atualizando uma configuração IP do MetroCluster.
+
Para atualizar uma configuração IP do MetroCluster, link:other_references.html["Referências"] consulte para vincular ao conteúdo _Atualização e expansão_ do MetroCluster.





== Combinações de atualização de sistema suportadas

A tabela a seguir mostra a matriz de sistemas suportados para executar uma atualização de controlador convertendo o sistema existente no sistema de substituição, mantendo o chassi e os discos do sistema existente.


CAUTION: Este procedimento aplica-se estritamente às seguintes configurações de atualização. Não utilize este procedimento para efetuar uma atualização entre quaisquer outras combinações do sistema. Para todos os outros modelos de controladora, consulte link:other_references.html["Referências"]o link para _usar comandos "System controller replace" para atualizar o hardware do controlador executando o ONTAP 9,8 ou posterior_ e _usando realocação agregada para atualizar manualmente o hardware do controlador executando o ONTAP 9,8 ou posterior_.

[cols="20,20,40"]
|===
| Sistema existente | Sistema de substituição | Versões de ONTAP compatíveis 


| AFF C250 1 | AFF C30, AFF C60 | 9.16.1 


| AFF A250 1 | AFF A30, AFF A50 | 9.16.1 


| AFF C800 1 | AFF C80 | 9.16.1 


| AFF A800 1 | AFF A90 ou AFF A70 | 9.15.1 e mais tarde 


| AFF A220 configurado como um All SAN Array (ASA) | ASA A150 | 9.13.1P1 e posterior 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e posterior 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 e posterior 2



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e posterior 


| FAS2620 | FAS2820  a| 
9.11.1P7 ou versões posteriores de patch (FAS2620) 2

9.13.1 e posterior (FAS2820)



| FAS2720 | FAS2820 | 9.13.1 e mais tarde 


| AFF A700 configurado como um ASA | ASA A900 | 9.13.1P1 e posterior 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 e posterior 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 e posterior 
|===
1. Quando você atualiza para um sistema introduzido no ONTAP 9.15.1 ou posterior, o ONTAP converte a eficiência de storage de todos os volumes thin Provisioning existentes, incluindo aqueles que não usam a eficiência de storage, e aplica os novos recursos de eficiência de storage que utilizam a funcionalidade de descarga de hardware. Este é um processo de fundo automático, sem impactos visível no desempenho do sistema. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Saiba mais"^].

^2^ Os sistemas AFF A200 e FAS2620 não suportam versões do ONTAP posteriores à 9.11.1.

[NOTE]
====
A NetApp recomenda vivamente, sempre que possível, que tenha a mesma versão do ONTAP nos sistemas antigos e de substituição.

As versões mínimas do ONTAP na tabela anterior são obrigatórias. Essas versões do ONTAP têm a versão de firmware do processador de serviço ou do controlador de gerenciamento de placa base (BMC) necessária para suportar a mistura de tipos de controladora em um chassi durante uma atualização.

====


== Escolha um procedimento de atualização de hardware diferente

* link:../upgrade-arl/index.html["Revise os métodos ARL alternativos disponíveis para atualizar o hardware do controlador"].
* Se você preferir um método diferente de atualizar o hardware do controlador e estiver disposto a fazer movimentos de volume, consulte link:other_references.html["Referências"]o link para _Upgrade movendo volumes ou armazenamento_.


.Informações relacionadas
Consulte link:other_references.html["Referências"] para acessar a _Documentação do ONTAP 9_.
