---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Instale os módulos de sistema de substituição no node2 durante uma atualização ARL dos modelos de controladores no mesmo chassi. 
---
= Instale o módulo AFF A30, AFF A50, AFF C30 ou AFF C60 no node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Instale o módulo do controlador de substituição que recebeu para a atualização em node2. O Node2 é o controlador B localizado na metade inferior do chassi quando se olha os controladores pela parte traseira do sistema.

.Passos
. Posicione o sistema de armazenamento nos trilhos no meio do gabinete ou rack de telecomunicações e, em seguida, apoie o sistema de armazenamento a partir da parte inferior e deslize-o para o lugar.
+

NOTE: Não introduza completamente o módulo do controlador no chassis até ser instruído a fazê-lo mais tarde no procedimento.

. Cable as portas de gerenciamento e console para o módulo do controlador node2.
+

NOTE: Como o chassi já está LIGADO, o node2 inicia a inicialização do BIOS seguida pelo AUTOBOOT assim que estiver totalmente encaixado.  Para interromper a inicialização do node2, antes de inserir completamente o módulo controlador no slot, é recomendável conectar os cabos do console serial e de gerenciamento ao módulo controlador node2.

. Com a alavanca do came na posição aberta, empurre firmemente o módulo do controlador até que ele atenda ao plano médio e esteja totalmente assentado. O trinco de bloqueio sobe quando o módulo do controlador está totalmente assente. Feche o manípulo do excêntrico para a posição de bloqueio.
+

NOTE: Para evitar danificar os conetores, não utilize força excessiva ao deslizar o módulo do controlador para o chassis.

. Conecte o console serial assim que o módulo estiver encaixado e esteja pronto para interromper o AUTOBOOT do node2.
. Depois de interromper o AUTOBOOT, o node2 pára no prompt DO Loader. Se você não interromper o AUTOBOOT a tempo e o node2 iniciar a inicialização, aguarde o prompt e pressione Ctrl-C para entrar no menu de inicialização. Após o nó parar no menu de inicialização, use a opção `8` para reinicializar o nó e interromper o AUTOBOOT durante a reinicialização.
. No prompt Loader> de node2, defina as variáveis de ambiente padrão:
+
`set-defaults`

. Salve as configurações de variáveis de ambiente padrão:
+
`saveenv`

. Para configurações sem switch de dois nós, verifique se você possui uma placa X60132A de 4 portas 10/25 GbE no slot 1 do nó 2. A placa X60132A é necessária para a interconexão do cluster durante a atualização.

