---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/manage_storage_encryption_using_okm.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configure e gerencie criptografia de armazenamento, gerencie chaves de autenticação e quiesce as relações SnapMirror ao usar ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Gerencie a criptografia de armazenamento usando o Gerenciador de chaves integrado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar o Onboard Key Manager (OKM) para gerenciar chaves de criptografia. Se você tiver o OKM configurado, você deve Registrar a senha e o material de backup antes de iniciar a atualização.

.Passos
. Grave a frase-passe de todo o cluster.
+
Esta é a senha que foi inserida quando o OKM foi configurado ou atualizado usando a CLI ou API REST.

. Faça backup das informações do gerenciador de chaves executando o `security key-manager onboard show-backup` comando.




== Quiesce as relações SnapMirror (opcional)

Antes de continuar com o procedimento, você deve confirmar que todas as relações do SnapMirror são silenciadas. Quando um relacionamento do SnapMirror é interrompido, ele permanece quieto em reinicializações e failovers.

.Passos
. Verifique o status da relação do SnapMirror no cluster de destino:
+
`snapmirror show`

+
[NOTE]
====
Se o status for "transferência", você deve cancelar essas transferências:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
A interrupção falha se a relação SnapMirror não estiver no estado "transferindo".

. Quiesce todas as relações entre o cluster:
+
`snapmirror quiesce -destination-vserver *`


