---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/netboot_node1.html 
keywords: preparing, prepare, netboot, ontap, node1 
summary: Ao usar o ARL para atualizar modelos de controladora no mesmo chassi, você deve netboot node1 depois de trocar o módulo de sistema de substituição correspondente. 
---
= Netboot node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depois de trocar os módulos do sistema de substituição correspondentes, você deve netboot node1. O termo netboot significa que você está inicializando a partir de uma imagem ONTAP armazenada em um servidor remoto. Ao se preparar para netboot, você adiciona uma cópia da imagem de inicialização do ONTAP 9 a um servidor da Web que o sistema pode acessar.

Não é possível verificar a versão do ONTAP instalada no suporte de arranque do módulo do controlador de substituição, a menos que esteja instalado num chassis e ligado. A versão do ONTAP na Mídia de inicialização do sistema de substituição deve ser igual à versão do ONTAP em execução no sistema antigo que você está atualizando e as imagens de inicialização principal e de backup na Mídia de inicialização devem corresponder. Para verificar a versão mínima suportada do ONTAP para a atualização, link:index.html["Visão geral"]consulte .

Você pode configurar as imagens executando um netboot seguido do `wipeconfig` comando no menu de inicialização. Se o módulo do controlador foi usado anteriormente em outro cluster, o `wipeconfig` comando limpa qualquer configuração residual na Mídia de inicialização.

Você também pode usar a opção de inicialização USB para executar o netboot. Consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_boot_recovery_LOADER_command_for_installing_ONTAP_for_initial_setup_of_a_system["Como usar o comando boot_recovery Loader para instalar o ONTAP para a configuração inicial de um sistema"^].

.Antes de começar
* Verifique se você pode acessar um servidor HTTP com o sistema.
* Baixe os arquivos de sistema necessários para o seu sistema e a versão correta do ONTAP a partir do site de suporte _NetApp_. Consulte o link:other_references.html["Referências"]link para o _Site de suporte da NetApp_.


.Sobre esta tarefa
Você deve netboot os novos controladores se eles não tiverem a mesma versão do ONTAP 9 instalada neles que está instalada nos controladores originais. Depois de instalar cada novo controlador, inicialize o sistema a partir da imagem ONTAP 9 armazenada no servidor Web. Em seguida, pode transferir os ficheiros corretos para o dispositivo multimédia de arranque para as subsequentes inicializações do sistema.

.Passos
. link:other_references.html["Referências"]Consulte o link para o _Site de suporte NetApp_ para fazer o download dos arquivos usados para executar o netboot do sistema.
. [[netboot_node1_step2]]Baixe o software ONTAP apropriado na seção de download do software do site de suporte _NetApp_ e armazene o `<ontap_version>_image.tgz` arquivo em um diretório acessível pela Web.
. Mude para o diretório acessível pela Web e verifique se os arquivos necessários estão disponíveis.
. Sua lista de diretórios deve conter `<ontap_version>_image.tgz`.
. Configure a conexão netboot escolhendo uma das seguintes ações.
+

NOTE: Você deve usar a porta de gerenciamento e o IP como conexão netboot. Não use um IP de LIF de dados ou uma interrupção de dados pode ocorrer enquanto a atualização está sendo realizada.

+
[cols="35,65"]
|===
| Se o DHCP (Dynamic Host Configuration Protocol) for... | Então... 


| Em execução | Configure a conexão automaticamente usando o seguinte comando no prompt do ambiente de inicialização:
`ifconfig e0M -auto` 


| Não está a funcionar  a| 
Configure manualmente a conexão usando o seguinte comando no prompt do ambiente de inicialização:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` É o endereço IP do sistema de armazenamento (obrigatório).
`_netmask_` é a máscara de rede do sistema de armazenamento (obrigatório).
`_gateway_` é o gateway para o sistema de armazenamento (obrigatório).
`_dns_addr_` É o endereço IP de um servidor de nomes em sua rede (opcional).
`_dns_domain_` É o nome de domínio do serviço de nomes de domínio (DNS) (opcional).


NOTE: Outros parâmetros podem ser necessários para sua interface. Insira `help ifconfig` no prompt do firmware para obter detalhes.

|===
. Execute netboot no node1:
+
`netboot \http://<web_server_ip/path_to_web_accessible_directory>/netboot/kernel`

+

NOTE: Não interrompa a inicialização.

. (Apenas atualizações AFF A250 e AFF C250) quando o node1 para o módulo de controlador de substituição está a arrancar, é apresentado o seguinte aviso:
+
[listing]
----
*****************************************************
* WARNING: Partner is not of the same family/model. *
* Mixing is only allowed when upgrading the system. *
* The system will shut down in 24 hours.            *
*****************************************************
Do you want to continue (y/n):
----
+
Resposta `y`.

+
Este aviso é exibido porque a configuração inclui node2 para o controlador existente. Ele é exibido para cada inicialização do sistema até que você atualize node2. Este é o comportamento esperado.

. Aguarde que o node1 em execução no módulo do controlador de substituição inicialize e exiba as opções do menu de inicialização, conforme mostrado abaixo:
+
[listing]
----
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)?
----
. No menu de inicialização, selecione a opção `(7) Install new software first`.
+
Esta opção de menu transfere e instala a nova imagem ONTAP no dispositivo de arranque.

+
Ignore a seguinte mensagem:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Esta nota aplica-se a atualizações de software ONTAP sem interrupções e não atualizações de controladora.

+

NOTE: Sempre use netboot para atualizar o novo nó para a imagem desejada. Se você usar outro método para instalar a imagem no novo controlador, a imagem incorreta pode ser instalada. Este problema aplica-se a todas as versões do ONTAP. O procedimento netboot combinado com opção `(7) Install new software` limpa a Mídia de inicialização e coloca a mesma versão do ONTAP em ambas as partições de imagem.

. Se você for solicitado a continuar o procedimento, digite `y` e, quando solicitado, digite o URL:
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`
+
O `<path_to_the_web-accessible_directory>` deve levar ao local onde você baixou o `<ontap_version>_image.tgz` em <<netboot_node1_step2,Passo 2>>.

. Conclua as seguintes subetapas para reinicializar o módulo do controlador:
+
.. Introduza `n` para ignorar a recuperação da cópia de segurança quando vir o seguinte aviso:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Digite `y` para reiniciar quando você vir o seguinte prompt:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
O módulo do controlador reinicializa, mas pára no menu de inicialização porque o dispositivo de inicialização foi reformatado e os dados de configuração devem ser restaurados.



. No prompt, execute o `wipeconfig` comando para limpar qualquer configuração anterior na Mídia de inicialização:
+
.. Quando vir a mensagem abaixo, responda `yes`:
+
[listing]
----
This will delete critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?:
----
.. O nó reinicializa para terminar o `wipeconfig` e, em seguida, pára no menu de inicialização.


. Selecione a opção `5` para ir para o modo de manutenção a partir do menu de arranque. Responda `yes` aos prompts até que o nó pare no modo de manutenção e no prompt de comando `*>` .
. Verifique se o controlador e o chassis estão configurados como `ha`:
+
`ha-config show`

+
O exemplo a seguir mostra a saída do `ha-config show` comando:

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. Se o controlador e o chassi não estiverem configurados como `ha`, use os seguintes comandos para corrigir a configuração:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

. Verifique as `ha-config` configurações:
+
`ha-config show`

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. Paragem node1:
+
`halt`

+
node1 deve parar no prompt Loader.

. No node2, verifique a data, a hora e o fuso horário do sistema:
+
`date`

. Em node1, verifique a data usando o seguinte comando no prompt do ambiente de inicialização:
+
`show date`

. Se necessário, defina a data em node1:
+
`set date _mm/dd/yyyy_`

+

NOTE: Defina a data UTC correspondente em node1.

. No node1, verifique a hora usando o seguinte comando no prompt do ambiente de inicialização:
+
`show time`

. Se necessário, defina a hora em node1:
+
`set time _hh:mm:ss_`

+

NOTE: Defina a hora UTC correspondente em node1.

. Defina a ID do sistema do parceiro em node1:
+
`setenv partner-sysid _node2_sysid_`

+
Para node1, o `partner-sysid` deve ser o de node2. Você pode obter o ID do sistema node2 a partir da `node show -node _node2_` saída do comando no node2.

+
.. Guarde as definições:
+
`saveenv`



. No node1, no prompt Loader, verifique o `partner-sysid` para node1:
+
`printenv partner-sysid`


