---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/prepare_nodes_for_upgrade.html 
keywords: preparing, prepare, nodes, upgrade, stage 1, prechecks, old, system, chassis, disk, disks 
summary: Prepare os nós e execute uma série de pré-verificações ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Prepare os nós para atualização
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O processo de substituição do controlador começa com uma série de pré-verificações. Você também coleta informações sobre os nós originais para uso posterior no procedimento e, se necessário, determina o tipo de unidades de autocriptografia que estão sendo usadas.

.Passos
. Liste a versão do firmware do processador de serviço (SP) ou do controlador de gerenciamento de placa base (BMC) em execução no controlador antigo:
+
`service-processor show`

+
Verifique se você tem uma versão de firmware SP ou BMC suportada:

+
[cols="30,35,35"]
|===
| Controlador antigo | SP ou BMC | Versão mínima de firmware 


| AFF A800 | BMC | 10,9 


| AFF A220 | BMC | 11.9P1 


| AFF A200 | SP | 5.11P1 


| AFF C190 | BMC | 11.9P1 


| FAS2620 | SP | 5.11P1 


| FAS2720 | BMC | 11.9P1 
|===
. Inicie o processo de substituição do controlador inserindo o seguinte comando no modo de privilégio avançado da linha de comando ONTAP:
+
`set -privilege advanced`

+
`system controller replace start -nodes _node_names_`

+
Você verá uma saída semelhante ao exemplo a seguir. A saída exibe a versão do ONTAP em execução no cluster:

+
....
Warning:
1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedures.

Do you want to continue? {y|n}: y
....
.  `y`Selecione . Você verá a seguinte saída:
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
Durante a fase de pré-verificações, o sistema executa a seguinte lista de verificações em segundo plano.

+
[cols="35,65"]
|===
| Pré-verificação | Descrição 


| Verificação do estado do cluster | Verifica todos os nós no cluster para confirmar se eles estão íntegros. 


| Verificação do estado de realocação de agregados | Verifica se uma realocação agregada já está em andamento. Se outra realocação agregada estiver em andamento, a verificação falhará. 


| Verificação do nome do modelo | Verifica se os modelos de controlador são suportados para este procedimento. Se os modelos não forem suportados, a tarefa falhará. 


| Verificação do Quórum do cluster | Verifica se os nós que estão sendo substituídos estão no quórum. Se os nós não estiverem no quórum, a tarefa falhará. 


| Verificação da versão da imagem | Verifica se os nós que estão sendo substituídos executam a mesma versão do ONTAP. Se as versões da imagem ONTAP forem diferentes, a tarefa falhará. Os novos nós devem ter a mesma versão do ONTAP 9.x instalada neles que está instalada nos nós originais. Se os novos nós tiverem uma versão diferente do ONTAP instalada, você precisará inicializar os novos controladores depois de instalá-los. Para obter instruções sobre como atualizar o ONTAP, consulte link:other_references.html["Referências"]o link para _Atualizar ONTAP_. 


| Verificação do estado HA | Verifica se ambos os nós que estão sendo substituídos estão em uma configuração de par de alta disponibilidade (HA). Se o failover de armazenamento não estiver habilitado para os controladores, a tarefa falhará. 


| Verificação do estado do agregado | Se os nós que estão sendo substituídos possuem agregados para os quais eles não são o proprietário da casa, a tarefa falha. Os nós não devem possuir quaisquer agregados não locais. 


| Verificação do estado do disco | Se algum nó a ser substituído tiver discos em falta ou com falha, a tarefa falhará. Se algum disco estiver faltando, link:other_references.html["Referências"]consulte o link para _Gerenciamento de disco e agregado com a CLI_, _Gerenciamento de armazenamento lógico com a CLI_ e _Gerenciamento de alta disponibilidade_ para configurar o armazenamento para o par de HA. 


| Verificação do estado do LIF de dados | Verifica se algum dos nós que estão sendo substituídos tem LIFs de dados não locais. Os nós não devem conter quaisquer LIFs de dados para os quais eles não são o proprietário da casa. Se um dos nós contiver LIFs de dados não locais, a tarefa falhará. 


| Estado de LIF do cluster | Verifica se as LIFs de cluster estão prontas para ambos os nós. Se as LIFs de cluster estiverem inativas, a tarefa falhará. 


| Verificação do estado ASUP | Se as notificações do AutoSupport não estiverem configuradas, a tarefa falhará. Você deve ativar o AutoSupport antes de iniciar o procedimento de substituição do controlador. 


| Verificação de utilização da CPU | Verifica se a utilização da CPU é superior a 50% para qualquer um dos nós que estão sendo substituídos. Se o uso da CPU for superior a 50% por um período considerável de tempo, a tarefa falhará. 


| Verificação de reconstrução agregada | Verifica se a reconstrução está a ocorrer em quaisquer agregados de dados. Se a reconstrução agregada estiver em andamento, a tarefa falhará. 


| Verificação trabalho afinidade nó | Verifica se algum trabalho de afinidade de nó está em execução. Se os trabalhos de afinidade de nó estiverem em execução, a verificação falhará. 
|===
. Depois que a operação de substituição do controlador é iniciada e as pré-verificações são concluídas, a operação é interrompida, permitindo que você colete informações de saída que talvez você precise mais tarde no processo de atualização do controlador.
. Execute o conjunto de comandos abaixo indicado pelo procedimento de substituição do controlador no console do sistema.
+
Execute os comandos da porta serial conetada a cada nó, execute e salve a saída dos comandos individualmente:

+
** `vserver services name-service dns show`
** `network interface show -curr-node _local_ -role cluster,intercluster,node-mgmt,cluster-mgmt,data`
** `network port show -node _local_ -type physical`
** `service-processor show -node _local_ -instance`
** `network fcp adapter show -node _local_`
** `network port ifgrp show -node _local_`
** `system node show -instance -node _local_`
** `run -node _local_ sysconfig`
** `run -node local sysconfig -ac`
** `run -node local aggr status -r`
** `vol show -fields type`
** `run local aggr options _data_aggregate_name_`
** `vol show -fields type , space-guarantee`
** `storage aggregate show -node _local_`
** `volume show -node _local_`
** `storage array config show -switch _switch_name_`
** `system license show -owner _local_`
** `storage encryption disk show`
** `security key-manager onboard show-backup`
** `security key-manager external show`
** `security key-manager external show-status`
** `network port reachability show -detail -node _local_`
+

NOTE: Se a criptografia de volume NetApp (NVE) ou a criptografia agregada NetApp (NAE) usando o Gerenciador de chaves integrado estiver em uso, mantenha a senha do gerenciador de chaves pronta para concluir a ressincronização do gerenciador de chaves mais tarde no procedimento.



. Se o seu sistema utilizar unidades de encriptação automática, consulte o artigo da base de dados de Conhecimento https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Como saber se uma unidade tem certificação FIPS"^] para determinar o tipo de unidades de encriptação automática que estão a ser utilizadas no par de HA que está a atualizar. O software ONTAP é compatível com dois tipos de unidades com autocriptografia:
+
--
** Unidades SAS ou NVMe com criptografia de storage NetApp (NSE) com certificação FIPS
** Unidades NVMe com autocriptografia (SED) não FIPS


[NOTE]
====
Não é possível combinar unidades FIPS com outros tipos de unidades no mesmo nó ou par de HA.

É possível misturar SEDs com unidades sem criptografia no mesmo nó ou par de HA.

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["Saiba mais sobre unidades com autocriptografia compatíveis"^].

--




== Corrija a propriedade agregada se uma pré-verificação ARL falhar

Se a Verificação de status agregado falhar, você deverá devolver os agregados pertencentes ao nó do parceiro ao nó do proprietário principal e iniciar o processo de pré-verificação novamente.

.Passos
. Devolva os agregados atualmente pertencentes ao nó do parceiro para o nó do proprietário da casa:
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. Verifique se nem o node1 nem o node2 ainda possuem agregados para os quais é o proprietário atual (mas não o proprietário da casa):
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
O exemplo a seguir mostra a saída do comando quando um nó é o proprietário atual e proprietário de agregados:

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== Depois de terminar

Tem de reiniciar o processo de substituição do controlador:

`system controller replace start -nodes _node_names_`



== Licença

Cada nó no cluster deve ter seu próprio arquivo de licença NetApp (NLF).

Se você não tiver um NLF, os recursos atualmente licenciados no cluster estarão disponíveis para o novo controlador. No entanto, o uso de recursos não licenciados no controlador pode colocá-lo fora de conformidade com o seu contrato de licença, portanto, você deve instalar o NLF para o novo controlador após a conclusão da atualização.

Consulte o link:other_references.html["Referências"]link para o _Site de suporte da NetApp_, onde você pode obter seu NLF. Os NLFs estão disponíveis na seção _meu suporte_ em _licenças de software_. Se o local não tiver os NLFs de que você precisa, entre em Contato com seu representante de vendas da NetApp.

Para obter informações detalhadas sobre licenciamento, link:other_references.html["Referências"]consulte o link para a _Referência de Administração do sistema_.
