---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html 
keywords: relocating, non-root, aggregates, nas, data, lif, node1, node2, NVRAM, controller, module, modules 
summary: Mova os agregados não-raiz e LIFs de dados nas de node1 para node2 e restaure os recursos do node1 ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Realocar agregados não-raiz e LIFs de dados nas de propriedade do node1 para o node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de poder substituir o node1 pelos módulos de substituição para a atualização do seu sistema, você deve mover os agregados não-raiz e LIFs de dados nas de node1 para node2 antes de restaurar os recursos do node1 de volta no node1 em execução no sistema de substituição. Esse processo é amplamente automatizado; a operação é interrompida para permitir que você verifique seu status.

.Antes de começar
A operação já deve ser pausada quando você iniciar a tarefa; você deve retomar manualmente a operação.

.Sobre esta tarefa
Os LIFs remotos manipulam o tráfego para LUNs SAN durante o procedimento de atualização. Não é necessário mover SAN LIFs para cluster ou integridade do serviço durante a atualização. Você deve verificar se os LIFs estão saudáveis e localizados nas portas apropriadas depois de colocar o node1 on-line como o sistema de substituição.


NOTE: O proprietário da casa para os agregados e LIFs não é modificado; apenas o proprietário atual é modificado.

.Passos
. Retomar as operações de transferência agregada e migração de LIF de dados nas:
+
`system controller replace resume`

+
Todos os agregados não-raiz e LIFs de dados nas são migrados de node1 para node2.

+
A operação é interrompida para permitir que você verifique se todos os node1 agregados não-raiz e LIFs de dados não-SAN foram migrados para o node2.

. Verifique o status das operações de transferência agregada e movimentação de LIF de dados nas:
+
`system controller replace show-details`

. Com a operação ainda em pausa, verifique se todos os agregados não-raiz estão online para o seu estado em node2:
+
`storage aggregate show -node _node2_ -state online -root false`

+
O exemplo a seguir mostra que os agregados não-root no node2 estão online:

+
[listing]
----
cluster::> storage aggregate show -node node2 -state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Se os agregados ficaram offline ou se tornaram estrangeiros no node2, coloque-os online usando o seguinte comando no node2, uma vez para cada agregado:

+
`storage aggregate online -aggregate _aggr_name_`

. Verifique se todos os volumes estão online no node2 usando o seguinte comando no node2 e examinando sua saída:
+
`volume show -node _node2_ -state offline`

+
Se algum volume estiver offline no node2, coloque-o online usando o seguinte comando no node2, uma vez para cada volume:

+
`volume online -vserver _vserver_name_ -volume _volume_name_`

+
O `_vserver_name_` a usar com este comando é encontrado na saída do comando anterior `volume show`.



. [[step5]]se algum LIFs estiver inativo, defina o status administrativo dos LIFs para `up` usando o seguinte comando, uma vez para cada LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _nodename_ -status-admin up`


