---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_2_index.html 
keywords: upgrade, relocate, retire, replace, netboot, overview, stage 2 
summary: 'Sequência de processo do estágio 2 para uma atualização ARL usando `system controller replace` comandos para atualizar modelos de controladora no mesmo chassi.' 
---
= Visão geral da fase 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a fase 2, você realocar node1 agregados não-raiz e LIFs de dados nas para node2. Esse processo é amplamente automatizado; a operação é interrompida para permitir que você verifique seu status. Tem de retomar manualmente a operação. Se necessário, você realocar agregados com falha ou vetado. Você também grava informações do node1 para uso mais tarde no procedimento e depois troca os módulos de sistema node1 correspondentes, retire node1 e netboot o node1 atualizado.

.Passos
. link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["Realocar agregados não-raiz e LIFs de dados nas de propriedade do node1 para o node2"]
. link:relocate_failed_or_vetoed_aggr.html["Realocar agregados com falha ou vetado"]
. link:retire_node1.html["Aposentar-se node1"]
. link:replace-node1-affa250-affc250.html["Substitua os node1 módulos do sistema"]
. link:netboot_node1.html["Netboot node1"]

