---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_6_index.html 
keywords: upgrade, boot, node2, verify, restore, overview, stage 1 
summary: 'Sequência de processo do estágio 6 para uma atualização ARL usando `system controller replace` comandos para atualizar modelos de controladora no mesmo chassi.' 
---
= Visão geral da fase 6
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a fase 6, você inicializa o node2 com módulos de sistema atualizados e verifica a instalação do node2 atualizado. Se estiver a utilizar o NetApp volume Encryption (NVE), irá restaurar a configuração do gestor de chaves. Você também relocaliza node1 agregados não-raiz e LIFs de dados nas do node1 para o node2 atualizado e verifica se os LIFs SAN existem no node2.

. link:boot_node2_with_a900_controller_and_nvs.html["Arranque node2 com os módulos do sistema de substituição"]
. link:verify_node2_installation.html["Verifique a instalação do node2"]
. link:restore_key_manager_config_node2.html["Restaure a configuração do gerenciador de chaves no node2"]
. link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Migre agregados que não sejam raiz e LIFs de dados nas de volta para node2"]

