---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_3_index.html 
keywords: upgrade, boot, node1, verify, restore, overview, stage 3 
summary: 'Sequência de processo do estágio 3 para uma atualização ARL usando `system controller replace` comandos para atualizar modelos de controladora no mesmo chassi.' 
---
= Visão geral da fase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a fase 3, você coneta as conexões de armazenamento e HA do cluster compartilhado para as prateleiras externas, se houver, inicializa o node1 com os módulos de sistema atualizados e verifica a instalação do node1 atualizado. Se estiver a utilizar o NetApp volume Encryption (NVE), irá restaurar a configuração do gestor de chaves. Você também relocaliza node1 agregados não-raiz e LIFs de dados nas do node2 para o node1 atualizado e verifica se os LIFs SAN existem no node1.

.Passos
. link:cable-node1-for-shared-cluster-HA-storage.html["Cabo node1 para storage compartilhado de cluster-HA (somente atualização AFF A800)"]
. link:boot_node1_with_a900_controller_and_nvs.html["Arranque node1 com os módulos do sistema de substituição"]
. link:verify_node1_installation.html["Verifique a instalação do node1"]
. link:restore_key_manager_config_upgraded_node1.html["Restaure a configuração do gerenciador de chaves no node1 atualizado"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html["Migre node1 agregados não-raiz e LIFs de dados nas de node2 para o node1 atualizado"]

