---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node1_installation.html 
keywords: verifying, verify, node1, install, installation, NVRAM, controller, module, modules 
summary: Verifique a instalação do node1 com os módulos de substituição ao usar o ARL para atualizar modelos de controladora no mesmo chassi. 
---
= Verifique a instalação do node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depois de inicializar o node1 com o módulo do controlador de substituição, verifique se ele está instalado corretamente.

Somente para atualizações do AFF A800, você mapeia as portas físicas do node1 existente para o node1 de substituição porque as portas físicas estão mudando entre o AFF A800 e o controlador AFF A90 ou AFF A70.

Para todas as outras atualizações, não há alteração nas portas físicas, portanto, não é necessário mapear as portas físicas do antigo node1 para o node1 de substituição.

.Sobre esta tarefa
Você deve esperar que o node1 entre no quórum e, em seguida, retomar a operação de substituição do controlador.

Neste ponto do procedimento, a operação de atualização do controlador deve ter pausado como node1 tentativas de juntar quórum automaticamente.

.Passos
. Verifique se o quórum de node1 aderiu:
+
`cluster show -node node1 -fields health`

+
A saída `health` do campo deve ser `true`.

. Verifique se o node1 faz parte do mesmo cluster que o node2 e se está em bom estado:
+
`cluster show`

+
[NOTE]
====
Se o node1 não tiver aderido ao quórum após o arranque, aguarde cinco minutos e volte a verificar. Dependendo da conexão do cluster, pode levar algum tempo para que a verificação de acessibilidade da porta seja concluída e mova LIFs para suas respetivas portas iniciais.

Se o node1 ainda não estiver no quórum após cinco minutos, considere modificar a porta do cluster do novo nó colocando-o em "Cluster ipspace" usando o comando de privilégio de diagnóstico `network port modify <port_name> -ipspace Cluster` .

====
. Mudar para o modo de privilégio avançado:
+
`set advanced`

. Verifique o status da operação de substituição do controlador e verifique se ele está em um estado de pausa e no mesmo estado em que estava antes de node1 ser interrompido para executar as tarefas físicas de instalação de novos controladores e movimentação de cabos:
+
`system controller replace show`

+
`system controller replace show-details`

. Retomar a operação de substituição do controlador:
+
`system controller replace resume`

. A operação de substituição do controlador pausa para a intervenção com a seguinte mensagem:
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node1         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node2         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: Neste procedimento, a seção _recriando VLANs, ifgrps e domínios de broadcast_ foi renomeada como _Restaurar configuração de rede em node1_.

. Com a substituição do controlador em estado de pausa, avance para <<Restaure a configuração de rede no node1>>.




== Restaure a configuração de rede no node1

Depois de confirmar que o node1 está no quórum e pode se comunicar com o node2, verifique se as VLANs, os grupos de interface e os domínios de broadcast do node1 são vistos no node1. Além disso, verifique se todas as portas de rede node1 estão configuradas em seus domínios de broadcast corretos.

.Sobre esta tarefa
Para obter mais informações sobre como criar e recriar VLANs, grupos de interface e domínios de broadcast, link:other_references.html["Referências"]consulte para vincular ao conteúdo _Network Management_.

.Passos
. Liste todas as portas físicas que estão no node1 atualizado:
+
`network port show -node node1`

+
Todas as portas de rede físicas, portas VLAN e portas de grupo de interfaces no nó são exibidas. A partir desta saída, você pode ver quaisquer portas físicas que foram movidas para o `Cluster` domínio de broadcast pelo ONTAP. Você pode usar essa saída para ajudar a decidir quais portas devem ser usadas como portas membros do grupo de interfaces, portas base VLAN ou portas físicas independentes para hospedar LIFs.

. Liste os domínios de broadcast no cluster:
+
`network port broadcast-domain show`

. Listar a acessibilidade da porta de rede de todas as portas no node1:
+
`network port reachability show -node node1`

+
Você deve ver a saída como o exemplo a seguir:

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
Nos exemplos anteriores, o node1 inicializou após a substituição do controlador. As portas que exibem "não-acessibilidade" não têm conetividade física. Você deve reparar quaisquer portas com um status de acessibilidade diferente `ok`de .

+

NOTE: Durante a atualização, as portas de rede e a respetiva conetividade não devem ser alteradas. Todas as portas devem residir nos domínios de broadcast corretos e a acessibilidade da porta de rede não deve ser alterada. No entanto, antes de mover LIFs de node2 para node1, você deve verificar o status de acessibilidade e integridade das portas de rede.

. [[Restore_node1_step4]]repare a acessibilidade para cada uma das portas no node1 com um status de acessibilidade diferente do que `ok` usando o seguinte comando, na seguinte ordem:
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
--
.. Portas físicas
.. Portas VLAN


--
+
Você deve ver a saída como o exemplo a seguir:

+
[listing]
----
Cluster ::> reachability repair -node node1 -port e1b
----
+
[listing]
----
Warning: Repairing port "node1:e1b" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
Uma mensagem de aviso, como mostrado no exemplo anterior, é esperada para portas com um status de acessibilidade que pode ser diferente do status de acessibilidade do domínio de broadcast onde ele está localizado atualmente. Revise a conetividade da porta e da resposta `y` ou `n` conforme apropriado.

+
Verifique se todas as portas físicas têm sua acessibilidade esperada:

+
`network port reachability show`

+
À medida que o reparo de acessibilidade é executado, o ONTAP tenta colocar as portas nos domínios de broadcast corretos. No entanto, se a acessibilidade de uma porta não puder ser determinada e não pertencer a nenhum dos domínios de broadcast existentes, o ONTAP criará novos domínios de broadcast para essas portas.

. Verificar acessibilidade da porta:
+
`network port reachability show`

+
Quando todas as portas estão corretamente configuradas e adicionadas aos domínios de broadcast corretos, o `network port reachability show` comando deve relatar o status de acessibilidade como `ok` para todas as portas conetadas e o status como `no-reachability` para portas sem conetividade física. Se qualquer porta relatar um status diferente desses dois, execute o reparo de acessibilidade e adicione ou remova portas de seus domínios de broadcast, conforme instruções em <<restore_node1_step4,Passo 4>>.

. Verifique se todas as portas foram colocadas em domínios de broadcast:
+
`network port show`

. Verifique se todas as portas nos domínios de broadcast têm a unidade de transmissão máxima (MTU) correta configurada:
+
`network port broadcast-domain show`

. Restaure as portas iniciais do LIF, especificando o SVM e as portas home do LIF, se houver, que precisam ser restauradas usando as seguintes etapas:
+
.. Liste quaisquer LIFs que estão deslocados:
+
`displaced-interface show`

.. Restaure os nós iniciais do LIF e as portas iniciais:
+
`displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. Verifique se todos os LIFs têm uma porta inicial e estão administrativamente ativos:
+
`network interface show -fields home-port,status-admin`


