---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Antes de iniciar a atualização, verifique se você tem o hardware correto para atualizar os modelos de controladora no mesmo chassi. 
---
= Verifique o hardware de atualização
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de iniciar a atualização, verifique se você tem os módulos corretos para o seu sistema de substituição. Se houver peças em falta, entre em Contato com o suporte técnico ou com o representante de vendas da NetApp para obter assistência.

[cols="50,50"]
|===
| Se você estiver atualizando a partir de ... | O sistema de substituição deve ter ... 


| AFF A250, AFF C250 | Dois módulos de controladora e novos módulos de e/S 


| AFF A800, AFF C800 | Dois módulos de controladora, dois NVRAMs e novos módulos de e/S 


 a| 
* AFF A220 configurado como um ASA
* AFF A220, AFF A200, AFF C190
* FAS2620, FAS2720

 a| 
Dois módulos de controlador

Se você estiver convertendo o sistema existente em um compartimento de armazenamento para que possa anexá-lo a outro sistema, o sistema de substituição também deve ter dois módulos de e/S.



 a| 
* AFF A700 configurado como um ASA
* AFF A700
* FAS9000

| Dois controladores e dois módulos NVRAM 
|===