---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/manage_authentication_okm.html 
keywords: manage, authentication, onboard key manager, okm, key, passphrase, fips 
summary: Use o Gerenciador de chaves integrado para gerenciar chaves de autenticação durante uma atualização manual do ARL em controladores que executam o ONTAP 9.8 ou posterior. 
---
= Gerencie chaves de autenticação usando o Gerenciador de chaves integrado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode usar o OKM (Onboard Key Manager) para gerenciar chaves de autenticação. Se você tiver o OKM configurado, você deve Registrar a senha e o material de backup antes de iniciar a atualização.

.Passos
. Grave a frase-passe de todo o cluster.
+
Esta é a senha que foi inserida quando o OKM foi configurado ou atualizado usando a CLI ou API REST.

. Verifique a senha e a operação do key-manager:
+
`security key-manager onboard sync`

+
Quando solicitado, insira a senha OKM de todo o cluster que você registrou na etapa anterior.

. Verifique se cc-mode está ativado consultando a saída do seguinte comando:
+
`security key-manager config show`

. Faça backup das informações do key-manager:
+
`security key-manager onboard show-backup`



.O que se segue?
Após gerenciar as chaves de autenticação usando o Gerenciador de Chaves Integrado, link:quiesce_snapmirror_relationships.html["acalmar os relacionamentos SnapMirror"].
