---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/reboots_panics_power_cycles.html 
keywords: reboot, crash, panic, failure, upgrade 
summary: O sistema pode falhar – reiniciar, entrar em pânico ou passar por um ciclo de energia – durante os diferentes estágios de uma atualização manual do ARL em controladores que executam o ONTAP 9.8 ou posterior. 
---
= Reinicializa, pânicos ou ciclos de energia
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O sistema pode falhar – reiniciar, entrar em pânico ou passar por um ciclo de energia – durante diferentes fases da atualização. A solução para esses problemas depende de quando eles ocorrem.



== Reinicializa, entra em pânico ou ciclos de energia durante a fase 2

Falhas podem ocorrer antes, durante ou imediatamente após a Etapa 2, durante a qual você realocar agregados de node1 para node2, mover LIFs de dados e LIFs SAN de propriedade de node1 para node2, Registrar informações de node1 e desativar node1.



=== node1 ou node2 falha antes da fase 2 com HA ainda ativada

Se o node1 ou o node2 falhar antes da fase 2, ainda não foram transferidos agregados e a configuração de HA ainda está ativada.

.Sobre esta tarefa
A aquisição e a giveback podem prosseguir normalmente.

.Passos
. Verifique se existem mensagens EMS na consola que o sistema possa ter emitido e tome as medidas corretivas recomendadas.
. Continue com o procedimento de atualização do par de nós.




=== node1 falha durante ou logo após a fase 2 com HA ainda ativada

Alguns ou todos os agregados foram realocados de node1 para node2, e a HA ainda está habilitada. O Node2 assumirá o volume raiz do node1 e quaisquer agregados não-raiz que não foram realocados.

.Sobre esta tarefa
A propriedade de agregados que foram realocados parece a mesma que a propriedade de agregados não-raiz que foram assumidos porque o proprietário do lar não mudou. Quando o node1 entra no `waiting for giveback state`, o node2 devolve todos os node1 agregados não-raiz.

.Passos
. Complete link:relocate_non_root_aggr_node1_node2.html#step1["Passo 1"]na seção _relocate agregados não-raiz de node1 para node2_ novamente.
. Continue com o procedimento de atualização do par de nós.




=== O node1 falha após a fase 2 enquanto o HA está desativado

O Node2 não assumirá o controle, mas ainda está fornecendo dados de todos os agregados que não são raiz.

.Passos
. Abra node1.
. Continue com o procedimento de atualização do par de nós.
+
Você pode ver algumas alterações na saída `storage failover show` do comando, mas isso é típico e não afeta o procedimento. Consulte a seção solução de problemas link:issues_multiple_stages_of_procedure.html#storage-failover-command["Failover inesperado de armazenamento mostrar saída de comando"].





=== O Node2 falha durante ou após a Etapa 2 com HA ainda ativada

A node1 mudou parte ou todos os seus agregados para node2. O HA está ativado.

.Sobre esta tarefa
A node1 assumirá todos os agregados da node2, bem como qualquer dos seus agregados que tenha transferido para node2. Quando node2 entra no `Waiting for Giveback` estado, node1 devolve todos os agregados do node2.

.Passos
. Complete link:relocate_non_root_aggr_node1_node2.html#step1["Passo 1"]na seção _relocate agregados não-raiz de node1 para node2_ novamente.
. Continue com o procedimento de atualização do par de nós.




=== Node2 falha após a fase 2 e após HA é desativado

node1 não tomará conta.

.Passos
. Abra node2.
+
Uma interrupção de cliente ocorrerá para todos os agregados enquanto o node2 estiver inicializando.

. Continue com o restante procedimento de atualização do par de nós.




== Reinicializa, entra em pânico ou ciclos de energia durante a fase 3

As falhas podem ocorrer durante ou imediatamente após a fase 3, durante a qual você instala e inicializa node3, mapeia portas de node1 para node3, move LIFs de dados e SAN LIFs pertencentes a node1 e node2 para node3 e realocar todos os agregados de node2 para node3.



=== Node2 falha durante a fase 3 com HA desativada e antes de relocalizar quaisquer agregados

O Node3 não assumirá o controlo após uma falha de node2, uma vez que o HA já está desativado.

.Passos
. Abra node2.
+
Uma interrupção de cliente ocorrerá para todos os agregados enquanto o node2 estiver inicializando.

. Continue com o procedimento de atualização do par de nós.




=== Node2 falha durante a fase 3 após a realocação de alguns ou todos os agregados

A Node2 realocou alguns ou todos os seus agregados para a node3, que servirá dados de agregados que foram realocados. HA está desativada.

.Sobre esta tarefa
Haverá uma interrupção do cliente para agregados que não foram realocados.

.Passos
. Abra node2.
. Relocate os agregados restantes completando-link:relocate_non_root_aggr_node2_node3.html#step3["Passo 3"]os link:relocate_non_root_aggr_node2_node3.html#step1["Passo 1"]na seção _relocate agregados não-raiz de node2 para node3_.
. Continue com o procedimento de atualização do par de nós.




=== Node3 travamentos durante a fase 3 e antes de node2 realocaram quaisquer agregados

O Node2 não assume o controle, mas ainda está fornecendo dados de todos os agregados que não são raiz.

.Passos
. Abra node3.
. Continue com o procedimento de atualização do par de nós.




=== Node3 falha durante a fase 3 durante a realocação de agregados

Se o node3 falhar enquanto o node2 estiver realocando agregados para node3, o node2 cancelará a realocação de quaisquer agregados restantes.

.Sobre esta tarefa
O Node2 continua a servir os agregados restantes, mas os agregados que já foram transferidos para a interrupção do cliente do node3 encontram enquanto o node3 está inicializando.

.Passos
. Abra node3.
. Complete link:relocate_non_root_aggr_node2_node3.html#step3["Passo 3"] novamente na seção _relocate agregados não-root de node2 para node3_.
. Continue com o procedimento de atualização do par de nós.




=== Node3 falha ao inicializar depois de falhar no Estágio 3

Devido a uma falha catastrófica, o node3 não pode ser inicializado após uma falha durante a fase 3.

.Passo
. Entre em Contato com o suporte técnico.




=== Node2 falha após a fase 3, mas antes da fase 5

O Node3 continua fornecendo dados para todos os agregados. O par de HA está desativado.

.Passos
. Abra node2.
. Continue com o procedimento de atualização do par de nós.




=== Node3 falha após a fase 3, mas antes da fase 5

Node3 falha após a fase 3, mas antes da fase 5. O par de HA está desativado.

.Passos
. Abra node3.
+
Haverá uma interrupção do cliente para todos os agregados.

. Continue com o procedimento de atualização do par de nós.




== Reinicializa, entra em pânico ou ciclos de energia durante a fase 5

Falhas podem ocorrer durante a fase 5, a etapa em que você instala e inicializa node4, mapeia portas de node2 para node4, move LIFs de dados e SAN LIFs pertencentes a node2 de node3 para node4 e reposiciona todos os agregados do node2 de node3 para node4.



=== Node3 falha durante a fase 5

A Node3 mudou alguns ou todos os agregados da node2 para node4. O Node4 não assume o controle, mas continua a servir agregados não-raiz que o node3 já realocou. O par de HA está desativado.

.Sobre esta tarefa
Há uma interrupção para o resto dos agregados até que node3 inicialize novamente.

.Passos
. Abra node3.
. Relocate os agregados restantes que pertenciam ao node2 repetindo link:relocate_node2_non_root_aggr_node3_node4.html#man_relocate_3_4_Step1["Passo 1"] link:relocate_node2_non_root_aggr_node3_node4.html#step3["Passo 3"]na seção _relocate os agregados não-raiz do node2 de node3 para node4_.
. Continue com o procedimento de atualização do par de nós.




=== Node4 falha durante a fase 5

A Node3 mudou alguns ou todos os agregados da node2 para node4. O Node3 não assume, mas continua a servir agregados não-raiz que o node3 possui, bem como aqueles que não foram realocados. HA está desativada.

.Sobre esta tarefa
Há uma interrupção para agregados não-raiz que já foram relocados até que o node4 seja inicializado novamente.

.Passos
. Abra node4.
. Relocate os agregados restantes que pertenciam a node2, completando novamente link:relocate_node2_non_root_aggr_node3_node4.html#Step1["Passo 1"] link:relocate_node2_non_root_aggr_node3_node4.html#step3["Passo 3"]em _relocate os agregados não-raiz node2 de node3 para node4_.
. Continue com o procedimento de atualização do par de nós.

