---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: Configure node3 portas FC integradas, portas UTA/UTA2 ou placa UTA/UTA2 durante uma atualização manual do ARL nas controladoras executando o ONTAP 9.8 ou posterior. 
---
= Defina a configuração FC ou UTA/UTA2 em node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o node3 tiver portas FC integradas, portas de adaptador unificado de destino integrado (UTA/UTA2) ou uma placa UTA/UTA2, você deverá configurar as configurações antes de concluir o restante do procedimento.

.Sobre esta tarefa
Talvez seja necessário concluir <<Configurar portas FC no node3>>, ou <<Verifique e configure as portas UTA/UTA2 no node3>>, ou ambas as seções.


NOTE: Os materiais de marketing da NetApp podem usar o termo "UTA2" para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo "CNA".

* Se o node3 não tiver portas FC integradas, portas UTA/UTA2 integradas ou uma placa UTA/UTA2 e estiver atualizando um sistema com discos de storage, será possível pular para o link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"].
* No entanto, se você tiver um sistema V-Series ou um sistema com software de virtualização FlexArray com storage arrays, e o node3 não tiver portas FC integradas, portas UTA/UTA integradas ou uma placa UTA/UTA2, retorne a _Instalar e inicialize node3_ e continue em link:install_boot_node3.html#man_install3_step22["Passo 22"].


.Opções:
* <<Configurar portas FC no node3>>
* <<Verifique e configure as portas UTA/UTA2 no node3>>




== Configurar portas FC no node3

Se o node3 tiver portas FC, integradas ou em um adaptador FC, você precisará definir configurações de porta no nó antes de colocá-lo em serviço, pois as portas não estão pré-configuradas. Se as portas não estiverem configuradas, poderá ocorrer uma interrupção no serviço.

.Antes de começar
Você deve ter os valores das configurações de porta FC de node1 que você salvou link:prepare_nodes_for_upgrade.html["Prepare os nós para atualização"]no .

.Sobre esta tarefa
Você pode ignorar esta seção se o sistema não tiver configurações FC. Se o sistema tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, configure-as no <<Verifique e configure as portas UTA/UTA2 no node3>>.


IMPORTANT: Se o sistema tiver discos de armazenamento, introduza os comandos nesta secção no prompt do cluster. Se você tiver um sistema da série V ou tiver um software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, digite os comandos nesta seção no modo de manutenção.

.Passos
. Execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento | Vá para <<man_config_3_step5,Passo 5>> 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Vá para <<man_config_3_step2,Passo 2>> 
|===
. [[man_config_3_step2]]Boot node3 e modo de manutenção de acesso:
+
`boot_ontap maint`

. [[step3]]Faça uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento | Introduza o seguinte comando: 
`system node hardware unified-connect show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento. | Introduza o seguinte comando 
`ucadmin show` 
|===
+
O sistema exibe informações sobre todos os adaptadores de rede FC e convergentes no sistema.

. [[step4]]Compare as configurações FC de node3 com as configurações que você capturou anteriormente de node1.
. [[man_config_3_step5]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se as configurações de FC padrão nos novos nós forem... | Então... 


| O mesmo que aqueles que você capturou no node1 | Vá para <<man_config_3_step11,Passo 11>>. 


| Diferente dos que você capturou no node1 | Vá para <<man_config_3_step6,Passo 6>>. 
|===
. [[man_config_3_step6]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
Modifique as portas FC no node3 conforme necessário inserindo um dos seguintes comandos:

** Para programar portas de destino:
`system node hardware unified-connect modify -type | -t target -adapter _port_name_`
** Para programar portas do iniciador:
`system node hardware unified-connect modify -type | -t initiator -adapter _port_name_`


`-t` É o tipo FC4: Alvo ou iniciador.



| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
Modifique as portas FC no node3 conforme necessário inserindo o seguinte comando:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` É o tipo FC4, alvo ou iniciador.


NOTE: As portas FC devem ser programadas como iniciadores.

|===
. [[step7]]Faça uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento | Verifique as novas configurações inserindo o seguinte comando e examinando a saída: 
`system node hardware unified-connect show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Verifique as novas configurações inserindo o seguinte comando e examinando a saída: 
`ucadmin show` 
|===
. [[step8]]saia do modo de manutenção inserindo o seguinte comando:
+
`halt`

. [[step9]]depois de inserir o comando, aguarde até que o sistema pare no prompt do ambiente de inicialização.
. [[step10]]Faça uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema que você está atualizando... | Então... 


| É um sistema V-Series ou tem software de virtualização FlexArray executando o Clustered Data ONTAP 8.3 | Inicialize o node3 e acesse a manutenção no prompt do ambiente de inicialização: 
`boot_ontap maint` 


| Não é um sistema da série V ou não tem software de virtualização FlexArray | Inicialize node3 no prompt do ambiente de inicialização: 
`boot_ontap` 
|===
. [[man_config_3_step11]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema que você está atualizando... | Então... 


| Tem discos de armazenamento  a| 
** Se o node3 tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa UTA/UTA2 ou portas integradas UTA/UTA2, pule <<Verifique e configure as portas UTA/UTA2 no node3>> e vá para link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"].




| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento  a| 
** Se o node3 tiver uma placa ou portas integradas, vá para <<Verifique e configure as portas UTA/UTA2 no node3>>.
** Se o node3 não tiver uma placa ou portas integradas, pule <<Verifique e configure as portas UTA/UTA2 no node3>>e retorne a _Install and boot node3_ e continue em link:install_boot_node3.html#man_install3_step7["Passo 7"].


|===




== Verifique e configure as portas UTA/UTA2 no node3

Se o node3 tiver portas UTA/UTA2 integradas ou uma placa UTA/UTA2, você deve verificar a configuração das portas e, possivelmente, reconfigurá-las, dependendo de como você deseja usar o sistema atualizado.

.Antes de começar
Você deve ter os módulos SFP corretos para as portas UTA/UTA2.

.Sobre esta tarefa
Se pretender utilizar uma porta de adaptador de destino unificado (UTA/UTA2) para FC, tem de verificar primeiro a forma como a porta está configurada.


NOTE: Os materiais de marketing da NetApp podem usar o termo UTA2 para se referir a adaptadores e portas CNA. No entanto, a CLI usa o termo CNA.

Você pode usar o `ucadmin show` comando para verificar a configuração atual da porta:

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
As PORTAS UTA/UTA2 podem ser configuradas no modo FC nativo ou no modo UTA/UTA2. O modo FC suporta iniciador FC e destino FC; o modo UTA/UTA2 permite o compartilhamento simultâneo de tráfego NIC e FCoE na mesma interface SFP 10GbE e suporta destinos FC.

As PORTAS UTA/UTA2 podem ser encontradas em um adaptador ou no controlador e têm as seguintes configurações, mas você deve verificar a configuração das portas UTA/UTA2 no node3 e alterá-lo, se necessário:

* Os cartões UTA/UTA2 encomendados quando o controlador é encomendado são configurados antes do envio para ter a personalidade que você solicita.
* Os cartões UTA/UTA2 encomendados separadamente do controlador são fornecidos com a personalidade de destino padrão do FC.
* As portas UTA/UTA2 integradas em novos controladores são configuradas antes do envio para ter a personalidade que você solicita.
+

NOTE: *Atenção*: Se o seu sistema tiver discos de armazenamento, você deve inserir os comandos nesta seção no prompt do cluster, a menos que seja direcionado para entrar no modo de manutenção. Se você tiver um sistema VSeries ou tiver um software de virtualização FlexArray e estiver conetado a matrizes de armazenamento, você deve inserir comandos nesta seção no prompt do modo de manutenção. Você deve estar no modo de manutenção para configurar portas UTA/UTA2.



.Passos
. Verifique como as portas estão atualmente configuradas entrando nos seguintes comandos no node3:
+
[cols="35,65"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `system node hardware unified-connect show` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
O sistema exibe a saída semelhante aos seguintes exemplos:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending  Admin
Adapter  Mode     Type       Mode     Type     Status
-------  -------  ---------  -------  -------  ------
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
*>
----
. [[step2]]se o módulo SFP atual não corresponder ao uso desejado, substitua-o pelo módulo SFP correto.
+
Entre em Contato com seu representante da NetApp para obter o módulo SFP correto.

. [[step3]]examine a saída do `system node hardware unified-connect show` comando OR `ucadmin show` para determinar se as portas UTA/UTA2 têm a personalidade que você deseja.
. [[step4]]Faça uma das seguintes ações:
+
[cols="35,65"]
|===
| Se as portas UTA/UTA2... | Então... 


| Não tenha a personalidade que você quer | Vá para <<man_check_3_step5,Passo 5>>. 


| Tenha a personalidade que você quer | Pule a Etapa 5 até a Etapa 12 e vá para <<man_check_3_step13,Passo 13>>. 
|===
. [[man_check_3_step5]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema... | Então... 


| Tem discos de storage e está executando o Clustered Data ONTAP 8.3 | Inicialize node3 e entre no modo de manutenção: 
`boot_ontap maint` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Vá para <<man_check_3_step6,Passo 6>>. Você já deve estar no modo de manutenção. 
|===
. [[man_check_3_step6]]execute uma das seguintes ações:
+
[cols="35,65"]
|===
| Se você estiver configurando... | Então... 


| Portas em uma placa UTA/UTA2 | Vá para <<man_check_3_step7,Passo 7>>. 


| Portas UTA/UTA2 integradas | Pule a Etapa 7 e vá para <<man_check_3_step8,Passo 8>>. 
|===
. [[man_check_3_step7]]se o adaptador estiver no modo iniciador e se a porta UTA/UTA2 estiver online, coloque a porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Os adaptadores no modo de destino são automaticamente offline no modo de manutenção.

. [[man_check_3_step8]]se a configuração atual não corresponder ao uso desejado, altere a configuração conforme necessário:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` é o modo personalidade, `fc` ou `cna`.
** `-t` É o tipo FC4, `target` ou `initiator`.
+

NOTE: Você precisa usar o iniciador FC para unidades de fita, sistemas de virtualização FlexArray e configurações MetroCluster. Você precisa usar o destino FC para clientes SAN.



. Verifique as configurações:
+
`ucadmin show`

. Verifique as configurações:
+
[cols="35,65"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento  a| 
.. Parar o sistema:
+
`halt`

+
O sistema pára no prompt do ambiente de inicialização.

.. Introduza o seguinte comando:
+
`boot_ontap`





| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Reiniciar para o modo de manutenção: 
`boot_netapp maint` 
|===
. [[step11]]Verifique as definições:
+
[cols="35,65"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `system node hardware unified-connect show` 


| É um V-Series ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `ucadmin show` 
|===
+
A saída nos exemplos a seguir mostra que o tipo FC4 de adaptador "1b" está mudando para `initiator` e que o modo dos adaptadores "2a" e "2b" está mudando para `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending    Admin
Adapter  Mode     Type       Mode     Type       Status
-------  -------  ---------  -------  ---------  ------
1a       fc       initiator  -        -          online
1b       fc       target     -        initiator  online
2a       fc       target     cna      -          online
2b       fc       target     cna      -          online
*>
----
. [[step12a]]coloque quaisquer portas de destino online inserindo um dos seguintes comandos, uma vez para cada porta:
+
[cols="35,65"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | `fcp config _adapter_name_ up` 
|===
. [[man_check_3_step13]]Faça o cabo da porta.
. [[step14]]Faça uma das seguintes ações:
+
[cols="35,65"]
|===
| Se o sistema... | Então... 


| Tem discos de armazenamento | Vá para link:map_ports_node1_node3.html["Portas de mapa de node1 a node3"]. 


| É um sistema da série V ou tem software de virtualização FlexArray e está conetado a matrizes de armazenamento | Retorne a _Install and boot node3_ e continue em link:install_boot_node3.html#man_install3_step7["Passo 7"]. 
|===

