---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: Se necessário, configure o novo módulo de controladora para NVE ou NAE durante uma atualização manual do ARL em controladores que executam o ONTAP 9.8 ou posterior. 
---
= Configure o volume NetApp ou a criptografia Aggregte no novo módulo do controlador
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se a controladora substituída ou o parceiro de alta disponibilidade (HA) da nova controladora usar o NetApp volume Encryption (NVE) ou o NetApp Aggregate Encryption (NAE), você deverá configurar o novo módulo de controladora para NVE ou NAE.

.Sobre esta tarefa
Este procedimento inclui etapas que são executadas no novo módulo do controlador. Você deve inserir o comando no nó correto.

.Passos
. Verifique se os servidores de gerenciamento de chaves ainda estão disponíveis, seu status e suas informações de chave de autenticação:
+
`security key-manager key query -node node`

. Adicione os servidores de gerenciamento de chaves listados na etapa anterior à lista de servidores de gerenciamento de chaves no novo controlador:
+
.. Adicione o servidor de gerenciamento de chaves usando o seguinte comando:
+
`security key-manager -add _key_management_server_ip_address_`

.. Repita a etapa anterior para cada servidor de gerenciamento de chaves listado. Você pode vincular até quatro servidores de gerenciamento de chaves.
.. Verifique se os servidores de gerenciamento de chaves foram adicionados com sucesso usando o seguinte comando:
+
`security key-manager show`



. No novo módulo do controlador, execute o assistente de configuração de gerenciamento de chaves para configurar e instalar os servidores de gerenciamento de chaves.
+
Você deve instalar os mesmos servidores de gerenciamento de chaves que estão instalados no módulo de controlador existente.

+
.. Inicie o assistente de configuração do servidor de gerenciamento de chaves no novo nó usando o seguinte comando:
+
`security key-manager setup -node _new_controller_name_`

.. Conclua as etapas no assistente para configurar servidores de gerenciamento de chaves.


. Restaure chaves de autenticação de todos os servidores de gerenciamento de chaves vinculados para o novo nó:
+
[cols="35,65"]
|===
| Para... | Use este comando... 


| Gerenciador de chaves externo | `security key-manager external restore` Esse comando precisa da senha OKM 


| Gerenciador de chaves integrado (OKM) | `security key-manager onboard sync` 
|===
+
Para obter mais informações, consulte o artigo da base de dados de Conhecimento https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["Como restaurar a configuração do servidor gerenciador de chaves externo a partir do menu de inicialização do ONTAP"^] .



.Depois de terminar
Verifique se algum volume foi colocado offline porque as chaves de autenticação não estavam disponíveis ou os servidores de Gerenciamento de chaves externas não puderam ser alcançados. Traga esses volumes de volta online usando o `volume online` comando.
