---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_6_index.html 
keywords: stage 6, complete, upgrade, set up, setup, controller, storage encryption, netapp encryption, decommission, resume snapmirror 
summary: Sequência de processo do estágio 6 para uma atualização manual do ARL em controladores que executam o ONTAP 9.8 ou posterior. 
---
= Visão geral da fase 6
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a fase 6, você confirma que os novos nós estão configurados corretamente e, se os novos nós estiverem habilitados para criptografia, você configura e configura a criptografia de armazenamento ou a criptografia de volume do NetApp. Você também deve desativar os nós antigos e retomar as operações do SnapMirror.

. link:manage_authentication_kmip.html["Gerenciar a autenticação usando servidores KMIP"]
. link:ensure_controllers_set_up_correctly.html["Confirme se os novos controladores estão configurados corretamente"]
. link:set_up_storage_encryption_new_controller.html["Configure a criptografia de armazenamento no novo módulo do controlador"]
. link:set_up_netapp_encryption_on_new_controller.html["Configure o volume NetApp ou a encriptação agregada no novo módulo do controlador"]
. link:decommission_old_system.html["Desativar o sistema antigo"]
. link:resume_snapmirror_ops.html["Retomar as operações do SnapMirror"]

