---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/worksheet_information_before_moving_san_lifs_node3.html 
keywords: worksheet, information, SAN, LIF, switch, port, adapter 
summary: Registre as informações de configuração de LIF de dados do nas node1 durante uma atualização manual do ARL em controladores que executam o ONTAP 9.8 ou posterior. 
---
= Worksheet: Informações a serem registradas antes de mover LIFs de dados nas para node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para ajudar a verificar se tem a configuração correta depois de mover SAN LIFs de node2 para node3, pode utilizar a seguinte folha de cálculo para registar as `adapter` informações e `switch-port` para cada LIF.

Registre as informações de LIF `adapter` da `network interface show -data-protocol fc*` saída do comando e as `switch-port` informações da `fcp adapter show -fields switch-port,fc-wwpn` saída do comando para node2.

Depois de concluir a migração para o node3, Registre o `adapter` LIF e `switch-port` as informações para os LIFs no node3 e verifique se cada LIF ainda está conetado ao mesmo `switch-port`.

[cols="6*"]
|===
3+| Node2 3+| Node3 


| LIF | `adapter` | `switch-port` | LIF | `adapter` | `switch-port` 


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  
|===