---
sidebar: sidebar 
permalink: upgrade-arl/index.html 
keywords: aggregate, relocation, moving, manual, upgrade, relocate, hardware 
summary: Use a realocação de agregados para atualizar o hardware do controlador 
---
= Comece aqui: Escolha seu procedimento de atualização ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o hardware do controlador sem interrupção usando o ARL (Aggregate Relocation). Para obter outros métodos de atualização do hardware do controlador, link:../upgrade/upgrade-decide-to-use-this-guide.html["Atualize movendo volumes ou armazenamento"]consulte .

Com o ARL, você atualiza o hardware da controladora de forma ininterrupta em um par de nós que executam o ONTAP, migrando agregados sem raiz dos nós originais para os novos nós no mesmo cluster. Os dados hospedados nos nós que estão sendo atualizados estão acessíveis durante a atualização.

O ARL aproveita a configuração de HA para oferecer a capacidade de mover a propriedade de agregados que não são raiz de um nó para outro, se eles compartilharem storage no mesmo cluster.

Existem vários métodos ARL para atualizar o hardware do controlador. Para selecionar o procedimento adequado, consulte as informações a seguir sobre os sistemas e as versões do ONTAP suportadas para cada opção de atualização do ARL.



== Use os comandos "System controller replace" com ONTAP 9.15,1 ou posterior

Se o cenário de atualização estiver listado na seguinte matriz de sistemas suportados, vá para para link:../upgrade-arl-auto-app-9151/index.html["Use os comandos "System controller replace" para atualizar o hardware do controlador introduzido no ONTAP 9.15.1 e posterior"] para iniciar o procedimento de atualização.

.Mostrar sistemas suportados
[%collapsible]
====
|===
| Controlador existente | Controlador de substituição | Suportado a partir do ONTAP... 


| AFF A400 | AFF A50 | 9.16.1 


| AFF A300 | AFF A50 | 9.16.1 


| AFF A220, AFF A150 | AFF A20 | 9.16.1 


| AFF C400 | AFF C60, AFF C80 | 9.16.1 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | 9.15.1P3 para FAS70, FAS90 9.16.1P2 para FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70, AFF A90, AFF A1K | 9.15.1 


| AFF A900 | AFF A90, AFF A1K | 9.15.1 
|===
====


== Atualize os modelos de controladora no mesmo chassi

Se o seu cenário de atualização estiver listado na seguinte matriz de sistemas suportados, vá paralink:../upgrade-arl-auto-in-chassis/index.html["Use os comandos "System controller replace" para atualizar os modelos de controladora no mesmo chassi"] para iniciar o procedimento de atualização.

.Mostrar sistemas suportados
[%collapsible]
====
[cols="20,20,40"]
|===
| Sistema antigo | Sistema de substituição | Versões de ONTAP compatíveis 


| AFF C250 | AFF C30, AFF C60 | 9.16.1 e mais tarde 


| AFF A250 | AFF A50, AFF A30 | 9.16.1 e mais tarde 


| AFF C800 | AFF C80 | 9.16.1 e mais tarde 


| AFF A800 | AFF A70 ou AFF A90 | 9.15.1 e mais tarde 


| AFF A220 configurado como um All SAN Array (ASA) | ASA A150 | 9.13.1P1 e posterior 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e posterior 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 e posterior

*Nota*: O AFF A200 não suporta versões ONTAP posteriores a 9.11.1.



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e posterior 


| FAS2620 | FAS2820  a| 
9.11.1P7 ou versões de patch posteriores (FAS2620)

*Nota*: O FAS2620 não suporta versões ONTAP posteriores a 9.11.1.

9.13.1 e posterior (FAS2820)



| FAS2720 | FAS2820 | 9.13.1 e mais tarde 


| AFF A700 configurado como um ASA | ASA A900 | 9.13.1P1 e posterior 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 e posterior 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 e posterior 
|===
====


== Use os comandos "System controller replace" com o ONTAP 9.8 ou posterior

Se o cenário de atualização estiver listado na seguinte matriz de sistemas suportados, vá para para link:../upgrade-arl-auto-app/index.html["Use os comandos "System controller replace" para atualizar o hardware da controladora executando o ONTAP 9.8 ou posterior"] para iniciar o procedimento de atualização.

.Mostrar sistemas suportados
[%collapsible]
====
|===
| Controlador antigo | Controlador de substituição 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| FAS8060, FAS8080 | FAS9500 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800 


| AFF8060, AFF8080 | AFF A900 


| FAS8200 | FAS8300, FAS8700, FAS9000, FAS9500 


| FAS8300, FAS8700, FAS9000 | FAS9500 


| AFF A300 | AFF A400, AFF A700, AFF A800, AFF A900 


| AFF A320 | AFF A400 


| AFF A400, AFF A700 | AFF A900 
|===
====


== Use os comandos "System controller replace" com ONTAP 9.5 a 9,7

Se o cenário de atualização estiver listado na seguinte matriz de sistemas suportados, vá para para link:../upgrade-arl-auto/index.html["Use os comandos "System controller replace" para atualizar o hardware da controladora executando o ONTAP 9.5 a 9,7"] para iniciar o procedimento de atualização.

.Mostrar sistemas suportados
[%collapsible]
====
[cols="50,50"]
|===
| Controlador antigo | Controlador de substituição 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800 


| FAS8200 | FAS8700, FAS9000, FAS8300 


| AFF A300 | AFF A700, AFF A800, AFF A400 
|===
====


== Use comandos ARL manuais

Se o cenário de atualização não for suportado usando "comandos do sistema", você pode executar uma atualização ARL usando comandos manuais.

.Mostrar sistemas suportados
[%collapsible]
====
[role="tabbed-block"]
=====
.ONTAP 9.8 ou posterior
--
As atualizações manuais do ARL são suportadas pelos seguintes sistemas que executam o ONTAP 9.8 e versões posteriores:

* Sistema FAS para sistema FAS
* Sistema AFF para sistema AFF
+
Só pode atualizar para um sistema de substituição na mesma série:

+
** Sistema AFF A-Series para sistema AFF A-Series
** Sistema AFF C-Series para sistema AFF C-Series


* Sistema ASA para sistema ASA
+

NOTE: As atualizações ASA para um sistema de substituição ASA R2 não são suportadas. Para obter informações sobre como migrar dados do ASA para o ASA R2, link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Habilite o acesso a dados de hosts SAN ao seu sistema de storage ASA R2"^]consulte .

+
Só pode atualizar para um sistema de substituição na mesma série:

+
** Sistema ASA A-Series para sistema ASA A-Series
** Sistema ASA C-Series para sistema ASA C-Series




link:../upgrade-arl-manual-app/index.html["Atualize manualmente o hardware da controladora executando o ONTAP 9.8 ou posterior"]

--
.ONTAP 9.7 ou anterior
--
As atualizações manuais do ARL são suportadas pelos seguintes sistemas que executam o ONTAP 9.7 e versões anteriores:

* Sistema FAS para sistema FAS
* Sistema AFF para sistema AFF


link:../upgrade-arl-manual/index.html["Atualize manualmente o hardware da controladora executando o ONTAP 9.7 ou anterior"]

--
=====
====